// The AI Workshop Zone's own words. Packages bring their strings; the platform
// passes the interface locale in `zone.locale`, and any other locale reads English.

const en = {
  official: 'Official REZICS Zone',
  tagline: 'Prompts, skills and small tools for reading and writing with AI.',
  browse: 'Browse every prompt and skill',
  featured: 'Featured',
  copy: {
    prompt: { label: 'Copy prompt', copied: 'Prompt copied', failed: 'Could not copy the prompt' },
    skill: { label: 'Copy Skill', copied: 'Skill instructions copied', failed: 'Could not copy the Skill' },
    link: { label: 'Copy link', copied: 'Link copied', failed: 'Could not copy the link' },
  },
  kind: { prompt: 'Prompt', skill: 'Skill' },
  preview: 'Preview',
  testedWith: 'Tested with',
  tryIt: 'Try it',
  by: (author: string) => `by ${author}`,
  untitled: 'Untitled',
  collection: 'Collection',
  count: (count: number) => count === 1 ? '1 prompt or skill' : `${count} prompts and skills`,
  more: 'See all',
  footerTitle: 'AI Workshop on REZICS',
  footerNote: 'Every prompt and skill here was placed by a public decision. Follow the stamp on any card to see why.',
  works: 'Every prompt and skill',
  decisions: 'Decision log',
  about: 'About and rules',
};

type Strings = typeof en;

const translations: Record<string, Strings> = {
  en,
  'zh-Hans': {
    official: 'REZICS 官方专区',
    tagline: '用 AI 读书和写作的提示词、技能与小工具。',
    browse: '浏览全部提示词与技能',
    featured: '精选',
    copy: {
      prompt: { label: '复制提示词', copied: '提示词已复制', failed: '无法复制提示词' },
      skill: { label: '复制技能', copied: '技能说明已复制', failed: '无法复制技能' },
      link: { label: '复制链接', copied: '链接已复制', failed: '无法复制链接' },
    },
    kind: { prompt: '提示词', skill: '技能' },
    preview: '预览',
    testedWith: '已测试',
    tryIt: '试一试',
    by: (author: string) => `作者 ${author}`,
    untitled: '未命名',
    collection: '合集',
    count: (count: number) => `${count} 个提示词与技能`,
    more: '查看全部',
    footerTitle: 'REZICS AI 工作坊',
    footerNote: '这里的每条提示词和技能都来自一项公开决定。点开卡片上的印章，就能看到它为什么在这里。',
    works: '全部提示词与技能',
    decisions: '决定记录',
    about: '关于与规则',
  },
  'zh-Hant': {
    official: 'REZICS 官方 Zone',
    tagline: '用 AI 讀書和寫作的提示詞、技能與小工具。',
    browse: '瀏覽全部提示詞與技能',
    featured: '精選',
    copy: {
      prompt: { label: '複製提示詞', copied: '提示詞已複製', failed: '無法複製提示詞' },
      skill: { label: '複製技能', copied: '技能說明已複製', failed: '無法複製技能' },
      link: { label: '複製連結', copied: '連結已複製', failed: '無法複製連結' },
    },
    kind: { prompt: '提示詞', skill: '技能' },
    preview: '預覽',
    testedWith: '已測試',
    tryIt: '試試看',
    by: (author: string) => `作者 ${author}`,
    untitled: '未命名',
    collection: '合集',
    count: (count: number) => `${count} 項提示詞與技能`,
    more: '查看全部',
    footerTitle: 'REZICS AI 工作坊',
    footerNote: '這裡的每條提示詞和技能都來自一項公開決定。點開卡片上的印章，就能看到它為什麼在這裡。',
    works: '全部提示詞與技能',
    decisions: '決策紀錄',
    about: '關於與規則',
  },
  ko: {
    official: 'REZICS 공식 Zone',
    tagline: 'AI로 읽고 쓰는 데 도움이 되는 프롬프트, 스킬, 작은 도구.',
    browse: '모든 프롬프트와 스킬 둘러보기',
    featured: '추천',
    copy: {
      prompt: { label: '프롬프트 복사', copied: '프롬프트를 복사했어요', failed: '프롬프트를 복사하지 못했어요' },
      skill: { label: '스킬 복사', copied: '스킬 지침을 복사했어요', failed: '스킬을 복사하지 못했어요' },
      link: { label: '링크 복사', copied: '링크를 복사했어요', failed: '링크를 복사하지 못했어요' },
    },
    kind: { prompt: '프롬프트', skill: '스킬' },
    preview: '미리 보기',
    testedWith: '테스트한 모델',
    tryIt: '사용해 보기',
    by: (author: string) => `${author} 작성`,
    untitled: '제목 없음',
    collection: '컬렉션',
    count: (count: number) => `프롬프트와 스킬 ${count}개`,
    more: '모두 보기',
    footerTitle: 'REZICS AI 워크숍',
    footerNote: '여기에 있는 모든 프롬프트와 스킬은 공개된 결정에 따라 선정되었습니다. 카드의 도장을 누르면 선정 이유를 볼 수 있어요.',
    works: '모든 프롬프트와 스킬',
    decisions: '결정 내역',
    about: '소개와 규칙',
  },
  de: {
    official: 'Offizielle REZICS Zone',
    tagline: 'Prompts, Skills und kleine Werkzeuge zum Lesen und Schreiben mit KI.',
    browse: 'Alle Prompts und Skills ansehen',
    featured: 'Vorgestellt',
    copy: {
      prompt: { label: 'Prompt kopieren', copied: 'Prompt kopiert', failed: 'Der Prompt konnte nicht kopiert werden' },
      skill: { label: 'Skill kopieren', copied: 'Skill-Anweisungen kopiert', failed: 'Der Skill konnte nicht kopiert werden' },
      link: { label: 'Link kopieren', copied: 'Link kopiert', failed: 'Der Link konnte nicht kopiert werden' },
    },
    kind: { prompt: 'Prompt', skill: 'Skill' },
    preview: 'Vorschau',
    testedWith: 'Getestet mit',
    tryIt: 'Ausprobieren',
    by: (author: string) => `von ${author}`,
    untitled: 'Ohne Titel',
    collection: 'Sammlung',
    count: (count: number) => count === 1 ? '1 Prompt oder Skill' : `${count} Prompts und Skills`,
    more: 'Alle ansehen',
    footerTitle: 'AI Workshop auf REZICS',
    footerNote: 'Alle Prompts und Skills hier wurden aufgrund einer öffentlichen Entscheidung ausgewählt. Öffne den Stempel auf einer Karte, um zu erfahren, warum sie hier ist.',
    works: 'Alle Prompts und Skills',
    decisions: 'Entscheidungsprotokoll',
    about: 'Über die Zone und ihre Regeln',
  },
  ja: {
    official: 'REZICS 公式 Zone',
    tagline: 'AIを使った読書や執筆に役立つプロンプト、スキル、小さなツール。',
    browse: 'プロンプトとスキルをすべて見る',
    featured: '注目',
    copy: {
      prompt: { label: 'プロンプトをコピー', copied: 'プロンプトをコピーしました', failed: 'プロンプトをコピーできませんでした' },
      skill: { label: 'スキルをコピー', copied: 'スキルの指示をコピーしました', failed: 'スキルをコピーできませんでした' },
      link: { label: 'リンクをコピー', copied: 'リンクをコピーしました', failed: 'リンクをコピーできませんでした' },
    },
    kind: { prompt: 'プロンプト', skill: 'スキル' },
    preview: 'プレビュー',
    testedWith: 'テスト済みモデル',
    tryIt: '試してみる',
    by: (author: string) => `作者：${author}`,
    untitled: 'タイトル未設定',
    collection: 'コレクション',
    count: (count: number) => count === 1 ? '1件のプロンプトまたはスキル' : `${count}件のプロンプト・スキル`,
    more: 'すべて見る',
    footerTitle: 'REZICSのAIワークショップ',
    footerNote: 'ここに掲載されているプロンプトとスキルは、すべて公開決定に基づいて選ばれています。カードのスタンプをたどると、選定理由を確認できます。',
    works: 'すべてのプロンプトとスキル',
    decisions: '決定ログ',
    about: '概要とルール',
  },
  fr: {
    official: 'Zone officielle REZICS',
    tagline: 'Prompts, compétences et petits outils pour lire et écrire avec l’IA.',
    browse: 'Parcourir tous les prompts et toutes les compétences',
    featured: 'À la une',
    copy: {
      prompt: { label: 'Copier le prompt', copied: 'Prompt copié', failed: 'Impossible de copier le prompt' },
      skill: { label: 'Copier la compétence', copied: 'Instructions de la compétence copiées', failed: 'Impossible de copier la compétence' },
      link: { label: 'Copier le lien', copied: 'Lien copié', failed: 'Impossible de copier le lien' },
    },
    kind: { prompt: 'Prompt', skill: 'Compétence' },
    preview: 'Aperçu',
    testedWith: 'Testé avec',
    tryIt: 'Essayer',
    by: (author: string) => `par ${author}`,
    untitled: 'Sans titre',
    collection: 'Collection',
    count: (count: number) => count === 1 ? '1 prompt ou une compétence' : `${count} prompts et compétences`,
    more: 'Tout voir',
    footerTitle: 'Atelier IA sur REZICS',
    footerNote: 'Tous les prompts et toutes les compétences de cette Zone ont été retenus à l’issue de décisions publiques. Ouvrez le sceau d’une fiche pour découvrir pourquoi.',
    works: 'Tous les prompts et toutes les compétences',
    decisions: 'Journal des décisions',
    about: 'Présentation et règles',
  },
  es: {
    official: 'Zone oficial de REZICS',
    tagline: 'Prompts, habilidades y pequeñas herramientas para leer y escribir con IA.',
    browse: 'Explora todos los prompts y las habilidades',
    featured: 'Destacados',
    copy: {
      prompt: { label: 'Copiar prompt', copied: 'Prompt copiado', failed: 'No se pudo copiar el prompt' },
      skill: { label: 'Copiar habilidad', copied: 'Instrucciones de la habilidad copiadas', failed: 'No se pudo copiar la habilidad' },
      link: { label: 'Copiar enlace', copied: 'Enlace copiado', failed: 'No se pudo copiar el enlace' },
    },
    kind: { prompt: 'Prompt', skill: 'Habilidad' },
    preview: 'Vista previa',
    testedWith: 'Probado con',
    tryIt: 'Probarlo',
    by: (author: string) => `por ${author}`,
    untitled: 'Sin título',
    collection: 'Colección',
    count: (count: number) => count === 1 ? '1 prompt o una habilidad' : `${count} prompts y habilidades`,
    more: 'Ver todo',
    footerTitle: 'Taller de IA en REZICS',
    footerNote: 'Todos los prompts y todas las habilidades de esta Zone se han incluido tras decisiones públicas. Abre el sello de cualquier ficha para ver el motivo.',
    works: 'Todos los prompts y las habilidades',
    decisions: 'Registro de decisiones',
    about: 'Información y normas',
  },
};

export function strings(locale: string): Strings {
  return translations[locale] ?? en;
}
