-- Reviewed field/grain dispositions for the Open Library works run surfaces (LIVE01).
-- A field observed but not declared here is reported as unsupported/undeclared-field.
INSERT INTO source.field_mapping (mapping_revision, provider, namespace, root_grain, field_count)
VALUES ('open-library-run-map-v1', 'open-library', 'work', 'work', 52);
INSERT INTO source.field_disposition (mapping_revision, grain, field_key, disposition, value_kind, reason,
  native_target, loss)
SELECT 'open-library-run-map-v1', grain, field_key, disposition, value_kind, reason, native_target, loss
FROM (VALUES
  ('work', 'key', 'structured-source-only', 'identifier', 'Source identity; never native identity', NULL, NULL),
  ('work', 'title', 'native', 'language-text', 'Title-only adoption after an affirmed English language', 'work-metadata-v1#title:en', NULL),
  ('work', 'description', 'structured-source-only', 'text', 'Source expression in the private source graph; rights undetermined', NULL, NULL),
  ('work', 'authors', 'structured-source-only', 'reference', 'Source author references; native credits need explicit adoption', NULL, NULL),
  ('work', 'subjects', 'structured-source-only', 'term', 'Source-qualified subject terms', NULL, NULL),
  ('work', 'revision', 'structured-source-only', 'metadata', 'Recorded as the observation source revision', NULL, NULL),
  ('work', 'type', 'unsupported', 'metadata', 'Retained raw bytes only; no structured mapping in this revision', NULL, NULL),
  ('work', 'latest_revision', 'unsupported', 'metadata', 'Retained raw bytes only; no structured mapping in this revision', NULL, NULL),
  ('work', 'created', 'unsupported', 'time', 'Retained raw bytes only; no structured mapping in this revision', NULL, NULL),
  ('work', 'last_modified', 'unsupported', 'time', 'Retained raw bytes only; no structured mapping in this revision', NULL, NULL),
  ('work', 'subtitle', 'unsupported', 'text', 'Retained raw bytes only; no structured mapping in this revision', NULL, NULL),
  ('work', 'subject_places', 'unsupported', 'term', 'Retained raw bytes only; no structured mapping in this revision', NULL, NULL),
  ('work', 'subject_people', 'unsupported', 'term', 'Retained raw bytes only; no structured mapping in this revision', NULL, NULL),
  ('work', 'subject_times', 'unsupported', 'term', 'Retained raw bytes only; no structured mapping in this revision', NULL, NULL),
  ('work', 'covers', 'unsupported', 'reference', 'Retained raw bytes only; no structured mapping in this revision', NULL, NULL),
  ('work', 'links', 'unsupported', 'reference', 'Retained raw bytes only; no structured mapping in this revision', NULL, NULL),
  ('work', 'excerpts', 'unsupported', 'text', 'Retained raw bytes only; no structured mapping in this revision', NULL, NULL),
  ('work', 'first_publish_date', 'unsupported', 'time', 'Retained raw bytes only; no structured mapping in this revision', NULL, NULL),
  ('work', 'first_sentence', 'unsupported', 'text', 'Retained raw bytes only; no structured mapping in this revision', NULL, NULL),
  ('work', 'dewey_number', 'unsupported', 'identifier', 'Retained raw bytes only; no structured mapping in this revision', NULL, NULL),
  ('work', 'lc_classifications', 'unsupported', 'identifier', 'Retained raw bytes only; no structured mapping in this revision', NULL, NULL),
  ('work', 'location', 'unsupported', 'metadata', 'Retained raw bytes only; no structured mapping in this revision', NULL, NULL),
  ('edition', 'key', 'unsupported', 'identifier', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'title', 'unsupported', 'text', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'subtitle', 'unsupported', 'text', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'full_title', 'unsupported', 'text', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'works', 'unsupported', 'reference', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'authors', 'unsupported', 'reference', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'publishers', 'unsupported', 'text', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'publish_date', 'unsupported', 'time', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'publish_places', 'unsupported', 'text', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'isbn_10', 'unsupported', 'identifier', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'isbn_13', 'unsupported', 'identifier', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'lccn', 'unsupported', 'identifier', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'oclc_numbers', 'unsupported', 'identifier', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'identifiers', 'unsupported', 'identifier', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'number_of_pages', 'unsupported', 'quantity', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'pagination', 'unsupported', 'text', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'languages', 'unsupported', 'reference', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'covers', 'unsupported', 'reference', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'physical_format', 'unsupported', 'term', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'edition_name', 'unsupported', 'text', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'series', 'unsupported', 'text', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'source_records', 'unsupported', 'reference', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'ocaid', 'unsupported', 'identifier', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'type', 'unsupported', 'metadata', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'revision', 'unsupported', 'metadata', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'latest_revision', 'unsupported', 'metadata', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'created', 'unsupported', 'time', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('edition', 'last_modified', 'unsupported', 'time', 'Edition page retained raw only; no native edition is fabricated', NULL, NULL),
  ('ratings', 'summary', 'unsupported', 'statistic', 'Provider statistic retained raw only; never a native rating or ballot', NULL, NULL),
  ('ratings', 'counts', 'unsupported', 'statistic', 'Provider statistic retained raw only; never a native rating or ballot', NULL, NULL)
) AS declared (grain, field_key, disposition, value_kind, reason, native_target, loss);
