import { healthRoutes } from '../../../services/main/src/routes/health.ts';
import {
  FusekiClient,
  type SparqlResult,
} from '../../../services/main/src/infrastructure/fuseki.ts';
import { COMMAND_MODULE_VERSION } from '../../../services/main/src/infrastructure/profile.ts';
import { profileRegistry } from '../../../packages/model/src/generated/profiles.ts';
import type { MainWorkDependencies } from '../../../services/main/src/routes/dependencies.ts';
import { productionExample } from './g-722-fixture.ts';
import { recoveryAccess } from '../../../services/main/tests/support/recovery-access.ts';
import { describe, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { str } from 'envalid';
import {
  assertClassifiedDefaults,
  checkProductionEnv,
  productionSpecs,
  type ProductionRole,
} from '../production-env.ts';
import { migrationRecords, repositoryRoot } from '../migrate.ts';
import { accountSchemaReady } from '../../../services/account/src/schema-ready.ts';
import { mainSchemaReady, assertSchemaReady } from '../../../services/main/src/schema-ready.ts';
import type { Pool } from 'pg';

describe('G-722 production configuration', () => {
  test('complete production input validates against every existing role spec', () => {
    expect(() =>
      checkProductionEnv(productionExample(), Object.keys(productionSpecs) as ProductionRole[]),
    ).not.toThrow();
  });
  test('every unsafe spec default or example has an explicit classification', () => {
    expect(() => assertClassifiedDefaults()).not.toThrow();
    expect(() =>
      assertClassifiedDefaults({
        future: { NEW_ORIGIN: str({ default: 'http://127.0.0.1:8000' }) },
      }),
    ).toThrow('Unclassified');
    expect(() =>
      assertClassifiedDefaults({ future: { NEW_SECRET: str({ example: '<generated>' }) } }),
    ).toThrow('Unclassified');
    expect(() =>
      assertClassifiedDefaults({ future: { NEW_SECRET: str({ default: 'password' }) } }),
    ).toThrow('Unclassified');
  });
  test('Fuseki capability format and independent title key are checked before startup', () => {
    const env = productionExample();
    expect(() =>
      checkProductionEnv({ ...env, FUSEKI_TITLE_ADMISSION_KEY: env.FUSEKI_COMMAND_TOKEN }),
    ).toThrow('independently');
    expect(() => checkProductionEnv({ ...env, FUSEKI_COMMAND_TOKEN: 'too-short' })).toThrow(
      '64-character',
    );
  });
  for (const [name, value] of [
    ['ACCOUNT_SMTP_HOST', '127.0.0.1'],
    ['ACCOUNT_SMTP_HOST', 'mailpit.internal'],
    ['ACCOUNT_SMTP_HOST', 'localhost.'],
    ['ACCOUNT_EMAIL_FROM', 'accounts@localhost'],
    ['MAIN_OPEN_LIBRARY_FIXTURE_ROOT', '/srv/fixtures'],
    ['MAIN_OBJECT_DIRECTORY', '.temp/objects'],
    ['ACCOUNT_SECRET', '<generated by task dev:prepare>'],
    ['MAIN_S3_SECRET_KEY', 'changeme'],
    ['ACCOUNT_DATABASE_URL', 'postgres://owner:password@postgres.internal/account'],
    ['ACCOUNT_BASE_URL', 'http://127.0.0.1:3004'],
    ['WEB_ORIGIN', 'http://[::1]:3000'],
    ['MAIN_RESOURCE', 'https://main.rezics.test'],
    ['MAIN_ORIGIN', 'http://127.1:3001'],
    ['ABOUT_SITE_URL', 'http://localhost:4321'],
  ])
    test(`refuses ${name} development value ${value}`, () => {
      expect(() =>
        checkProductionEnv(
          { ...productionExample(), [name!]: value },
          Object.keys(productionSpecs) as ProductionRole[],
        ),
      ).toThrow();
    });
  test('missing required fields and implicit SMTP development defaults fail', () => {
    const env = productionExample();
    delete env.ACCOUNT_SECRET;
    expect(() => checkProductionEnv(env)).toThrow('ACCOUNT_SECRET');
    const smtp = productionExample();
    delete smtp.ACCOUNT_SMTP_HOST;
    expect(() => checkProductionEnv(smtp)).toThrow('SMTP');
  });
  test('production Worker configs exist for all three Workers', () => {
    for (const app of ['web', 'accounts', 'about'] as const) {
      const config = JSON.parse(
        readFileSync(`${repositoryRoot}/apps/${app}/wrangler.jsonc`, 'utf8'),
      );
      expect(config.env.production.name).toBe(`rezics-${app}-production`);
      expect(
        Object.values(config.env.production.vars).every(
          (value) => typeof value === 'string' && /^<[A-Z_]+>$/.test(value),
        ),
      ).toBe(true);
      expect(() => checkProductionEnv(config.env.production.vars, [app])).toThrow();
      const configured = Object.fromEntries(
        Object.keys(config.env.production.vars).map((name) => [name, productionExample()[name]]),
      );
      expect(() =>
        checkProductionEnv(
          {
            ...configured,
            WEB_OAUTH_CLIENT_ID: productionExample().WEB_OAUTH_CLIENT_ID,
            ...(app === 'accounts'
              ? { ACCOUNT_TURNSTILE_SITE_KEY: productionExample().ACCOUNT_TURNSTILE_SITE_KEY }
              : {}),
          },
          [app],
        ),
      ).not.toThrow();
    }
  });
});

describe('G-722 release readiness', () => {
  const poolFor = (rows: unknown[] = []) =>
    ({ query: async () => ({ rows }) }) as unknown as Pick<Pool, 'query'>;
  for (const owner of ['access', 'relay', 'content', 'account'] as const) {
    test(`${owner} requires all release migration records and permits extra history`, async () => {
      const records = migrationRecords(repositoryRoot, owner);
      await expect(assertSchemaReady(poolFor(), owner)).rejects.toThrow('incomplete');
      await expect(assertSchemaReady(poolFor(records.slice(1)), owner)).rejects.toThrow(
        'incomplete',
      );
      await expect(
        assertSchemaReady(poolFor([...records, { name: 'future', version: 999 }]), owner),
      ).resolves.toBeUndefined();
    });
  }
  test('production cannot omit storage or Account migrations', async () => {
    await expect(mainSchemaReady({ NODE_ENV: 'production' })).rejects.toThrow(
      'ACCESS_DATABASE_URL',
    );
    await expect(accountSchemaReady(poolFor(), { NODE_ENV: 'production' })).rejects.toThrow(
      'incomplete',
    );
    await expect(
      accountSchemaReady(poolFor(migrationRecords(repositoryRoot, 'account')), {
        NODE_ENV: 'production',
      }),
    ).resolves.toBeUndefined();
  });
  test('a graph write ahead of the text projection does not flap API readiness', async () => {
    class AheadOfProjection extends FusekiClient {
      constructor() {
        super('http://localhost:1/rezics');
      }
      override async query(query: string): Promise<SparqlResult> {
        // Admission is open, while the newly advanced graph has no current index proof.
        return query.includes('ASK') ? { boolean: true } : { results: { bindings: [] } };
      }
      override async commandHealth() {
        return {
          moduleVersion: COMMAND_MODULE_VERSION,
          instanceId: '11111111-1111-4111-8111-111111111111',
          publicSearchWriteEpoch: '2',
          publicSearchWriteActive: false,
          profiles: Object.fromEntries(
            Object.entries(profileRegistry).map(([id, profile]) => [id, profile.sha256]),
          ),
        };
      }
    }
    const work = {
      environment: { lineage: { dataEpoch: 'epoch-a', routingEpoch: 'routing-a' } },
      access: recoveryAccess(),
    } as unknown as MainWorkDependencies;
    const app = healthRoutes(new AheadOfProjection(), work);
    const request = (path: string) => app.handle(new Request(`http://localhost${path}`));
    expect((await request('/health/search-ready')).status).toBe(503);
    expect(await (await request('/health/ready')).json()).toEqual({ status: 'ready' });
  });
  test('development does not introduce storage or schema probes', async () => {
    const pool = {
      query: async () => {
        throw new Error('unexpected probe');
      },
    } as unknown as Pick<Pool, 'query'>;
    await expect(
      mainSchemaReady({ NODE_ENV: 'development', ACCESS_DATABASE_URL: 'invalid' }),
    ).resolves.toBeUndefined();
    await expect(accountSchemaReady(pool, { NODE_ENV: 'development' })).resolves.toBeUndefined();
  });
});
