import { describe, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { str } from 'envalid';
import {
  assertClassifiedDefaults,
  checkProductionEnv,
  productionSpecs,
  type ProductionRole,
} from '../production-env.ts';
import { expectedSchemaHead, repositoryRoot } from '../migrate.ts';
import { accountSchemaReady } from '../../../services/account/src/schema-ready.ts';
import { mainSchemaReady, readSchemaHead } from '../../../services/main/src/schema-ready.ts';
import type { Pool } from 'pg';

/** Synthetic complete deployment input; no real credential or development fixture. */
export function productionExample(): Record<string, string> {
  const result: Record<string, string> = {};
  for (const spec of Object.values(productionSpecs))
    for (const [name, validator] of Object.entries(spec)) {
      if (validator.default !== undefined) result[name] = String(validator.default);
      else if (name.endsWith('_DATABASE_URL') || name === 'OWNER_RELOCATION_TARGET_URL')
        result[name] = 'postgres://owner:8d4cb67658b2d230@postgres.internal/owner';
      else if (/URL|ORIGIN|RESOURCE|ENDPOINT|ISSUER/.test(name))
        result[name] = 'https://service.rezics.com';
      else if (/PORT$/.test(name)) result[name] = '3001';
      else if (/DIRECTORY/.test(name)) result[name] = '/var/lib/rezics/objects';
      else if (/EPOCH/.test(name)) result[name] = '1';
      else result[name] = '8d4cb67658b2d230c437b8a97c2757e18d4cb67658b2d230c437b8a97c2757e1';
    }
  delete result.MAIN_OPEN_LIBRARY_FIXTURE_ROOT;
  result.ACCOUNT_SMTP_HOST = 'smtp.rezics.com';
  result.ACCOUNT_EMAIL_FROM = 'REZICS <accounts@rezics.com>';
  result.ACCOUNT_SMTP_REQUIRE_TLS = 'true';
  result.MAIN_ORIGIN = 'https://main.rezics.com';
  result.ACCOUNT_ORIGIN = 'https://accounts.rezics.com';
  result.ACCOUNT_SERVICE_ORIGIN = 'https://account.rezics.com';
  result.ACCOUNT_BASE_URL = 'https://accounts.rezics.com';
  result.WEB_ORIGIN = 'https://rezics.com';
  result.MAIN_RESOURCE = result.ACCOUNT_MAIN_RESOURCE = 'https://main.rezics.com';
  result.FUSEKI_TITLE_ADMISSION_KEY =
    '5db75dc8f93220c9a68776fc8b1f3c3c5db75dc8f93220c9a68776fc8b1f3c3c';
  return result;
}

describe('G-722 production configuration', () => {
  test('complete production input validates against every existing role spec', () => {
    expect(() =>
      checkProductionEnv(productionExample(), Object.keys(productionSpecs) as ProductionRole[]),
    ).not.toThrow();
  });
  test('every unsafe spec default or example has an explicit classification', () => {
    expect(() => assertClassifiedDefaults()).not.toThrow();
    expect(() =>
      assertClassifiedDefaults({
        future: { NEW_ORIGIN: str({ default: 'http://127.0.0.1:8000' }) },
      }),
    ).toThrow('Unclassified');
    expect(() =>
      assertClassifiedDefaults({ future: { NEW_SECRET: str({ example: '<generated>' }) } }),
    ).toThrow('Unclassified');
    expect(() =>
      assertClassifiedDefaults({ future: { NEW_SECRET: str({ default: 'password' }) } }),
    ).toThrow('Unclassified');
  });
  test('Fuseki capability format and independent title key are checked before startup', () => {
    const env = productionExample();
    expect(() =>
      checkProductionEnv({ ...env, FUSEKI_TITLE_ADMISSION_KEY: env.FUSEKI_COMMAND_TOKEN }),
    ).toThrow('independently');
    expect(() => checkProductionEnv({ ...env, FUSEKI_COMMAND_TOKEN: 'too-short' })).toThrow(
      '64-character',
    );
  });
  for (const [name, value] of [
    ['ACCOUNT_SMTP_HOST', '127.0.0.1'],
    ['ACCOUNT_SMTP_HOST', 'mailpit.internal'],
    ['ACCOUNT_SMTP_HOST', 'localhost.'],
    ['ACCOUNT_EMAIL_FROM', 'accounts@localhost'],
    ['MAIN_OPEN_LIBRARY_FIXTURE_ROOT', '/srv/fixtures'],
    ['MAIN_OBJECT_DIRECTORY', '.temp/objects'],
    ['ACCOUNT_SECRET', '<generated by task dev:prepare>'],
    ['MAIN_S3_SECRET_KEY', 'changeme'],
    ['ACCOUNT_DATABASE_URL', 'postgres://owner:password@postgres.internal/account'],
    ['ACCOUNT_BASE_URL', 'http://127.0.0.1:3004'],
    ['WEB_ORIGIN', 'http://[::1]:3000'],
    ['MAIN_RESOURCE', 'https://main.rezics.test'],
    ['MAIN_ORIGIN', 'http://127.1:3001'],
    ['ABOUT_SITE_URL', 'http://localhost:4321'],
  ])
    test(`refuses ${name} development value ${value}`, () => {
      expect(() =>
        checkProductionEnv(
          { ...productionExample(), [name!]: value },
          Object.keys(productionSpecs) as ProductionRole[],
        ),
      ).toThrow();
    });
  test('missing required fields and implicit SMTP development defaults fail', () => {
    const env = productionExample();
    delete env.ACCOUNT_SECRET;
    expect(() => checkProductionEnv(env)).toThrow('ACCOUNT_SECRET');
    const smtp = productionExample();
    delete smtp.ACCOUNT_SMTP_HOST;
    expect(() => checkProductionEnv(smtp)).toThrow('SMTP');
  });
  test('production Worker configs exist for all three Workers', () => {
    for (const app of ['web', 'accounts', 'about']) {
      const config = JSON.parse(
        readFileSync(`${repositoryRoot}/apps/${app}/wrangler.jsonc`, 'utf8'),
      );
      expect(config.env.production.name).toBe(`rezics-${app}-production`);
      if (app !== 'about')
        expect(() =>
          checkProductionEnv(
            {
              ...config.env.production.vars,
              WEB_OAUTH_CLIENT_ID: productionExample().WEB_OAUTH_CLIENT_ID,
            },
            [app],
          ),
        ).not.toThrow();
    }
  });
});

describe('G-722 release readiness', () => {
  const poolFor = (head?: string) =>
    ({ query: async () => ({ rows: head ? [{ head }] : [] }) }) as unknown as Pick<Pool, 'query'>;
  test('missing, stale and current schema heads', async () => {
    await expect(readSchemaHead(poolFor(), 'access')).rejects.toThrow('differs');
    await expect(readSchemaHead(poolFor('stale'), 'access')).rejects.toThrow('differs');
    const head = expectedSchemaHead(repositoryRoot, 'access');
    expect(await readSchemaHead(poolFor(head), 'access')).toBe(head);
  });
  test('production cannot omit storage or Account schema', async () => {
    await expect(mainSchemaReady({ NODE_ENV: 'production' })).rejects.toThrow(
      'ACCESS_DATABASE_URL',
    );
    await expect(accountSchemaReady(poolFor(), { NODE_ENV: 'production' })).rejects.toThrow(
      'differs',
    );
    const head = expectedSchemaHead(repositoryRoot, 'account');
    expect(await accountSchemaReady(poolFor(head), { NODE_ENV: 'production' })).toEqual({
      storage: 'ready',
      schemaHead: head,
    });
  });
});
