// The Light Novels Zone's own words. Packages bring their strings; the platform
// passes the interface locale in `zone.locale`, and any other locale reads English.

const en = {
  continueTitle: 'Continue your series',
  nextVolume: 'Next volume',
  more: 'More',
  progress: 'Your place in the series',
  volumes: 'Volumes',
  availability: 'Where to read it',
  about: 'About',
  coverageTitle: 'What this Zone covers',
  coverageBody: 'It lists the series and volumes recorded in the REZICS catalogue, and your own progress through them. It does not sell books, link to stores, show prices or promise that a volume is available in your language or where you live.',
  attribution: 'Where a Work also has visual novel records, they come from the VNDB database dump, used under the ODbL and DbCL. © VNDB contributors.',
  attributionLink: 'About VNDB',
  siblingTitle: 'Play it as a visual novel',
  siblingBody: 'The Visual Novels Zone shows the same Works with the same library state, and finds a release you can play in your language.',
  siblingLink: 'Open the Visual Novels Zone',
};

type Strings = typeof en;
type ZoneLocale = 'en' | 'zh-Hans' | 'zh-Hant' | 'ja' | 'ko' | 'de' | 'fr' | 'es';
const zoneLocales = ['en', 'zh-Hans', 'zh-Hant', 'ja', 'ko', 'de', 'fr', 'es'] as const satisfies readonly ZoneLocale[];

const translations: Record<ZoneLocale, Strings> = {
  en,
  'zh-Hans': {
    continueTitle: '继续读你的系列',
    nextVolume: '下一卷',
    more: '更多',
    progress: '你在系列中的进度',
    volumes: '各卷',
    availability: '在哪里阅读',
    about: '简介',
    coverageTitle: '本专区涵盖的范围',
    coverageBody: '这里列出 REZICS 目录中已记录的系列和各卷，以及你自己的阅读进度。本专区不出售图书，不链接商店，不显示价格，也不保证某一卷有你的语言版本或在你所在的地区可得。',
    attribution: '如果某部作品也有视觉小说记录，这些记录来自 VNDB 数据库转储，依据 ODbL 和 DbCL 使用。© VNDB 贡献者。',
    attributionLink: '关于 VNDB',
    siblingTitle: '当作视觉小说来玩',
    siblingBody: '视觉小说专区展示同样的作品，书架状态也相同，并能找到有你的语言、可以玩的发行版。',
    siblingLink: '打开视觉小说专区',
  },
  'zh-Hant': {
    continueTitle: '繼續讀你的系列',
    nextVolume: '下一卷',
    more: '更多',
    progress: '你在系列中的進度',
    volumes: '各卷',
    availability: '在哪裡閱讀',
    about: '簡介',
    coverageTitle: '本專區涵蓋的範圍',
    coverageBody: '這裡列出 REZICS 目錄中已記錄的系列與各卷，以及你自己的閱讀進度。本專區不販售書籍、不連結商店、不顯示價格，也不保證某一卷有你的語言版本或在你所在的地區可取得。',
    attribution: '若某部作品也有視覺小說紀錄，這些紀錄來自 VNDB 資料庫轉儲，依 ODbL 與 DbCL 使用。© VNDB 貢獻者。',
    attributionLink: '關於 VNDB',
    siblingTitle: '當作視覺小說來玩',
    siblingBody: '視覺小說專區顯示相同的作品，書架狀態也相同，並能找到有你的語言、可以玩的發行版。',
    siblingLink: '開啟視覺小說專區',
  },
  ja: {
    continueTitle: 'シリーズの続きを読む',
    nextVolume: '次の巻',
    more: 'もっと見る',
    progress: 'シリーズでの進み具合',
    volumes: '各巻',
    availability: '読める場所',
    about: '概要',
    coverageTitle: 'このゾーンが扱う範囲',
    coverageBody: 'REZICS のカタログに記録されたシリーズと各巻、そしてあなた自身の進み具合を一覧します。書籍の販売、ストアへのリンク、価格の表示、あなたの言語やお住まいの地域での入手可否の保証は行いません。',
    attribution: '作品にビジュアルノベルの記録もある場合、それは VNDB のデータベースダンプに由来し、ODbL と DbCL のもとで利用しています。© VNDB contributors。',
    attributionLink: 'VNDB について',
    siblingTitle: 'ビジュアルノベルとして遊ぶ',
    siblingBody: 'ビジュアルノベルゾーンでは同じ作品が同じライブラリ状態で表示され、あなたの言語で遊べるリリースを探せます。',
    siblingLink: 'ビジュアルノベルゾーンを開く',
  },
  ko: {
    continueTitle: '시리즈 이어 읽기',
    nextVolume: '다음 권',
    more: '더 보기',
    progress: '시리즈에서 내 진행 상황',
    volumes: '각 권',
    availability: '읽을 수 있는 곳',
    about: '소개',
    coverageTitle: '이 Zone이 다루는 범위',
    coverageBody: 'REZICS 카탈로그에 기록된 시리즈와 각 권, 그리고 내 진행 상황을 나열합니다. 책을 판매하거나 스토어로 연결하거나 가격을 보여 주지 않으며, 어떤 권을 내 언어나 거주 지역에서 구할 수 있다고 보장하지도 않습니다.',
    attribution: '작품에 비주얼 노벨 기록도 있는 경우, 그 기록은 VNDB 데이터베이스 덤프에서 가져왔으며 ODbL과 DbCL에 따라 사용합니다. © VNDB contributors.',
    attributionLink: 'VNDB 소개',
    siblingTitle: '비주얼 노벨로 플레이하기',
    siblingBody: '비주얼 노벨 Zone은 같은 작품을 같은 라이브러리 상태로 보여 주고, 내 언어로 플레이할 수 있는 릴리스를 찾아 줍니다.',
    siblingLink: '비주얼 노벨 Zone 열기',
  },
  de: {
    continueTitle: 'Deine Serie fortsetzen',
    nextVolume: 'Nächster Band',
    more: 'Mehr',
    progress: 'Dein Stand in der Serie',
    volumes: 'Bände',
    availability: 'Wo du es lesen kannst',
    about: 'Über das Werk',
    coverageTitle: 'Was diese Zone abdeckt',
    coverageBody: 'Sie listet die Serien und Bände, die im REZICS-Katalog erfasst sind, und deinen eigenen Fortschritt darin. Sie verkauft keine Bücher, verlinkt keine Shops, zeigt keine Preise und verspricht nicht, dass ein Band in deiner Sprache oder dort erhältlich ist, wo du wohnst.',
    attribution: 'Hat ein Werk auch Visual-Novel-Einträge, stammen sie aus dem VNDB-Datenbank-Dump und werden unter ODbL und DbCL genutzt. © VNDB contributors.',
    attributionLink: 'Über VNDB',
    siblingTitle: 'Als Visual Novel spielen',
    siblingBody: 'Die Visual-Novels-Zone zeigt dieselben Werke mit demselben Bibliotheksstatus und findet eine Veröffentlichung, die du in deiner Sprache spielen kannst.',
    siblingLink: 'Visual-Novels-Zone öffnen',
  },
  fr: {
    continueTitle: 'Poursuivre votre série',
    nextVolume: 'Tome suivant',
    more: 'Plus',
    progress: 'Votre avancement dans la série',
    volumes: 'Tomes',
    availability: 'Où le lire',
    about: 'À propos',
    coverageTitle: 'Ce que couvre cette Zone',
    coverageBody: 'Elle liste les séries et les tomes enregistrés dans le catalogue REZICS, ainsi que votre propre avancement. Elle ne vend pas de livres, ne renvoie pas vers des boutiques, n’affiche pas de prix et ne promet pas qu’un tome soit disponible dans votre langue ou là où vous vivez.',
    attribution: 'Lorsqu’une œuvre a aussi des fiches de visual novel, elles proviennent de l’export de la base VNDB, utilisé sous ODbL et DbCL. © VNDB contributors.',
    attributionLink: 'À propos de VNDB',
    siblingTitle: 'À jouer comme un visual novel',
    siblingBody: 'La Zone Visual Novels montre les mêmes œuvres avec le même état de bibliothèque et trouve une édition jouable dans votre langue.',
    siblingLink: 'Ouvrir la Zone Visual Novels',
  },
  es: {
    continueTitle: 'Continúa tu serie',
    nextVolume: 'Siguiente volumen',
    more: 'Ver más',
    progress: 'Tu progreso en la serie',
    volumes: 'Volúmenes',
    availability: 'Dónde leerlo',
    about: 'Acerca de',
    coverageTitle: 'Qué cubre esta Zone',
    coverageBody: 'Lista las series y los volúmenes registrados en el catálogo de REZICS y tu propio progreso en ellos. No vende libros, no enlaza a tiendas, no muestra precios y no promete que un volumen esté disponible en tu idioma ni donde vives.',
    attribution: 'Cuando una obra también tiene registros de novela visual, proceden del volcado de la base de datos de VNDB, usado bajo ODbL y DbCL. © VNDB contributors.',
    attributionLink: 'Acerca de VNDB',
    siblingTitle: 'Juégalo como novela visual',
    siblingBody: 'La Zone de Novelas visuales muestra las mismas obras con el mismo estado de biblioteca y encuentra una edición que puedes jugar en tu idioma.',
    siblingLink: 'Abrir la Zone de Novelas visuales',
  },
};

export const localeStrings = translations;

export function strings(locale: string): Strings {
  return (zoneLocales as readonly string[]).includes(locale) ? translations[locale as ZoneLocale] : en;
}
