// The Fiction Zone's own words. Packages bring their strings; the platform
// passes the interface locale in `zone.locale`, and any other locale reads English.

const en = {
  tagline: 'Web serials, light novels and originals, picked in public by the Fiction editors.',
  official: 'Official REZICS Zone',
  podium: 'Top of the chart',
  more: 'Full chart',
  moreWorks: 'All stories',
  footerTitle: 'Fiction on REZICS',
  footerNote: 'Every pick in this Zone is a public decision. Follow the stamp on any work to see why it is here.',
  decisions: 'Decision log',
  about: 'About and rules',
  works: 'Every work',
  reads: 'Ranked by reads',
  finishedChapters: 'Ranked by finished chapters',
  ongoing: 'Ongoing',
  completed: 'Completed',
  hiatus: 'On hiatus',
  chapters: (count: string) => `${count} chapters`,
  words: (count: string) => `${count} words`,
  latestChapter: 'Latest chapter',
  day: 'Today', week: 'This week', month: 'This month',
};

type Strings = typeof en;
type ZoneLocale = 'en' | 'zh-Hans' | 'zh-Hant' | 'ja' | 'ko' | 'de' | 'fr' | 'es';
const zoneLocales = ['en', 'zh-Hans', 'zh-Hant', 'ja', 'ko', 'de', 'fr', 'es'] as const satisfies readonly ZoneLocale[];

const translations: Record<ZoneLocale, Strings> = {
  en,
  'zh-Hans': {
    tagline: '网络连载、轻小说与原创作品，由小说编辑部公开甄选。',
    official: 'REZICS 官方专区',
    podium: '榜单前三',
    more: '完整榜单',
    moreWorks: '全部作品',
    footerTitle: 'REZICS 小说',
    footerNote: '本专区的每一部推荐都来自一项公开决定。点开作品旁的印章，就能看到它为什么在这里。',
    decisions: '决定记录',
    about: '关于与规则',
    works: '全部作品',
    reads: '按阅读次数排名',
    finishedChapters: '按读完章节次数排名',
    ongoing: '连载中',
    completed: '已完结',
    hiatus: '暂停更新',
    chapters: (count: string) => `${count} 章`,
    words: (count: string) => `${count} 词`,
    latestChapter: '最新章节',
    day: '日榜', week: '周榜', month: '月榜',
  },
  'zh-Hant': {
    tagline: '網路連載、輕小說與原創作品，由小說編輯部公開甄選。',
    official: 'REZICS 官方 Zone',
    podium: '榜單前三',
    more: '完整榜單',
    footerTitle: 'REZICS 小說',
    footerNote: '這個 Zone 的每項精選都是公開決策的結果。點開作品旁的印章，就能了解它為何入選。',
    decisions: '決策紀錄',
    about: '關於與規則',
    works: '全部作品',
    moreWorks: '全部故事',
    reads: '依閱讀次數排名', finishedChapters: '依讀完章節數排名',
    ongoing: '連載中', completed: '已完結', hiatus: '暫停更新',
    chapters: (count: string) => `${count} 章`, words: (count: string) => `${count} 字`,
    latestChapter: '最新章節',
    day: '日榜', week: '週榜', month: '月榜',
  },
  ko: {
    tagline: '웹 연재물, 라이트 노벨, 오리지널 작품을 소설 편집진이 공개적으로 선정합니다.',
    official: 'REZICS 공식 Zone',
    podium: '순위 상위 작품',
    more: '전체 순위',
    footerTitle: 'REZICS 소설',
    footerNote: '이 Zone의 모든 추천 작품은 공개된 결정에 따라 선정되었습니다. 작품 옆의 도장을 누르면 선정 이유를 볼 수 있어요.',
    decisions: '결정 내역',
    about: '소개와 규칙',
    works: '모든 작품',
    moreWorks: '전체 이야기',
    reads: '조회 수 순위', finishedChapters: '완독 챕터 순위',
    ongoing: '연재 중', completed: '완결', hiatus: '휴재 중',
    chapters: (count: string) => `${count}화`, words: (count: string) => `단어 ${count}개`,
    latestChapter: '최신 회차',
    day: '오늘', week: '이번 주', month: '이번 달',
  },
  de: {
    tagline: 'Die Redaktion für Geschichten wählt Webserien, Light Novels und Originalwerke öffentlich aus.',
    official: 'Offizielle REZICS Zone',
    podium: 'Die Spitzenplätze der Rangliste',
    more: 'Gesamte Rangliste',
    footerTitle: 'Geschichten auf REZICS',
    footerNote: 'Jede Empfehlung in dieser Zone beruht auf einer öffentlichen Entscheidung. Öffne den Stempel an einem Werk, um zu erfahren, warum es hier ist.',
    decisions: 'Entscheidungsprotokoll',
    about: 'Über die Zone und ihre Regeln',
    works: 'Alle Werke',
    moreWorks: 'Alle Geschichten',
    reads: 'Nach Aufrufen sortiert', finishedChapters: 'Nach gelesenen Kapiteln sortiert',
    ongoing: 'Laufend', completed: 'Abgeschlossen', hiatus: 'Pausiert',
    chapters: (count: string) => `${count} Kapitel`, words: (count: string) => `${count} Wörter`,
    latestChapter: 'Neuestes Kapitel',
    day: 'Heute', week: 'Diese Woche', month: 'Diesen Monat',
  },
  ja: {
    tagline: 'ウェブ連載やライトノベル、オリジナル作品を、小説編集チームが公開の場で選び抜きます。',
    official: 'REZICS 公式 Zone',
    podium: 'ランキング上位',
    more: 'ランキングをすべて見る',
    footerTitle: 'REZICSの小説',
    footerNote: 'この Zone のおすすめはすべて公開の決定によって選ばれています。作品の横のスタンプをたどると、選ばれた理由がわかります。',
    decisions: '決定ログ',
    about: '概要とルール',
    works: 'すべての作品',
    moreWorks: 'すべての物語',
    reads: '閲覧数順', finishedChapters: '読了章数順',
    ongoing: '連載中', completed: '完結', hiatus: '休載中',
    chapters: (count: string) => `${count}章`, words: (count: string) => `${count}語`,
    latestChapter: '最新話',
    day: '今日', week: '今週', month: '今月',
  },
  fr: {
    tagline: 'Séries en ligne, light novels et œuvres originales, sélectionnés publiquement par l’équipe éditoriale de Fiction.',
    official: 'Zone officielle REZICS',
    podium: 'Sur le podium',
    more: 'Tout le classement',
    footerTitle: 'Fiction sur REZICS',
    footerNote: 'Chaque sélection de cette Zone fait suite à une décision publique. Ouvrez le sceau d’une œuvre pour découvrir pourquoi elle est ici.',
    decisions: 'Journal des décisions',
    about: 'Présentation et règles',
    works: 'Toutes les œuvres',
    moreWorks: 'Toutes les histoires',
    reads: 'Par nombre de lectures', finishedChapters: 'Par chapitres terminés',
    ongoing: 'En cours', completed: 'Terminée', hiatus: 'En pause',
    chapters: (count: string) => `${count} chapitres`, words: (count: string) => `${count} mots`,
    latestChapter: 'Dernier chapitre',
    day: 'Aujourd’hui', week: 'Cette semaine', month: 'Ce mois-ci',
  },
  es: {
    tagline: 'Novelas por entregas, novelas ligeras y obras originales, seleccionadas públicamente por el equipo editorial de Ficción.',
    official: 'Zone oficial de REZICS',
    podium: 'En el podio',
    more: 'Ver la clasificación completa',
    footerTitle: 'Ficción en REZICS',
    footerNote: 'Cada selección de esta Zone responde a una decisión pública. Abre el sello de una obra para saber por qué está aquí.',
    decisions: 'Registro de decisiones',
    about: 'Información y normas',
    works: 'Todas las obras',
    moreWorks: 'Todas las historias',
    reads: 'Por número de lecturas', finishedChapters: 'Por capítulos terminados',
    ongoing: 'En curso', completed: 'Completada', hiatus: 'En pausa',
    chapters: (count: string) => `${count} capítulos`, words: (count: string) => `${count} palabras`,
    latestChapter: 'Último capítulo',
    day: 'Hoy', week: 'Esta semana', month: 'Este mes',
  },
};

export const localeStrings = translations;

export function strings(locale: string): Strings {
  return (zoneLocales as readonly string[]).includes(locale) ? translations[locale as ZoneLocale] : en;
}
