import type { Static } from 'typebox';
import { Value } from 'typebox/value';
import { facetRegistry, facetRegistryDigest } from '../../../../../packages/model/src/generated/facets.ts';
import { FACETS_READ_COST, facetDefinition, facetList } from './contract.ts';

// Facets are authored in model/definitions/facet-*.ts and generated by `task gen`; Main
// serves and admits them but never stores them: Filters reference Facets, data does not.

export type AdmittedFacet = Static<typeof facetDefinition>;

/** Every admitted Facet version, checked against the served contract when Main loads. */
const admittedFacets: readonly AdmittedFacet[] = Object.values(facetRegistry).map(facet => {
  if (!Value.Check(facetDefinition, facet)) throw new Error(`Generated Facet ${facet.id} breaks its contract`);
  return facet as AdmittedFacet;
});

const byRef = new Map(admittedFacets.map(facet => [facet.id, facet]));
const byName = new Map(admittedFacets.filter(facet => facet.current).map(facet => [facet.name, facet]));

/** A Facet by exact DefinitionRef, or a name read as its current version. */
export function resolveFacet(reference: string): AdmittedFacet | undefined {
  return byRef.get(reference) ?? byName.get(reference);
}

const list = { profile: 'facets-v1' as const, digest: facetRegistryDigest, facets: admittedFacets };
if (!Value.Check(facetList, list)) throw new Error('Generated Facet list breaks its contract');

/** The GET /v1/facets body: identical for every reader until the next deploy. */
export const facetListBody = JSON.stringify(list);
export const facetListTag = `"${facetRegistryDigest}"`;
if (Buffer.byteLength(facetListBody) > FACETS_READ_COST.maxBytes) throw new Error('Facet list exceeds its byte bound');
