import type { FeedViewerStateReader } from '../modules/feed/viewer-state.ts';
import type { ContentCore } from '../../../content/src/core.ts';
import type { ContentProtectionStore } from '../modules/protection/content-store.ts';
import type { ProtectionAdmissionSigner } from '../modules/access/protection-admission.ts';
import type { ContentComments } from '../../../content/src/comments.ts';
import type { ContentProjectionCursor } from '../../../content/src/projection-cursor.ts';
import type { ContentPrivateSearchOwners } from '../modules/search-disclosure/content-socket.ts';
import type { AccessAdmissionRegistry } from '../modules/access/admission.ts';
import type { AgentProvisioning } from '../modules/agent/provision.ts';
import type { AgentVanityHandles } from '../modules/agent/vanity.ts';
import type { ReleaseRatingInventoryStore } from '../modules/access/rating-aggregate-inventory.ts';
import type { AccessOrganizationModeration } from '../modules/access/organization-moderation.ts';
import type { AccessGroups } from '../modules/access/groups.ts';
import type { AccessGrants } from '../modules/access/grants.ts';
import type { AccessMemberships } from '../modules/access/memberships.ts';
import type { AccessMembershipConsents } from '../modules/access/membership-consents.ts';
import type { AccessOrgRealmParticipation } from '../modules/access/org-realm-participation.ts';
import type { AccessManagedOrganizations } from '../modules/access/managed-organizations.ts';
import type { AccessPrivateMemberships } from '../modules/access/private-memberships.ts';
import type { AccessPrivateRecipients } from '../modules/access/private-recipients.ts';
import type { AccessRepresentations } from '../modules/access/representations.ts';
import type { AccessRepresentedMembershipAuthority }
  from '../modules/access/represented-membership-authority.ts';
import type { AccessEligibleOrgMemberSet } from '../modules/access/eligible-org-member-set.ts';
import type { AccessRoles } from '../modules/access/roles.ts';
import type { SourceIntakeStore } from '../modules/source/intake.ts';
import type { RecipeSourceConversionStore } from '../modules/recipe/source-conversion.ts';
import type { SourceAcquisitionServices } from '../modules/source/acquisition.ts';
import type { OpenLibraryConversionStore } from '../modules/source/open-library-conversion.ts';
import type { SourceChildCorrespondenceStore }
  from '../modules/source/record-child-correspondence.ts';
import type { GoMvsResolutionStore } from '../modules/package/go-mvs.ts';
import type { CargoResolutionStore } from '../modules/package/cargo-resolution.ts';
import type { NpmResolutionStore } from '../modules/package/npm-resolution.ts';
import type { NixResolutionStore } from '../modules/package/nix-resolution.ts';
import type { ModResolutionStore } from '../modules/package/mod-resolution.ts';
import type { PackageLockStore } from '../modules/package/lock.ts';
import type { PackageInstallationStore } from '../modules/package/install.ts';
import type { HubStore } from '../modules/hub/store.ts';
import type { GoProxyCaptureStore } from '../modules/package/go-proxy-capture.ts';
import type { GoSumdbTrustStore } from '../modules/package/go-sumdb-trust.ts';
import type { OpenLibrarySourceGraph } from '../modules/source/graph-projection.ts';
import type { SourceNativeWorkProposalStore } from '../modules/source/native-work-proposal.ts';
import type { SourceNativeWorkAdoptionStore } from '../modules/source/native-work-adoption.ts';
import type { SourceNativeWorkAttachmentStore } from '../modules/source/native-work-attachment.ts';
import type { SourceAuthorCreditStore } from '../modules/source/author-credit.ts';
import type { SourceFieldWithdrawalStore } from '../modules/source/withdrawal.ts';
import type { SourceFieldAttachmentStore } from '../modules/source/support-attach.ts';
import type { SourceFieldApplicationStore } from '../modules/source/field-application.ts';
import type { SourceNativeChildStore } from '../modules/source/child-native-support.ts';
import type { ProviderIdentityStore } from '../modules/source/provider-identity.ts';
import type { SourceScoreStore } from '../modules/source/score.ts';
import type { AccessActingContexts } from '../modules/access/contexts.ts';
import type { AccessSessionAgents } from '../modules/access/session-agent.ts';
import type { AccountAssertionVerifier } from '../modules/account/verify-assertion.ts';
import type { RelayHandoffPositions } from '../modules/outbox/relay-position.ts';
import type { BackpressureProfile } from '../operations/backpressure.ts';
import type { WorkActivationEnvironment } from '../modules/work/activate.ts';
import type { ReaderVariantPreferenceStore } from '../modules/work/native-variants.ts';
import type { RealmVariantRecommendationStore }
  from '../modules/work/realm-variant-recommendation.ts';
import type { VerificationStore } from '../modules/verification/store.ts';
import type { MediaAccessBatchReader } from '../modules/media/access-batch.ts';
import type { ErasureService } from '../modules/erasure/request.ts';
import type { RealmReplyStore } from '../modules/realm-reply/store.ts';
import type { OwnerOperations } from '../modules/owner/operations.ts';
import type { RankingGenerations } from '../modules/recommendation/ranking.ts';
import type { EventTemporalQueries } from '../modules/event/queries.ts';
import type { AccessVotes } from '../modules/vote/access.ts';
import type { AccessJudgments } from '../modules/judgment/access.ts';
import type { StructureProgressStore } from '../modules/progress/store.ts';
import type { ReadingSettingsStore } from '../modules/reading-settings/store.ts';
import type { StructureStageStore } from '../modules/structure/stage.ts';
import type { SemanticStageStore } from '../modules/semantic/staging.ts';
import type { ImmutableObjects } from '../infrastructure/immutable-objects.ts';
import type { ExportStore } from '../modules/export/store.ts';
import type { LicenseScopeHook } from '../modules/export/planner.ts';
import type { GovernanceStore } from '../modules/governance/store.ts';
import type { GovernanceRules } from '../modules/governance/rules.ts';
import type { ManagementReadStore } from '../modules/management-reads/read-store.ts';
import type { RealmSubmissionStore } from '../modules/realm-submission/store.ts';
import type { RealmSubmissionReads } from '../modules/realm-submission/reads.ts';
import type { AccessProposalExecutions } from '../modules/proposal/access.ts';
import type { NotificationStore } from '../modules/notification/store.ts';
import type { NotificationDispatcher } from '../modules/notification/dispatcher.ts';
import type { NotificationRealtimeHub } from '../modules/notification/realtime.ts';
import type { RightsStore } from '../modules/rights/store.ts';
import type { ConnectedAppStore } from '../modules/connected-apps/store.ts';
import type { ThemeStore } from '../modules/theme/store.ts';
import type { PrivateContextSelections } from '../modules/context/private-selection.ts';
import type { ProfilesAccess } from '../modules/profiles/access.ts';
import type { ReaderLibraryStatusStore } from '../modules/library/status.ts';
import type { ReaderLibraryRatings } from '../modules/library/ratings.ts';

export interface MainWorkDependencies {
  realmAdmin?: import('../modules/access/realm-management.ts').AccessRealmManagement;
  media?: import('../modules/media/commands.ts').MediaDependencies;
  follows?: import('../modules/follows/store.ts').FollowsStore;
  feed?: import('../modules/feed/store.ts').FeedStore;
  feedViewerState?: FeedViewerStateReader;
  maintainers?: import('../modules/work/maintainers.ts').WorkMaintainers;
  discovery?: import('../modules/discovery/store.ts').DiscoveryProjection;
  profiles?: ProfilesAccess;
  libraryStatus?: ReaderLibraryStatusStore;
  libraryRatings?: ReaderLibraryRatings;
  agentProvisioning?: AgentProvisioning;
  agentHandles?: AgentVanityHandles;
  agentProfiles?: import('../modules/agent/profile.ts').AgentPublicProfiles;
  governance?: { store: GovernanceStore; rules?: GovernanceRules };
  managementReads?: ManagementReadStore;
  realmSubmissions?: RealmSubmissionStore;
  realmSubmissionReads?: RealmSubmissionReads;
  proposalExecutions?: AccessProposalExecutions;
  notifications?: { store: NotificationStore; dispatcher?: NotificationDispatcher;
    realtime?: NotificationRealtimeHub; providerSecrets?: Readonly<Record<string, string>> };
  rights?: { store: RightsStore };
  themes?: ThemeStore;
  contextSelections?: PrivateContextSelections;
  environment: WorkActivationEnvironment;
  structureObjects?: ImmutableObjects;
  structureStages?: StructureStageStore;
  semanticStages?: SemanticStageStore;
  progress?: StructureProgressStore;
  readingSettings?: ReadingSettingsStore;
  account: Pick<AccountAssertionVerifier, 'verify'>;
  content?: Pick<ContentCore, 'owningResourceForRevision' | 'readExactBatch'>;
  editorialProtection?: ContentProtectionStore;
  protectionSigner?: ProtectionAdmissionSigner;
  contentAuthoring?: ContentCore;
  comments?: ContentComments;
  contentProjection?: { content: ContentCore; cursor: ContentProjectionCursor; consumer: string };
  contentPrivateSearch?: ContentPrivateSearchOwners;
  /** Read-only Main outbox relay checkpoint for the OPS06 broker lane. */
  relayPosition?: Pick<RelayHandoffPositions, 'read'>;
  /** Deployment-selected lane budgets; defaults to `operations-backpressure-v1`. */
  backpressureProfile?: BackpressureProfile;
  access: Pick<AccessAdmissionRegistry,
    'register' | 'claim' | 'recordGraphOutcome' | 'canReadWork' | 'canReadContributionDraft'
    | 'canReadStandingRating' | 'canLinkTranslation' | 'activePrincipalId'>
    & Partial<Pick<AccessAdmissionRegistry, 'canReadAsBaselineMember'>>
    & Partial<Pick<AccessAdmissionRegistry, 'verifyContentDraftProof'
      | 'publicRealmCount' | 'realmDirectory'
      | 'withWorkEditAuthority'
      | 'canReadSemanticResource'
      | 'canMarkOfficialZone'
      | 'readRatingAggregateInventory' | 'checkRatingAggregateFence'
      | 'readRatingContextPolicyWitness' | 'issueTitleAdmission'>>;
  releaseRatingInventory?: ReleaseRatingInventoryStore;
  actingContexts?: AccessActingContexts;
  actingContextDiscovery?: AccessActingContexts;
  sessionAgents?: AccessSessionAgents;
  groups?: AccessGroups;
  grants?: AccessGrants;
  memberships?: AccessMemberships;
  membershipConsents?: AccessMembershipConsents;
  orgRealmParticipation?: AccessOrgRealmParticipation;
  organizationModeration?: AccessOrganizationModeration;
  managedOrganizations?: AccessManagedOrganizations;
  privateMemberships?: AccessPrivateMemberships;
  privateRecipients?: AccessPrivateRecipients;
  representations?: AccessRepresentations;
  representedMembershipAuthority?: AccessRepresentedMembershipAuthority;
  eligibleOrgMemberSet?: AccessEligibleOrgMemberSet;
  roles?: AccessRoles;
  sourceIntake?: SourceIntakeStore;
  recipeSourceConversions?: RecipeSourceConversionStore;
  sourceAcquisitions?: SourceAcquisitionServices;
  sourceConversions?: OpenLibraryConversionStore;
  sourceCorrespondences?: SourceChildCorrespondenceStore;
  packageResolutions?: GoMvsResolutionStore;
  packageCargoResolutions?: CargoResolutionStore;
  packageNpmResolutions?: NpmResolutionStore;
  packageNixResolutions?: NixResolutionStore;
  packageModResolutions?: ModResolutionStore;
  packageLocks?: PackageLockStore;
  packageInstallations?: PackageInstallationStore;
  hub?: HubStore;
  connectedApps?: ConnectedAppStore;
  packageCaptures?: GoProxyCaptureStore;
  packageVerifications?: GoSumdbTrustStore;
  sourceGraph?: OpenLibrarySourceGraph;
  sourceProposals?: SourceNativeWorkProposalStore;
  sourceAdoptions?: SourceNativeWorkAdoptionStore;
  sourceAttachments?: SourceNativeWorkAttachmentStore;
  sourceAuthorCredits?: SourceAuthorCreditStore;
  sourceFieldWithdrawals?: SourceFieldWithdrawalStore;
  sourceFieldAttachments?: SourceFieldAttachmentStore;
  sourceFieldApplications?: SourceFieldApplicationStore;
  sourceNativeChildren?: SourceNativeChildStore;
  sourceProviderIdentity?: ProviderIdentityStore;
  sourceScores?: SourceScoreStore;
  openLibraryFetch?: typeof fetch;
  readerPreferences?: ReaderVariantPreferenceStore;
  realmRecommendations?: RealmVariantRecommendationStore;
  verification?: VerificationStore;
  /** Current Access authority for bounded resource-summary batches. */
  mediaAccess?: Pick<MediaAccessBatchReader, 'canReadWorks' | 'canReadSemantics' | 'canReadPrivateContexts'>;
  /** Relay erasure journal and Content owner; absent means erasure is unavailable. */
  erasures?: ErasureService;
  realmReplies?: RealmReplyStore;
  ownerOperations?: OwnerOperations;
  recommendations?: RankingGenerations;
  eventQueries?: EventTemporalQueries;
  votes?: AccessVotes;
  judgments?: AccessJudgments;
  exports?: ExportStore;
  exportVerification?: Pick<VerificationStore, 'readEvidence'>;
  exportVerificationPrivate?: Pick<VerificationStore, 'readEvidenceFor'>;
  exportRights?: LicenseScopeHook;
}
