// The Visual Novels Zone's own words. Packages bring their strings; the platform
// passes the interface locale in `zone.locale`, and any other locale reads English.

const en = {
  filterLabel: 'Find a playable release',
  language: 'Language',
  anyLanguage: 'Any language',
  platform: 'Platform',
  anyPlatform: 'Any platform',
  completeness: 'Completeness',
  anyCompleteness: 'Any completeness',
  complete: 'Complete',
  partial: 'Partial',
  trial: 'Trial',
  unknown: 'Unknown',
  origin: 'Translation',
  anyOrigin: 'Official or fan translation',
  official: 'Official',
  unofficial: 'Fan translation',
  apply: 'Show matching novels',
  clear: 'Clear filters',
  summary: 'Visual novels with one release that meets every filter',
  noMatchTitle: 'No release meets every filter',
  noMatchBody: 'A visual novel is listed only when one release has the language, platform, completeness and translation you chose. A translated title alone does not count. Loosen a filter to see more.',
  keepLooking: 'Nothing in this stretch of the library matched. Show the next page to keep looking.',
  releaseComplete: 'complete',
  releasePartial: 'partial',
  releaseTrial: 'trial',
  releaseUnknown: 'completeness unknown',
  officialRelease: 'official release',
  fanTranslation: 'fan translation',
  fanTranslationBy: (names: string) => `fan translation by ${names}`,
  matchedRelease: 'Matched release',
  moreMatches: 'More releases match too.',
  untitled: 'Untitled',
  filterNote: 'Only releases recorded in the catalogue are matched. Release data comes from VNDB.',
  coverageTitle: 'What this Zone covers',
  coverageBody: 'It lists the visual novels and releases recorded in the REZICS catalogue. It does not sell games, link to stores, show prices or promise that a release is available where you live.',
  attribution: 'Visual novel records come from the VNDB database dump, used under the ODbL and DbCL. © VNDB contributors.',
  siblingTitle: 'Read it as a book',
  siblingBody: 'Many visual novels have light novels or books. The Light Novels Zone shows the same Works with the same library state.',
  siblingLink: 'Open the Light Novels Zone',
  availability: 'Availability',
  about: 'About',
};

type Strings = typeof en;
type ZoneLocale = 'en' | 'zh-Hans' | 'zh-Hant' | 'ja' | 'ko' | 'de' | 'fr' | 'es';
const zoneLocales = ['en', 'zh-Hans', 'zh-Hant', 'ja', 'ko', 'de', 'fr', 'es'] as const satisfies readonly ZoneLocale[];

const translations: Record<ZoneLocale, Strings> = {
  en,
  'zh-Hans': {
    filterLabel: '查找可玩的发行版',
    language: '语言',
    anyLanguage: '任何语言',
    platform: '平台',
    anyPlatform: '任何平台',
    completeness: '完整度',
    anyCompleteness: '任何完整度',
    complete: '完整',
    partial: '部分',
    trial: '试玩',
    unknown: '未知',
    origin: '翻译',
    anyOrigin: '官方或粉丝翻译',
    official: '官方',
    unofficial: '粉丝翻译',
    apply: '显示匹配的视觉小说',
    clear: '清除筛选',
    summary: '有一个发行版同时满足所有筛选条件的视觉小说',
    noMatchTitle: '没有发行版满足全部筛选条件',
    noMatchBody: '只有当某一个发行版同时具备你选择的语言、平台、完整度和翻译类型，视觉小说才会列出。只有翻译标题不算数。放宽一个条件可以看到更多。',
    keepLooking: '这一段资料库里没有匹配项。显示下一页继续查找。',
    releaseComplete: '完整',
    releasePartial: '部分',
    releaseTrial: '试玩',
    releaseUnknown: '完整度未知',
    officialRelease: '官方发行',
    fanTranslation: '粉丝翻译',
    fanTranslationBy: (names: string) => `${names} 制作的粉丝翻译`,
    matchedRelease: '匹配的发行版',
    moreMatches: '还有其他发行版也匹配。',
    untitled: '未命名',
    filterNote: '只匹配目录中已记录的发行版。发行版数据来自 VNDB。',
    coverageTitle: '本专区涵盖的范围',
    coverageBody: '这里列出 REZICS 目录中已记录的视觉小说和发行版。本专区不出售游戏，不链接商店，不显示价格，也不保证某个发行版在你所在的地区可用。',
    attribution: '视觉小说记录来自 VNDB 数据库转储，依据 ODbL 和 DbCL 使用。© VNDB 贡献者。',
    siblingTitle: '当作书来读',
    siblingBody: '许多视觉小说也有轻小说或图书。轻小说专区展示同样的作品，书架状态也相同。',
    siblingLink: '打开轻小说专区',
    availability: '可获得的版本',
    about: '简介',
  },
  'zh-Hant': {
    filterLabel: '尋找可玩的發行版',
    language: '語言',
    anyLanguage: '任何語言',
    platform: '平台',
    anyPlatform: '任何平台',
    completeness: '完整度',
    anyCompleteness: '任何完整度',
    complete: '完整',
    partial: '部分',
    trial: '試玩',
    unknown: '未知',
    origin: '翻譯',
    anyOrigin: '官方或粉絲翻譯',
    official: '官方',
    unofficial: '粉絲翻譯',
    apply: '顯示符合的視覺小說',
    clear: '清除篩選',
    summary: '有一個發行版同時符合所有篩選條件的視覺小說',
    noMatchTitle: '沒有發行版符合全部篩選條件',
    noMatchBody: '只有當某一個發行版同時具備你選擇的語言、平台、完整度與翻譯類型，視覺小說才會列出。只有翻譯標題不算數。放寬一項條件可以看到更多。',
    keepLooking: '這一段資料庫裡沒有符合的項目。顯示下一頁繼續尋找。',
    releaseComplete: '完整',
    releasePartial: '部分',
    releaseTrial: '試玩',
    releaseUnknown: '完整度未知',
    officialRelease: '官方發行',
    fanTranslation: '粉絲翻譯',
    fanTranslationBy: (names: string) => `${names} 製作的粉絲翻譯`,
    matchedRelease: '符合的發行版',
    moreMatches: '還有其他發行版也符合。',
    untitled: '未命名',
    filterNote: '只比對目錄中已記錄的發行版。發行版資料來自 VNDB。',
    coverageTitle: '本專區涵蓋的範圍',
    coverageBody: '這裡列出 REZICS 目錄中已記錄的視覺小說與發行版。本專區不販售遊戲、不連結商店、不顯示價格，也不保證某個發行版在你所在的地區可取得。',
    attribution: '視覺小說紀錄來自 VNDB 資料庫轉儲，依 ODbL 與 DbCL 使用。© VNDB 貢獻者。',
    siblingTitle: '當作書來讀',
    siblingBody: '許多視覺小說也有輕小說或書籍。輕小說專區顯示相同的作品，書架狀態也相同。',
    siblingLink: '開啟輕小說專區',
    availability: '可取得的版本',
    about: '簡介',
  },
  ja: {
    filterLabel: 'プレイできるリリースを探す',
    language: '言語',
    anyLanguage: 'すべての言語',
    platform: 'プラットフォーム',
    anyPlatform: 'すべてのプラットフォーム',
    completeness: '完全性',
    anyCompleteness: 'すべて',
    complete: '完全版',
    partial: '一部',
    trial: '体験版',
    unknown: '不明',
    origin: '翻訳',
    anyOrigin: '公式翻訳またはファン翻訳',
    official: '公式',
    unofficial: 'ファン翻訳',
    apply: '該当するノベルを表示',
    clear: '絞り込みを解除',
    summary: 'すべての条件を満たすリリースが 1 つあるビジュアルノベル',
    noMatchTitle: 'すべての条件を満たすリリースはありません',
    noMatchBody: '選んだ言語・プラットフォーム・完全性・翻訳の種類を 1 つのリリースがすべて満たす場合にだけ、ビジュアルノベルを表示します。翻訳されたタイトルがあるだけでは該当しません。条件を緩めてみてください。',
    keepLooking: 'ライブラリのこの範囲には該当がありませんでした。次のページで探し続けられます。',
    releaseComplete: '完全版',
    releasePartial: '一部',
    releaseTrial: '体験版',
    releaseUnknown: '完全性は不明',
    officialRelease: '公式リリース',
    fanTranslation: 'ファン翻訳',
    fanTranslationBy: (names: string) => `${names} によるファン翻訳`,
    matchedRelease: '該当したリリース',
    moreMatches: '他にも該当するリリースがあります。',
    untitled: '無題',
    filterNote: 'カタログに記録されたリリースだけを照合します。リリースのデータは VNDB によるものです。',
    coverageTitle: 'このゾーンが扱う範囲',
    coverageBody: 'REZICS のカタログに記録されたビジュアルノベルとリリースを一覧します。ゲームの販売、ストアへのリンク、価格の表示、お住まいの地域での入手可否の保証は行いません。',
    attribution: 'ビジュアルノベルの記録は VNDB のデータベースダンプに由来し、ODbL と DbCL のもとで利用しています。© VNDB contributors。',
    siblingTitle: '本として読む',
    siblingBody: '多くのビジュアルノベルにはライトノベルや書籍があります。ライトノベルゾーンでは同じ作品が同じライブラリ状態で表示されます。',
    siblingLink: 'ライトノベルゾーンを開く',
    availability: '入手できる版',
    about: '概要',
  },
  ko: {
    filterLabel: '플레이할 수 있는 릴리스 찾기',
    language: '언어',
    anyLanguage: '모든 언어',
    platform: '플랫폼',
    anyPlatform: '모든 플랫폼',
    completeness: '완성도',
    anyCompleteness: '모든 완성도',
    complete: '완전판',
    partial: '일부',
    trial: '체험판',
    unknown: '알 수 없음',
    origin: '번역',
    anyOrigin: '공식 또는 팬 번역',
    official: '공식',
    unofficial: '팬 번역',
    apply: '일치하는 노벨 보기',
    clear: '필터 지우기',
    summary: '모든 필터를 충족하는 릴리스가 하나 있는 비주얼 노벨',
    noMatchTitle: '모든 필터를 충족하는 릴리스가 없습니다',
    noMatchBody: '선택한 언어, 플랫폼, 완성도, 번역 종류를 하나의 릴리스가 모두 갖춘 경우에만 비주얼 노벨이 표시됩니다. 번역된 제목만으로는 해당되지 않습니다. 조건을 완화해 보세요.',
    keepLooking: '라이브러리의 이 구간에는 일치하는 항목이 없습니다. 다음 페이지에서 계속 찾아보세요.',
    releaseComplete: '완전판',
    releasePartial: '일부',
    releaseTrial: '체험판',
    releaseUnknown: '완성도 알 수 없음',
    officialRelease: '공식 릴리스',
    fanTranslation: '팬 번역',
    fanTranslationBy: (names: string) => `${names}의 팬 번역`,
    matchedRelease: '일치한 릴리스',
    moreMatches: '일치하는 릴리스가 더 있습니다.',
    untitled: '제목 없음',
    filterNote: '카탈로그에 기록된 릴리스만 비교합니다. 릴리스 데이터는 VNDB에서 가져옵니다.',
    coverageTitle: '이 Zone이 다루는 범위',
    coverageBody: 'REZICS 카탈로그에 기록된 비주얼 노벨과 릴리스를 나열합니다. 게임을 판매하거나 스토어로 연결하거나 가격을 보여 주지 않으며, 거주 지역에서 릴리스를 구할 수 있다고 보장하지도 않습니다.',
    attribution: '비주얼 노벨 기록은 VNDB 데이터베이스 덤프에서 가져왔으며 ODbL과 DbCL에 따라 사용합니다. © VNDB contributors.',
    siblingTitle: '책으로 읽기',
    siblingBody: '많은 비주얼 노벨에는 라이트 노벨이나 책이 있습니다. 라이트 노벨 Zone은 같은 작품을 같은 라이브러리 상태로 보여 줍니다.',
    siblingLink: '라이트 노벨 Zone 열기',
    availability: '구할 수 있는 판',
    about: '소개',
  },
  de: {
    filterLabel: 'Eine spielbare Veröffentlichung finden',
    language: 'Sprache',
    anyLanguage: 'Jede Sprache',
    platform: 'Plattform',
    anyPlatform: 'Jede Plattform',
    completeness: 'Vollständigkeit',
    anyCompleteness: 'Jede Vollständigkeit',
    complete: 'Vollständig',
    partial: 'Teilweise',
    trial: 'Demo',
    unknown: 'Unbekannt',
    origin: 'Übersetzung',
    anyOrigin: 'Offiziell oder Fanübersetzung',
    official: 'Offiziell',
    unofficial: 'Fanübersetzung',
    apply: 'Passende Novels anzeigen',
    clear: 'Filter zurücksetzen',
    summary: 'Visual Novels mit einer Veröffentlichung, die alle Filter erfüllt',
    noMatchTitle: 'Keine Veröffentlichung erfüllt alle Filter',
    noMatchBody: 'Eine Visual Novel erscheint nur, wenn eine einzige Veröffentlichung Sprache, Plattform, Vollständigkeit und Übersetzungsart erfüllt. Ein übersetzter Titel allein zählt nicht. Lockere einen Filter, um mehr zu sehen.',
    keepLooking: 'In diesem Abschnitt der Bibliothek gab es keinen Treffer. Zeige die nächste Seite, um weiterzusuchen.',
    releaseComplete: 'vollständig',
    releasePartial: 'teilweise',
    releaseTrial: 'Demo',
    releaseUnknown: 'Vollständigkeit unbekannt',
    officialRelease: 'offizielle Veröffentlichung',
    fanTranslation: 'Fanübersetzung',
    fanTranslationBy: (names: string) => `Fanübersetzung von ${names}`,
    matchedRelease: 'Passende Veröffentlichung',
    moreMatches: 'Weitere Veröffentlichungen passen ebenfalls.',
    untitled: 'Ohne Titel',
    filterNote: 'Verglichen werden nur Veröffentlichungen, die im Katalog erfasst sind. Die Daten stammen von VNDB.',
    coverageTitle: 'Was diese Zone abdeckt',
    coverageBody: 'Sie listet die Visual Novels und Veröffentlichungen, die im REZICS-Katalog erfasst sind. Sie verkauft keine Spiele, verlinkt keine Shops, zeigt keine Preise und verspricht nicht, dass eine Veröffentlichung dort erhältlich ist, wo du wohnst.',
    attribution: 'Die Visual-Novel-Einträge stammen aus dem VNDB-Datenbank-Dump und werden unter ODbL und DbCL genutzt. © VNDB contributors.',
    siblingTitle: 'Als Buch lesen',
    siblingBody: 'Zu vielen Visual Novels gibt es Light Novels oder Bücher. Die Light-Novels-Zone zeigt dieselben Werke mit demselben Bibliotheksstatus.',
    siblingLink: 'Light-Novels-Zone öffnen',
    availability: 'Verfügbarkeit',
    about: 'Über das Werk',
  },
  fr: {
    filterLabel: 'Trouver une édition jouable',
    language: 'Langue',
    anyLanguage: 'Toutes les langues',
    platform: 'Plateforme',
    anyPlatform: 'Toutes les plateformes',
    completeness: 'Complétude',
    anyCompleteness: 'Toute complétude',
    complete: 'Complète',
    partial: 'Partielle',
    trial: 'Démo',
    unknown: 'Inconnue',
    origin: 'Traduction',
    anyOrigin: 'Officielle ou traduction de fans',
    official: 'Officielle',
    unofficial: 'Traduction de fans',
    apply: 'Afficher les romans correspondants',
    clear: 'Effacer les filtres',
    summary: 'Visual novels dont une édition satisfait tous les filtres',
    noMatchTitle: 'Aucune édition ne satisfait tous les filtres',
    noMatchBody: 'Un visual novel n’apparaît que si une seule édition a la langue, la plateforme, la complétude et le type de traduction choisis. Un titre traduit ne suffit pas. Assouplissez un filtre pour en voir plus.',
    keepLooking: 'Aucun résultat dans cette portion de la bibliothèque. Affichez la page suivante pour continuer à chercher.',
    releaseComplete: 'complète',
    releasePartial: 'partielle',
    releaseTrial: 'démo',
    releaseUnknown: 'complétude inconnue',
    officialRelease: 'édition officielle',
    fanTranslation: 'traduction de fans',
    fanTranslationBy: (names: string) => `traduction de fans par ${names}`,
    matchedRelease: 'Édition correspondante',
    moreMatches: 'D’autres éditions correspondent aussi.',
    untitled: 'Sans titre',
    filterNote: 'Seules les éditions enregistrées dans le catalogue sont comparées. Leurs données viennent de VNDB.',
    coverageTitle: 'Ce que couvre cette Zone',
    coverageBody: 'Elle liste les visual novels et les éditions enregistrés dans le catalogue REZICS. Elle ne vend pas de jeux, ne renvoie pas vers des boutiques, n’affiche pas de prix et ne promet pas qu’une édition soit disponible là où vous vivez.',
    attribution: 'Les fiches de visual novels proviennent de l’export de la base VNDB, utilisé sous ODbL et DbCL. © VNDB contributors.',
    siblingTitle: 'À lire comme un livre',
    siblingBody: 'Beaucoup de visual novels ont des light novels ou des livres. La Zone Light Novels montre les mêmes œuvres avec le même état de bibliothèque.',
    siblingLink: 'Ouvrir la Zone Light Novels',
    availability: 'Disponibilité',
    about: 'À propos',
  },
  es: {
    filterLabel: 'Encontrar una edición jugable',
    language: 'Idioma',
    anyLanguage: 'Cualquier idioma',
    platform: 'Plataforma',
    anyPlatform: 'Cualquier plataforma',
    completeness: 'Completitud',
    anyCompleteness: 'Cualquier completitud',
    complete: 'Completa',
    partial: 'Parcial',
    trial: 'Demo',
    unknown: 'Desconocida',
    origin: 'Traducción',
    anyOrigin: 'Oficial o traducción de fans',
    official: 'Oficial',
    unofficial: 'Traducción de fans',
    apply: 'Mostrar novelas coincidentes',
    clear: 'Quitar filtros',
    summary: 'Novelas visuales con una edición que cumple todos los filtros',
    noMatchTitle: 'Ninguna edición cumple todos los filtros',
    noMatchBody: 'Una novela visual solo aparece cuando una única edición tiene el idioma, la plataforma, la completitud y el tipo de traducción elegidos. Un título traducido no basta. Relaja un filtro para ver más.',
    keepLooking: 'No hubo coincidencias en este tramo de la biblioteca. Muestra la página siguiente para seguir buscando.',
    releaseComplete: 'completa',
    releasePartial: 'parcial',
    releaseTrial: 'demo',
    releaseUnknown: 'completitud desconocida',
    officialRelease: 'edición oficial',
    fanTranslation: 'traducción de fans',
    fanTranslationBy: (names: string) => `traducción de fans de ${names}`,
    matchedRelease: 'Edición coincidente',
    moreMatches: 'Coinciden también otras ediciones.',
    untitled: 'Sin título',
    filterNote: 'Solo se comparan las ediciones registradas en el catálogo. Sus datos proceden de VNDB.',
    coverageTitle: 'Qué cubre esta Zone',
    coverageBody: 'Lista las novelas visuales y las ediciones registradas en el catálogo de REZICS. No vende juegos, no enlaza a tiendas, no muestra precios y no promete que una edición esté disponible donde vives.',
    attribution: 'Los registros de novelas visuales proceden del volcado de la base de datos de VNDB, usado bajo ODbL y DbCL. © VNDB contributors.',
    siblingTitle: 'Léela como libro',
    siblingBody: 'Muchas novelas visuales tienen novelas ligeras o libros. La Zone de Novelas ligeras muestra las mismas obras con el mismo estado de biblioteca.',
    siblingLink: 'Abrir la Zone de Novelas ligeras',
    availability: 'Disponibilidad',
    about: 'Acerca de',
  },
};

export const localeStrings = translations;

export function strings(locale: string): Strings {
  return (zoneLocales as readonly string[]).includes(locale) ? translations[locale as ZoneLocale] : en;
}
