// The Books Zone's own words. Packages bring their strings; the platform
// passes the interface locale in `zone.locale`, and any other locale reads English.

const en = {
  official: 'Official REZICS Zone',
  tagline: 'Public-domain classics and the editions worth reading, chosen in public by the Books editors.',
  coverStory: 'Cover story',
  inThisIssue: 'In this issue',
  byline: (author: string) => `by ${author}`,
  startReading: 'Start reading',
  untitled: 'Untitled',
  column: 'The column',
  previous: 'Previous',
  next: 'Next',
  more: 'More',
  spotlight: 'Author spotlight',
  readTheirBooks: 'See their books',
  colophon: 'Colophon',
  footerNote: 'Every book in this Zone is here by a public decision. Follow the stamp beside any title to read why.',
  works: 'Every book',
  decisions: 'Decision log',
  about: 'About and rules',
};

type Strings = typeof en;

const translations: Record<string, Strings> = {
  en,
  'zh-Hans': {
    official: 'REZICS 官方专区',
    tagline: '公版经典和值得读的版本，由图书编辑部公开甄选。',
    coverStory: '封面故事',
    inThisIssue: '本期目录',
    byline: (author: string) => `${author} 著`,
    startReading: '开始阅读',
    untitled: '未命名',
    column: '专栏',
    previous: '上一页',
    next: '下一页',
    more: '更多',
    spotlight: '作者聚焦',
    readTheirBooks: '看看作者的书',
    colophon: '版权页',
    footerNote: '本专区的每一本书都来自一项公开决定。点开书名旁的印章，就能读到它为什么在这里。',
    works: '全部图书',
    decisions: '决定记录',
    about: '关于与规则',
  },
  'zh-Hant': {
    official: 'REZICS 官方 Zone',
    tagline: '公版經典與值得閱讀的版本，由圖書編輯部公開甄選。',
    coverStory: '封面故事',
    inThisIssue: '本期目錄',
    byline: (author: string) => `${author} 著`,
    startReading: '開始閱讀',
    untitled: '未命名',
    column: '專欄',
    previous: '上一頁',
    next: '下一頁',
    more: '更多',
    spotlight: '作者聚焦',
    readTheirBooks: '看看作者的書',
    colophon: '版權頁',
    footerNote: '這個 Zone 裡的每本書都經公開決策選入。點開書名旁的印章，就能了解它入選的原因。',
    works: '全部書籍',
    decisions: '決策紀錄',
    about: '關於與規則',
  },
  ko: {
    official: 'REZICS 공식 Zone',
    tagline: '저작권이 만료된 고전과 읽어 볼 만한 판본을 도서 편집진이 공개적으로 선정합니다.',
    coverStory: '표지 특집',
    inThisIssue: '이번 호',
    byline: (author: string) => `${author} 지음`,
    startReading: '읽기 시작',
    untitled: '제목 없음',
    column: '칼럼',
    previous: '이전',
    next: '다음',
    more: '더 보기',
    spotlight: '작가 소개',
    readTheirBooks: '작가의 다른 책 보기',
    colophon: '판권 페이지',
    footerNote: '이 Zone에 있는 모든 책은 공개된 결정에 따라 선정되었습니다. 책 제목 옆의 도장을 누르면 선정 이유를 볼 수 있어요.',
    works: '모든 책',
    decisions: '결정 내역',
    about: '소개와 규칙',
  },
  de: {
    official: 'Offizielle REZICS Zone',
    tagline: 'Gemeinfreie Klassiker und lesenswerte Ausgaben, öffentlich ausgewählt von der Bücherredaktion.',
    coverStory: 'Titelgeschichte',
    inThisIssue: 'In dieser Ausgabe',
    byline: (author: string) => `von ${author}`,
    startReading: 'Jetzt lesen',
    untitled: 'Ohne Titel',
    column: 'Kolumne',
    previous: 'Zurück',
    next: 'Weiter',
    more: 'Mehr',
    spotlight: 'Im Porträt',
    readTheirBooks: 'Weitere Bücher ansehen',
    colophon: 'Impressum',
    footerNote: 'Jedes Buch in dieser Zone wurde aufgrund einer öffentlichen Entscheidung aufgenommen. Öffne den Stempel neben einem Titel, um zu erfahren, warum es hier ist.',
    works: 'Alle Bücher',
    decisions: 'Entscheidungsprotokoll',
    about: 'Über die Zone und ihre Regeln',
  },
  ja: {
    official: 'REZICS 公式 Zone',
    tagline: 'パブリックドメインの名作や、読む価値のある版を書籍編集チームが公開の場で選出。',
    coverStory: 'カバーストーリー',
    inThisIssue: '今号の内容',
    byline: (author: string) => `${author} 著`,
    startReading: '読み始める',
    untitled: 'タイトル未設定',
    column: 'コラム',
    previous: '前へ',
    next: '次へ',
    more: 'もっと見る',
    spotlight: '注目の著者',
    readTheirBooks: '著者の本を見る',
    colophon: '奥付',
    footerNote: 'この Zone の本はすべて公開の決定によって選ばれています。タイトル横のスタンプをたどると、選ばれた理由を読めます。',
    works: 'すべての本',
    decisions: '決定ログ',
    about: '概要とルール',
  },
};

export function strings(locale: string): Strings {
  return translations[locale] ?? en;
}
