// The Books Zone's own words. Packages bring their strings; the platform
// passes the interface locale in `zone.locale`, and any other locale reads English.

const en = {
  official: 'Official REZICS Zone',
  tagline: 'Public-domain classics and the editions worth reading, chosen in public by the Books editors.',
  coverStory: 'Cover story',
  inThisIssue: 'In this issue',
  byline: (author: string) => `by ${author}`,
  startReading: 'Start reading',
  untitled: 'Untitled',
  column: 'The column',
  previous: 'Previous',
  next: 'Next',
  more: 'More',
  spotlight: 'Author spotlight',
  readTheirBooks: 'See their books',
  colophon: 'Colophon',
  footerNote: 'Every book in this Zone is here by a public decision. Follow the stamp beside any title to read why.',
  works: 'Every book',
  decisions: 'Decision log',
  about: 'About and rules',
  reads: 'Ranked by reads',
  finishedChapters: 'Ranked by finished chapters',
  ongoing: 'Ongoing',
  completed: 'Completed',
  hiatus: 'On hiatus',
  chapters: (count: string) => `${count} chapters`,
  words: (count: string) => `${count} words`,
  latestChapter: 'Latest chapter',
  day: 'Today',
  week: 'This week',
  month: 'This month',
};

type Strings = typeof en;

const translations: Record<string, Partial<Strings>> = {
  en,
  'zh-Hans': {
    official: 'REZICS 官方专区',
    tagline: '公版经典和值得读的版本，由图书编辑部公开甄选。',
    coverStory: '封面故事',
    inThisIssue: '本期目录',
    byline: (author: string) => `${author} 著`,
    startReading: '开始阅读',
    untitled: '未命名',
    column: '专栏',
    previous: '上一页',
    next: '下一页',
    more: '更多',
    spotlight: '作者聚焦',
    readTheirBooks: '看看作者的书',
    colophon: '版权页',
    footerNote: '本专区的每一本书都来自一项公开决定。点开书名旁的印章，就能读到它为什么在这里。',
    works: '全部图书',
    decisions: '决定记录',
    about: '关于与规则',
    reads: '按阅读次数排名',
    finishedChapters: '按读完章节次数排名',
    ongoing: '连载中',
    completed: '已完结',
    hiatus: '暂停更新',
    chapters: (count: string) => `${count} 章`,
    words: (count: string) => `${count} 词`,
    latestChapter: '最新章节',
    day: '今日',
    week: '本周',
    month: '本月',
  },
  'zh-Hant': {
    official: 'REZICS 官方 Zone',
    tagline: '公版經典與值得閱讀的版本，由圖書編輯部公開甄選。',
    coverStory: '封面故事',
    inThisIssue: '本期目錄',
    byline: (author: string) => `${author} 著`,
    startReading: '開始閱讀',
    untitled: '未命名',
    column: '專欄',
    previous: '上一頁',
    next: '下一頁',
    more: '更多',
    spotlight: '作者聚焦',
    readTheirBooks: '看看作者的書',
    colophon: '版權頁',
    footerNote: '這個 Zone 裡的每本書都經公開決策選入。點開書名旁的印章，就能了解它入選的原因。',
    works: '全部書籍',
    decisions: '決策紀錄',
    about: '關於與規則',
    reads: '依閱讀次數排名',
    finishedChapters: '依讀完章節數排名',
    ongoing: '連載中', completed: '已完結', hiatus: '暫停更新',
    chapters: (count: string) => `${count} 章`, words: (count: string) => `${count} 字`,
    latestChapter: '最新章節', day: '今日', week: '本週', month: '本月',
  },
  ko: {
    official: 'REZICS 공식 Zone',
    tagline: '저작권이 만료된 고전과 읽어 볼 만한 판본을 도서 편집진이 공개적으로 선정합니다.',
    coverStory: '표지 특집',
    inThisIssue: '이번 호',
    byline: (author: string) => `${author} 지음`,
    startReading: '읽기 시작',
    untitled: '제목 없음',
    column: '칼럼',
    previous: '이전',
    next: '다음',
    more: '더 보기',
    spotlight: '작가 소개',
    readTheirBooks: '작가의 다른 책 보기',
    colophon: '판권 페이지',
    footerNote: '이 Zone에 있는 모든 책은 공개된 결정에 따라 선정되었습니다. 책 제목 옆의 도장을 누르면 선정 이유를 볼 수 있어요.',
    works: '모든 책',
    decisions: '결정 내역',
    about: '소개와 규칙',
    reads: '조회 수 순위',
    finishedChapters: '완독 챕터 순위',
    ongoing: '연재 중', completed: '완결', hiatus: '휴재 중',
    chapters: (count: string) => `${count}장`, words: (count: string) => `단어 ${count}개`,
    latestChapter: '최신 챕터', day: '오늘', week: '이번 주', month: '이번 달',
  },
  de: {
    official: 'Offizielle REZICS Zone',
    tagline: 'Gemeinfreie Klassiker und lesenswerte Ausgaben, öffentlich ausgewählt von der Bücherredaktion.',
    coverStory: 'Titelgeschichte',
    inThisIssue: 'In dieser Ausgabe',
    byline: (author: string) => `von ${author}`,
    startReading: 'Jetzt lesen',
    untitled: 'Ohne Titel',
    column: 'Kolumne',
    previous: 'Zurück',
    next: 'Weiter',
    more: 'Mehr',
    spotlight: 'Im Porträt',
    readTheirBooks: 'Weitere Bücher ansehen',
    colophon: 'Impressum',
    footerNote: 'Jedes Buch in dieser Zone wurde aufgrund einer öffentlichen Entscheidung aufgenommen. Öffne den Stempel neben einem Titel, um zu erfahren, warum es hier ist.',
    works: 'Alle Bücher',
    decisions: 'Entscheidungsprotokoll',
    about: 'Über die Zone und ihre Regeln',
    reads: 'Nach Aufrufen sortiert',
    finishedChapters: 'Nach gelesenen Kapiteln sortiert',
    ongoing: 'Laufend', completed: 'Abgeschlossen', hiatus: 'Pausiert',
    chapters: (count: string) => `${count} Kapitel`, words: (count: string) => `${count} Wörter`,
    latestChapter: 'Neuestes Kapitel', day: 'Heute', week: 'Diese Woche', month: 'Diesen Monat',
  },
  ja: {
    official: 'REZICS 公式 Zone',
    tagline: 'パブリックドメインの名作や、読む価値のある版を書籍編集チームが公開の場で選出。',
    coverStory: 'カバーストーリー',
    inThisIssue: '今号の内容',
    byline: (author: string) => `${author} 著`,
    startReading: '読み始める',
    untitled: 'タイトル未設定',
    column: 'コラム',
    previous: '前へ',
    next: '次へ',
    more: 'もっと見る',
    spotlight: '注目の著者',
    readTheirBooks: '著者の本を見る',
    colophon: '奥付',
    footerNote: 'この Zone の本はすべて公開の決定によって選ばれています。タイトル横のスタンプをたどると、選ばれた理由を読めます。',
    works: 'すべての本',
    decisions: '決定ログ',
    about: '概要とルール',
    reads: '閲覧数順',
    finishedChapters: '読了章数順',
    ongoing: '連載中', completed: '完結', hiatus: '休載中',
    chapters: (count: string) => `${count}章`, words: (count: string) => `${count}語`,
    latestChapter: '最新章', day: '今日', week: '今週', month: '今月',
  },
  fr: {
    official: 'Zone officielle REZICS',
    tagline: 'Des classiques du domaine public et des éditions qui valent la lecture, choisis publiquement par l’équipe éditoriale de la rubrique Livres.',
    coverStory: 'À la une',
    inThisIssue: 'Dans ce numéro',
    byline: (author: string) => `par ${author}`,
    startReading: 'Commencer à lire',
    untitled: 'Sans titre',
    column: 'La chronique',
    previous: 'Précédent',
    next: 'Suivant',
    more: 'Voir plus',
    spotlight: 'Portrait d’auteur',
    readTheirBooks: 'Découvrir ses livres',
    colophon: 'Mentions éditoriales',
    footerNote: 'Chaque livre de cette Zone a été retenu par décision publique. Ouvrez le sceau à côté d’un titre pour en connaître la raison.',
    works: 'Tous les livres',
    decisions: 'Journal des décisions',
    about: 'Présentation et règles',
    reads: 'Par nombre de lectures',
    finishedChapters: 'Par chapitres terminés',
    ongoing: 'En cours', completed: 'Terminé', hiatus: 'En pause',
    chapters: (count: string) => `${count} chapitres`, words: (count: string) => `${count} mots`,
    latestChapter: 'Dernier chapitre', day: 'Aujourd’hui', week: 'Cette semaine', month: 'Ce mois-ci',
  },
  es: {
    official: 'Zone oficial de REZICS',
    tagline: 'Clásicos de dominio público y ediciones que merece la pena leer, elegidos públicamente por el equipo editorial de Libros.',
    coverStory: 'Reportaje de portada',
    inThisIssue: 'En este número',
    byline: (author: string) => `de ${author}`,
    startReading: 'Empezar a leer',
    untitled: 'Sin título',
    column: 'La columna',
    previous: 'Anterior',
    next: 'Siguiente',
    more: 'Ver más',
    spotlight: 'Autor destacado',
    readTheirBooks: 'Ver sus libros',
    colophon: 'Colofón',
    footerNote: 'Cada libro de esta Zone está aquí por una decisión pública. Abre el sello junto a un título para saber por qué.',
    works: 'Todos los libros',
    decisions: 'Registro de decisiones',
    about: 'Información y normas',
    reads: 'Por número de lecturas',
    finishedChapters: 'Por capítulos terminados',
    ongoing: 'En curso', completed: 'Completado', hiatus: 'En pausa',
    chapters: (count: string) => `${count} capítulos`, words: (count: string) => `${count} palabras`,
    latestChapter: 'Último capítulo', day: 'Hoy', week: 'Esta semana', month: 'Este mes',
  },
};

export function strings(locale: string): Strings {
  return { ...en, ...translations[locale] };
}
