// The Mods Zone's own words. Packages bring their strings; the platform
// passes the interface locale in `zone.locale`, and a word a locale lacks reads English.

const en = {
  featured: 'Featured',
  by: (author: string) => `by ${author}`,
  untitled: 'Untitled',
  trending: 'Trending',
  intervals: { day: 'Today', week: 'This week', month: 'This month' },
  updated: (ago: string) => `Updated ${ago}`,
  collection: 'Collection',
  count: (count: number) => count === 1 ? '1 pick' : `${count} picks`,
  more: 'See all',
  environments: { client: 'Client', server: 'Server', 'client-and-server': 'Client and server' },
  rank: (rank: number) => `No. ${rank}`,
  compatibility: 'Runs on',
  chooseEnvironment: 'Choose a game version, loader and side to check a release',
  exactRelease: 'Compatible release', olderRelease: 'Older compatible release',
  release: 'Release', beta: 'Beta', alpha: 'Alpha', channelUnknown: 'Channel unknown',
  versionUnknown: 'Version unknown', dependenciesUnknown: 'Dependencies unknown',
  required: 'Requires', noRequired: 'No required mods', inspect: 'Inspect release',
};

type Strings = typeof en;

const translations: Record<string, Partial<Strings>> = {
  en,
  'zh-Hans': {
    featured: '精选',
    by: (author: string) => `作者 ${author}`,
    untitled: '未命名',
    trending: '热门趋势',
    intervals: { day: '今日', week: '本周', month: '本月' },
    updated: (ago: string) => `${ago}更新`,
    collection: '合集',
    count: (count: number) => `${count} 项`,
    more: '查看全部',
    environments: { client: '客户端', server: '服务端', 'client-and-server': '客户端和服务端' },
    rank: (rank: number) => `第 ${rank} 名`,
    compatibility: '适用于',
    chooseEnvironment: '选择游戏版本、加载器和运行端，查看兼容版本',
    exactRelease: '兼容版本', olderRelease: '较早的兼容版本',
    release: '正式版', beta: '测试版', alpha: '早期测试版', channelUnknown: '发布类型未知',
    versionUnknown: '版本号未知', dependenciesUnknown: '依赖信息未知',
    required: '必需', noRequired: '无必需模组', inspect: '查看版本',
  },
  'zh-Hant': {
    featured: '精選',
    by: (author: string) => `作者 ${author}`,
    untitled: '未命名',
    trending: '熱門',
    intervals: { day: '今日', week: '本週', month: '本月' },
    updated: (ago: string) => `更新於${ago}`,
    collection: '合集',
    count: (count: number) => `${count} 項`,
    more: '查看全部',
  },
  ko: {
    featured: '추천',
    by: (author: string) => `${author} 제작`,
    untitled: '제목 없음',
    trending: '인기 급상승',
    intervals: { day: '오늘', week: '이번 주', month: '이번 달' },
    updated: (ago: string) => `업데이트: ${ago}`,
    collection: '컬렉션',
    count: (count: number) => `추천 ${count}개`,
    more: '모두 보기',
  },
  de: {
    featured: 'Vorgestellt',
    by: (author: string) => `von ${author}`,
    untitled: 'Ohne Titel',
    trending: 'Im Trend',
    intervals: { day: 'Heute', week: 'Diese Woche', month: 'Diesen Monat' },
    updated: (ago: string) => `Zuletzt ${ago} aktualisiert`,
    collection: 'Sammlung',
    count: (count: number) => count === 1 ? '1 Empfehlung' : `${count} Empfehlungen`,
    more: 'Alle ansehen',
  },
  ja: {
    featured: '注目',
    by: (author: string) => `作者：${author}`,
    untitled: 'タイトル未設定',
    trending: '人気',
    intervals: { day: '今日', week: '今週', month: '今月' },
    updated: (ago: string) => `${ago}に更新`,
    collection: 'コレクション',
    count: (count: number) => `${count}件のおすすめ`,
    more: 'すべて見る',
  },
  fr: {
    featured: 'À la une',
    by: (author: string) => `par ${author}`,
    untitled: 'Sans titre',
    trending: 'Tendances',
    intervals: { day: 'Aujourd’hui', week: 'Cette semaine', month: 'Ce mois-ci' },
    updated: (ago: string) => `Mis à jour ${ago}`,
    collection: 'Collection',
    count: (count: number) => count === 1 ? '1 sélection' : `${count} sélections`,
    more: 'Voir plus',
  },
  es: {
    featured: 'Destacados',
    by: (author: string) => `por ${author}`,
    untitled: 'Sin título',
    trending: 'Tendencias',
    intervals: { day: 'Hoy', week: 'Esta semana', month: 'Este mes' },
    updated: (ago: string) => `Actualizado ${ago}`,
    collection: 'Colección',
    count: (count: number) => count === 1 ? '1 selección' : `${count} selecciones`,
    more: 'Ver más',
  },
};

export function strings(locale: string): Strings {
  return { ...en, ...translations[locale] };
}
