// The Mods Zone's own words. Packages bring their strings; the platform
// passes the interface locale in `zone.locale`, and a word a locale lacks reads English.

function pluralCount(locale: string, count: number, one: string, other: string): string {
  return new Intl.PluralRules(locale).select(count) === 'one' ? one : other;
}

const en = {
  featured: 'Featured',
  by: (author: string) => `by ${author}`,
  untitled: 'Untitled',
  trending: 'Trending',
  intervals: { day: 'Today', week: 'This week', month: 'This month' },
  updated: (ago: string) => `Updated ${ago}`,
  collection: 'Collection',
  count: (count: number) => pluralCount('en', count, `${count} pick`, `${count} picks`),
  more: 'See all',
  environments: { client: 'Client', server: 'Server', 'client-and-server': 'Client and server' },
  rank: (rank: number) => `No. ${rank}`,
  compatibility: 'Runs on',
  chooseEnvironment: 'Choose a game version, loader and side to check a release',
  exactRelease: 'Compatible release', olderRelease: 'Older compatible release',
  release: 'Release', beta: 'Beta', alpha: 'Alpha', channelUnknown: 'Channel unknown',
  versionUnknown: 'Version unknown', dependenciesUnknown: 'Dependencies unknown',
  required: 'Requires', noRequired: 'No required mods', inspect: 'Inspect release',
};

type Strings = typeof en;

const translations: Record<string, Partial<Strings>> = {
  en,
  'zh-Hans': {
    featured: '精选',
    by: (author: string) => `作者 ${author}`,
    untitled: '未命名',
    trending: '热门趋势',
    intervals: { day: '今日', week: '本周', month: '本月' },
    updated: (ago: string) => `${ago}更新`,
    collection: '合集',
    count: (count: number) => `${count} 项`,
    more: '查看全部',
    environments: { client: '客户端', server: '服务端', 'client-and-server': '客户端和服务端' },
    rank: (rank: number) => `第 ${rank} 名`,
    compatibility: '适用于',
    chooseEnvironment: '选择游戏版本、加载器和运行端，查看兼容版本',
    exactRelease: '兼容版本', olderRelease: '较早的兼容版本',
    release: '正式版', beta: '测试版', alpha: '早期测试版', channelUnknown: '发布类型未知',
    versionUnknown: '版本号未知', dependenciesUnknown: '依赖信息未知',
    required: '必需', noRequired: '无必需模组', inspect: '查看版本',
  },
  'zh-Hant': {
    featured: '精選',
    by: (author: string) => `作者 ${author}`,
    untitled: '未命名',
    trending: '熱門',
    intervals: { day: '今日', week: '本週', month: '本月' },
    updated: (ago: string) => `更新於${ago}`,
    collection: '合集',
    count: (count: number) => `${count} 項`,
    more: '查看全部',
    environments: { client: '用戶端', server: '伺服器端', 'client-and-server': '用戶端與伺服器端' },
    rank: (rank: number) => `第 ${rank} 名`,
    compatibility: '相容性',
    chooseEnvironment: '選擇遊戲版本、載入器及運行端，以確認模組版本相容性',
    exactRelease: '相容版本', olderRelease: '較舊的相容版本',
    release: '正式版', beta: 'Beta 版', alpha: 'Alpha 版', channelUnknown: '發布類型未知',
    versionUnknown: '版本未知', dependenciesUnknown: '相依項目未知',
    required: '需要', noRequired: '沒有必要模組', inspect: '查看版本',
  },
  ko: {
    featured: '추천',
    by: (author: string) => `${author} 제작`,
    untitled: '제목 없음',
    trending: '인기 급상승',
    intervals: { day: '오늘', week: '이번 주', month: '이번 달' },
    updated: (ago: string) => `업데이트: ${ago}`,
    collection: '컬렉션',
    count: (count: number) => `추천 ${count}개`,
    more: '모두 보기',
    environments: { client: '클라이언트', server: '서버', 'client-and-server': '클라이언트와 서버' },
    rank: (rank: number) => `제 ${rank}위`,
    compatibility: '호환성',
    chooseEnvironment: '릴리스 호환성을 확인하려면 게임 버전, 로더와 실행 환경을 선택하세요',
    exactRelease: '호환 버전', olderRelease: '이전 호환 버전',
    release: '정식 릴리스', beta: '베타', alpha: '알파', channelUnknown: '알 수 없는 채널',
    versionUnknown: '알 수 없는 버전', dependenciesUnknown: '알 수 없는 종속 항목',
    required: '필요', noRequired: '필수 모드 없음', inspect: '릴리스 확인',
  },
  de: {
    featured: 'Vorgestellt',
    by: (author: string) => `von ${author}`,
    untitled: 'Ohne Titel',
    trending: 'Im Trend',
    intervals: { day: 'Heute', week: 'Diese Woche', month: 'Diesen Monat' },
    updated: (ago: string) => `Zuletzt ${ago} aktualisiert`,
    collection: 'Sammlung',
    count: (count: number) => pluralCount('de', count, `${count} Empfehlung`, `${count} Empfehlungen`),
    more: 'Alle ansehen',
    environments: { client: 'Client', server: 'Server', 'client-and-server': 'Client und Server' },
    rank: (rank: number) => `Nr. ${rank}`,
    compatibility: 'Kompatibilität',
    chooseEnvironment: 'Wähle Spielversion, Loader und Seite, um die Kompatibilität einer Version zu prüfen',
    exactRelease: 'Kompatible Version', olderRelease: 'Ältere kompatible Version',
    release: 'Release', beta: 'Beta', alpha: 'Alpha', channelUnknown: 'Release-Kanal unbekannt',
    versionUnknown: 'Version unbekannt', dependenciesUnknown: 'Abhängigkeiten unbekannt',
    required: 'Benötigt', noRequired: 'Keine erforderlichen Mods', inspect: 'Release ansehen',
  },
  ja: {
    featured: '注目',
    by: (author: string) => `作者：${author}`,
    untitled: 'タイトル未設定',
    trending: '人気',
    intervals: { day: '今日', week: '今週', month: '今月' },
    updated: (ago: string) => `${ago}に更新`,
    collection: 'コレクション',
    count: (count: number) => `${count}件のおすすめ`,
    more: 'すべて見る',
    environments: { client: 'クライアント', server: 'サーバー', 'client-and-server': 'クライアントとサーバー' },
    rank: (rank: number) => `${rank}位`,
    compatibility: '互換性',
    chooseEnvironment: 'リリースの互換性を確認するには、ゲームのバージョン、ローダー、実行環境を選択してください',
    exactRelease: '対応リリース', olderRelease: '以前の対応リリース',
    release: '正式版', beta: 'ベータ版', alpha: 'アルファ版', channelUnknown: 'リリース区分不明',
    versionUnknown: 'バージョン不明', dependenciesUnknown: '依存関係不明',
    required: '必要', noRequired: '必須Modはありません', inspect: 'リリースを見る',
  },
  fr: {
    featured: 'À la une',
    by: (author: string) => `par ${author}`,
    untitled: 'Sans titre',
    trending: 'Tendances',
    intervals: { day: 'Aujourd’hui', week: 'Cette semaine', month: 'Ce mois-ci' },
    updated: (ago: string) => `Mis à jour ${ago}`,
    collection: 'Collection',
    count: (count: number) => pluralCount('fr', count, `${count} sélection`, `${count} sélections`),
    more: 'Voir plus',
    environments: { client: 'Client', server: 'Serveur', 'client-and-server': 'Client et serveur' },
    rank: (rank: number) => `Nº ${rank}`,
    compatibility: 'Compatibilité',
    chooseEnvironment: 'Choisissez une version du jeu, un loader et un côté pour vérifier un release',
    exactRelease: 'Version compatible', olderRelease: 'Ancienne version compatible',
    release: 'Version stable', beta: 'Bêta', alpha: 'Alpha', channelUnknown: 'Canal inconnu',
    versionUnknown: 'Version inconnue', dependenciesUnknown: 'Dépendances inconnues',
    required: 'Requis', noRequired: 'Aucun mod requis', inspect: 'Voir le release',
  },
  es: {
    featured: 'Destacados',
    by: (author: string) => `por ${author}`,
    untitled: 'Sin título',
    trending: 'Tendencias',
    intervals: { day: 'Hoy', week: 'Esta semana', month: 'Este mes' },
    updated: (ago: string) => `Actualizado ${ago}`,
    collection: 'Colección',
    count: (count: number) => pluralCount('es', count, `${count} selección`, `${count} selecciones`),
    more: 'Ver más',
    environments: { client: 'Cliente', server: 'Servidor', 'client-and-server': 'Cliente y servidor' },
    rank: (rank: number) => `N.º ${rank}`,
    compatibility: 'Compatibilidad',
    chooseEnvironment: 'Elige una versión del juego, un loader y el entorno para comprobar la compatibilidad',
    exactRelease: 'Versión compatible', olderRelease: 'Versión compatible anterior',
    release: 'Versión estable', beta: 'Beta', alpha: 'Alfa', channelUnknown: 'Canal desconocido',
    versionUnknown: 'Versión desconocida', dependenciesUnknown: 'Dependencias desconocidas',
    required: 'Requiere', noRequired: 'No requiere mods', inspect: 'Ver versión',
  },
};

export function strings(locale: string): Strings {
  return { ...en, ...translations[locale] };
}
