// The Mods Zone's own words. Packages bring their strings; the platform
// passes the interface locale in `zone.locale`, and any other locale reads English.

const en = {
  official: 'Official REZICS Zone',
  tagline: 'Game mods, load orders and setup guides that keep your saves safe.',
  featured: 'Featured',
  alsoFeatured: 'Also featured',
  get: 'Get',
  by: (author: string) => `by ${author}`,
  untitled: 'Untitled',
  trending: 'Trending',
  intervals: { day: 'Today', week: 'This week', month: 'This month' },
  updatedThisWeek: (count: number) => `${count} updated this week`,
  updated: (ago: string) => `Updated ${ago}`,
  status: { ongoing: 'Active', completed: 'Complete', hiatus: 'Paused' },
  collection: 'Collection',
  count: (count: number) => count === 1 ? '1 pick' : `${count} picks`,
  more: 'See all',
  footerTitle: 'Mods on REZICS',
  footerNote: 'Every pick here is a public decision by the Mods moderators. Follow the stamp on any card to see why it is here.',
  works: 'Every mod and guide',
  decisions: 'Decision log',
  about: 'About and rules',
};

type Strings = typeof en;

const translations: Record<string, Strings> = {
  en,
  'zh-Hans': {
    official: 'REZICS 官方专区',
    tagline: '游戏模组、加载顺序和不会弄坏存档的安装指南。',
    featured: '精选',
    alsoFeatured: '更多精选',
    get: '获取',
    by: (author: string) => `作者 ${author}`,
    untitled: '未命名',
    trending: '热门趋势',
    intervals: { day: '今日', week: '本周', month: '本月' },
    updatedThisWeek: (count: number) => `本周更新 ${count} 项`,
    updated: (ago: string) => `${ago}更新`,
    status: { ongoing: '持续更新', completed: '已完成', hiatus: '暂停更新' },
    collection: '合集',
    count: (count: number) => `${count} 项`,
    more: '查看全部',
    footerTitle: 'REZICS 模组',
    footerNote: '这里的每一项推荐都来自模组版主的一项公开决定。点开卡片上的印章，就能看到它为什么在这里。',
    works: '全部模组与指南',
    decisions: '决定记录',
    about: '关于与规则',
  },
  'zh-Hant': {
    official: 'REZICS 官方 Zone',
    tagline: '遊戲模組、載入順序和不會弄壞存檔的安裝指南。',
    featured: '精選',
    alsoFeatured: '更多精選',
    get: '取得',
    by: (author: string) => `作者 ${author}`,
    untitled: '未命名',
    trending: '熱門',
    intervals: { day: '今日', week: '本週', month: '本月' },
    updatedThisWeek: (count: number) => `本週更新 ${count} 項`,
    updated: (ago: string) => `更新於${ago}`,
    status: { ongoing: '持續更新', completed: '已完成', hiatus: '暫停更新' },
    collection: '合集',
    count: (count: number) => `${count} 項`,
    more: '查看全部',
    footerTitle: 'REZICS 模組',
    footerNote: '這裡的每項精選都是 Mods 版主公開決策的結果。點開卡片上的印章，就能了解它為何入選。',
    works: '全部模組與指南',
    decisions: '決策紀錄',
    about: '關於與規則',
  },
  ko: {
    official: 'REZICS 공식 Zone',
    tagline: '세이브 파일을 안전하게 지켜 주는 게임 모드, 로드 순서, 설정 가이드.',
    featured: '추천',
    alsoFeatured: '함께 추천',
    get: '다운로드',
    by: (author: string) => `${author} 제작`,
    untitled: '제목 없음',
    trending: '인기 급상승',
    intervals: { day: '오늘', week: '이번 주', month: '이번 달' },
    updatedThisWeek: (count: number) => `이번 주 업데이트 ${count}건`,
    updated: (ago: string) => `업데이트: ${ago}`,
    status: { ongoing: '진행 중', completed: '완료', hiatus: '중단' },
    collection: '컬렉션',
    count: (count: number) => `추천 ${count}개`,
    more: '모두 보기',
    footerTitle: 'REZICS 게임 모드',
    footerNote: '여기에 소개된 모든 작품은 게임 모드 커뮤니티 운영진이 공개적으로 내린 결정에 따라 선정되었습니다. 카드의 도장을 누르면 선정 이유를 볼 수 있어요.',
    works: '모든 모드와 가이드',
    decisions: '결정 내역',
    about: '소개와 규칙',
  },
  de: {
    official: 'Offizielle REZICS Zone',
    tagline: 'Spielmods, Ladereihenfolgen und Einrichtungsanleitungen, mit denen deine Spielstände sicher bleiben.',
    featured: 'Vorgestellt',
    alsoFeatured: 'Ebenfalls vorgestellt',
    get: 'Herunterladen',
    by: (author: string) => `von ${author}`,
    untitled: 'Ohne Titel',
    trending: 'Im Trend',
    intervals: { day: 'Heute', week: 'Diese Woche', month: 'Diesen Monat' },
    updatedThisWeek: (count: number) => `Diese Woche aktualisierte Werke: ${count}`,
    updated: (ago: string) => `Zuletzt ${ago} aktualisiert`,
    status: { ongoing: 'Aktiv', completed: 'Abgeschlossen', hiatus: 'Pausiert' },
    collection: 'Sammlung',
    count: (count: number) => count === 1 ? '1 Empfehlung' : `${count} Empfehlungen`,
    more: 'Alle ansehen',
    footerTitle: 'Mods auf REZICS',
    footerNote: 'Jede Empfehlung hier wurde vom Moderationsteam der Community für Spielmods öffentlich beschlossen. Öffne den Stempel auf einer Karte, um zu sehen, warum sie hier ist.',
    works: 'Alle Mods und Anleitungen',
    decisions: 'Entscheidungsprotokoll',
    about: 'Über die Zone und ihre Regeln',
  ja: {
    official: 'REZICS 公式 Zone',
    tagline: 'ゲームMOD、ロードオーダー、セーブデータを安全に保つ導入ガイド。',
    featured: '注目',
    alsoFeatured: 'こちらも注目',
    get: '入手する',
    by: (author: string) => `作者：${author}`,
    untitled: 'タイトル未設定',
    trending: '人気',
    intervals: { day: '今日', week: '今週', month: '今月' },
    updatedThisWeek: (count: number) => `今週更新：${count}件`,
    updated: (ago: string) => `${ago}に更新`,
    status: { ongoing: '更新中', completed: '完了', hiatus: '休止中' },
    collection: 'コレクション',
    count: (count: number) => `${count}件のおすすめ`,
    more: 'すべて見る',
    footerTitle: 'REZICSのMOD',
    footerNote: 'ここで紹介しているMODはすべて、MOD担当モデレーターによる公開決定で選ばれています。カードのスタンプをたどると、選ばれた理由がわかります。',
    works: 'すべてのMODとガイド',
    decisions: '決定ログ',
    about: '概要とルール',
  },
};

export function strings(locale: string): Strings {
  return translations[locale] ?? en;
}
