import type { ProfileDefinition } from '../compiler/ir.ts';

export const sourceFieldStatementProfile = {
  id: 'source-field-statement-v1',
  comments: [
    'Private source claim for one field occurrence of a verified general conversion.',
    'It keeps exact lexical form, datatype, language, precision, unit, rank and',
    'somevalue/novalue/unknown distinctions; it asserts no native fact or reuse right.',
  ],
  prefixes: [
    ['sh', 'http://www.w3.org/ns/shacl#'],
    ['rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'],
    ['xsd', 'http://www.w3.org/2001/XMLSchema#'],
    ['rv', 'https://rezics.com/vocab/'],
  ],
  layout: 'expanded',
  shapes: [
    { iri: 'https://rezics.com/definition/source-field-statement-v1/statement-shape',
      properties: [
        { path: 'rdf:type', hasValue: 'rv:SourceStatement' },
        { path: 'rv:sourceConversion', minCount: 1, maxCount: 1, nodeKind: 'sh:IRI',
          class: 'rv:SourceConversion' },
        { path: 'rv:sourceMappingRevision', minCount: 1, maxCount: 1, datatype: 'xsd:string',
          maxLength: 100, pattern: '^[a-z0-9]+(-[a-z0-9]+)*$' },
        { path: 'rv:sourceGrain', minCount: 1, maxCount: 1, datatype: 'xsd:string',
          maxLength: 64, pattern: '^[a-z0-9]+(-[a-z0-9]+)*$' },
        { path: 'rv:sourceField', minCount: 1, maxCount: 1, datatype: 'xsd:string',
          minLength: 1, maxLength: 200 },
        { path: 'rv:sourceOccurrence', minCount: 1, maxCount: 1, nodeKind: 'sh:IRI' },
        { path: 'rv:sourceOrdinal', minCount: 1, maxCount: 1, datatype: 'xsd:integer',
          minInclusive: 0, maxInclusive: 65535 },
        { path: 'rv:sourceStatementRole', minCount: 1, maxCount: 1, datatype: 'xsd:string',
          in: ['"main"', '"qualifier"', '"reference"'] },
        { path: 'rv:sourceQualifies', maxCount: 1, nodeKind: 'sh:IRI', class: 'rv:SourceStatement' },
        { path: 'rv:fieldDisposition', minCount: 1, maxCount: 1, datatype: 'xsd:string',
          in: ['"native"', '"structured-source-only"', '"lossy"', '"excluded"', '"unsupported"'] },
        { path: 'rv:dispositionReason', minCount: 1, maxCount: 1, datatype: 'xsd:string',
          minLength: 1, maxLength: 500 },
        { path: 'rv:sourceValueKind', minCount: 1, maxCount: 1, datatype: 'xsd:string',
          in: ['"value"', '"somevalue"', '"novalue"', '"null"', '"unknown"'] },
        { path: 'rv:sourceLexical', maxCount: 1, datatype: 'xsd:string', maxLength: 65536 },
        { path: 'rv:sourceDatatype', maxCount: 1, nodeKind: 'sh:IRI' },
        { path: 'rv:sourceLanguage', maxCount: 1, datatype: 'xsd:string',
          pattern: '^[A-Za-z]{2,8}(-[A-Za-z0-9]{1,8})*$' },
        { path: 'rv:sourceRank', maxCount: 1, datatype: 'xsd:string',
          in: ['"preferred"', '"normal"', '"deprecated"'] },
        { path: 'rv:sourceTimePrecision', maxCount: 1, datatype: 'xsd:integer',
          minInclusive: 0, maxInclusive: 14 },
        { path: 'rv:sourceCalendar', maxCount: 1, nodeKind: 'sh:IRI' },
        { path: 'rv:sourceQuantityUnit', maxCount: 1, nodeKind: 'sh:IRI' },
        { path: 'rv:sourceQuantityLower', maxCount: 1, datatype: 'xsd:string', maxLength: 200 },
        { path: 'rv:sourceQuantityUpper', maxCount: 1, datatype: 'xsd:string', maxLength: 200 },
        { path: 'rv:sourceStatisticKind', maxCount: 1, datatype: 'xsd:string',
          in: ['"score-average"', '"score-count"', '"score-distribution"', '"user-count"',
            '"popularity"', '"rank"'] },
        { path: 'rv:sourceByteDigest', minCount: 1, maxCount: 1, datatype: 'xsd:string',
          pattern: '^[0-9a-f]{64}$' },
      ] },
  ],
} as const satisfies ProfileDefinition;
