import {
  typeLocales,
  type TypeBrowseCategory,
  type TypeMetadata,
  type TypeRegistryDefinition,
} from '../compiler/type.ts';

type Label = string | readonly [one: string, other: string];
const labels = (
  ...values: [Label, Label, Label, Label, Label, Label, Label, Label]
): TypeMetadata['labels'] =>
  Object.fromEntries(
    typeLocales.map((locale, index) => {
      const value = values[index]!;
      return [
        locale,
        typeof value === 'string'
          ? { one: value, other: value }
          : { one: value[0], other: value[1] },
      ];
    }),
  ) as TypeMetadata['labels'];

const browse = (
  id: string,
  order: number,
  ...values: [string, string, string, string, string, string, string, string]
): TypeBrowseCategory => ({
  id,
  order,
  labels: Object.fromEntries(
    typeLocales.map((locale, index) => [locale, values[index]!]),
  ) as TypeBrowseCategory['labels'],
});

// Catalogue nouns and onboarding plurals, authored in all eight interface locales.
// Creation policy feeds Access's baseline gate; Access authorizes every operation.
export const typesV1 = {
  id: 'types-v1',
  defaults: { work: 'schema:CreativeWork', resource: 'rdfs:Resource', record: 'rv:Record' },
  types: {
    'schema:Book': {
      base: 'work',
      interest: 'books',
      primaryAction: 'read',
      creation: 'contributor',
      presentation: 'book',
      cover: 'portrait',
      priority: 5,
      labels: labels(
        ['Book', 'Books'],
        '書籍',
        '图书',
        '本',
        '책',
        ['Buch', 'Bücher'],
        ['Livre', 'Livres'],
        ['Libro', 'Libros'],
      ),
    },
    'schema:BookSeries': {
      base: 'work',
      interest: 'books',
      primaryAction: 'read',
      creation: 'contributor',
      presentation: 'book',
      cover: 'portrait',
      priority: 6,
      labels: labels(
        ['Book', 'Books'],
        '書籍',
        '图书',
        '本',
        '책',
        ['Buch', 'Bücher'],
        ['Livre', 'Livres'],
        ['Libro', 'Libros'],
      ),
    },
    'schema:DigitalDocument': {
      base: 'work',
      interest: null,
      primaryAction: 'read',
      creation: 'contributor',
      presentation: 'guide',
      cover: 'document',
      priority: 15,
      labels: labels(
        ['Guide', 'Guides'],
        '指南',
        '指南',
        'ガイド',
        '안내서',
        ['Anleitung', 'Anleitungen'],
        ['Guide', 'Guides'],
        ['Guía', 'Guías'],
      ),
    },
    'schema:Recipe': {
      base: 'work',
      interest: 'recipes',
      primaryAction: 'read',
      creation: 'contributor',
      presentation: 'recipe',
      cover: 'square',
      priority: 3,
      labels: labels(
        ['Recipe', 'Recipes'],
        '食譜',
        '菜谱',
        'レシピ',
        '레시피',
        ['Rezept', 'Rezepte'],
        ['Recette', 'Recettes'],
        ['Receta', 'Recetas'],
      ),
    },
    'schema:SoftwareApplication': {
      base: 'work',
      interest: 'software',
      primaryAction: 'install',
      creation: 'administrator',
      presentation: 'default',
      cover: 'square',
      priority: 7,
      labels: labels(
        'Software',
        '軟體',
        '软件',
        'ソフトウェア',
        '소프트웨어',
        'Software',
        ['Logiciel', 'Logiciels'],
        'Software',
      ),
    },
    'schema:SoftwareSourceCode': {
      base: 'work',
      interest: 'software',
      primaryAction: 'install',
      creation: 'administrator',
      presentation: 'default',
      cover: 'square',
      priority: 8,
      labels: labels(
        'Software',
        '軟體',
        '软件',
        'ソフトウェア',
        '소프트웨어',
        'Software',
        ['Logiciel', 'Logiciels'],
        'Software',
      ),
    },
    'schema:VideoGame': {
      base: 'work',
      interest: 'media',
      primaryAction: 'visit',
      creation: 'contributor',
      presentation: 'game',
      cover: 'landscape',
      priority: 4,
      labels: labels(
        ['Game', 'Games'],
        '遊戲',
        '游戏',
        'ゲーム',
        '게임',
        ['Spiel', 'Spiele'],
        ['Jeu', 'Jeux'],
        ['Juego', 'Juegos'],
      ),
    },
    'rv:ModPackage': {
      base: 'work',
      interest: 'software',
      primaryAction: 'install',
      creation: 'administrator',
      presentation: 'default',
      cover: 'square',
      priority: 0,
      labels: labels(
        ['Mod', 'Mods'],
        '模組',
        '模组',
        'MOD',
        '모드',
        ['Mod', 'Mods'],
        ['Mod', 'Mods'],
        ['Mod', 'Mods'],
      ),
    },
    'rv:SkillPackage': {
      base: 'work',
      interest: 'ai',
      primaryAction: 'install',
      creation: 'contributor',
      presentation: 'skill',
      cover: 'square',
      priority: 1,
      labels: labels(
        ['Skill', 'Skills'],
        '技能',
        '技能',
        'スキル',
        '스킬',
        ['Skill', 'Skills'],
        ['Compétence', 'Compétences'],
        ['Habilidad', 'Habilidades'],
      ),
    },
    'rv:PromptTemplate': {
      base: 'work',
      interest: 'ai',
      primaryAction: 'copy',
      creation: 'contributor',
      presentation: 'prompt',
      cover: 'document',
      priority: 2,
      labels: labels(
        ['Prompt', 'Prompts'],
        '提示詞',
        '提示词',
        'プロンプト',
        '프롬프트',
        ['Prompt', 'Prompts'],
        ['Prompt', 'Prompts'],
        ['Prompt', 'Prompts'],
      ),
    },
    'schema:Movie': {
      base: 'work',
      interest: 'media',
      primaryAction: 'watch',
      creation: 'contributor',
      presentation: 'media',
      cover: 'portrait',
      priority: 9,
      labels: labels(
        ['Film', 'Films'],
        '電影',
        '电影',
        '映画',
        '영화',
        ['Film', 'Filme'],
        ['Film', 'Films'],
        ['Película', 'Películas'],
      ),
    },
    'schema:TVSeries': {
      base: 'work',
      interest: 'media',
      primaryAction: 'watch',
      creation: 'contributor',
      presentation: 'media',
      cover: 'portrait',
      priority: 10,
      labels: labels(
        'TV series',
        '電視影集',
        '剧集',
        'テレビシリーズ',
        'TV 시리즈',
        ['Fernsehserie', 'Fernsehserien'],
        ['Série télévisée', 'Séries télévisées'],
        ['Serie de TV', 'Series de TV'],
      ),
    },
    'schema:VideoObject': {
      base: 'work',
      interest: 'media',
      primaryAction: 'watch',
      creation: 'contributor',
      presentation: 'media',
      cover: 'landscape',
      priority: 11,
      labels: labels(
        ['Video', 'Videos'],
        '影片',
        '视频',
        '動画',
        '동영상',
        ['Video', 'Videos'],
        ['Vidéo', 'Vidéos'],
        ['Vídeo', 'Vídeos'],
      ),
    },
    'schema:AudioObject': {
      base: 'work',
      interest: 'media',
      primaryAction: 'watch',
      creation: 'contributor',
      presentation: 'media',
      cover: 'square',
      priority: 14,
      labels: labels('Audio', '音訊', '音频', '音声', '오디오', 'Audio', 'Audio', 'Audio'),
    },
    'schema:MusicRecording': {
      base: 'work',
      interest: 'media',
      primaryAction: 'watch',
      creation: 'contributor',
      presentation: 'media',
      cover: 'square',
      priority: 13,
      labels: labels('Music', '音樂', '音乐', '音楽', '음악', 'Musik', 'Musique', 'Música'),
    },
    'schema:MusicAlbum': {
      base: 'work',
      interest: 'media',
      primaryAction: 'watch',
      creation: 'contributor',
      presentation: 'media',
      cover: 'square',
      priority: 12,
      labels: labels('Music', '音樂', '音乐', '音楽', '음악', 'Musik', 'Musique', 'Música'),
    },
    'schema:CreativeWork': {
      browse: browse(
        'works',
        0,
        'Works',
        '作品',
        '作品',
        '作品',
        '작품',
        'Werke',
        'Œuvres',
        'Obras',
      ),
      base: 'work',
      interest: null,
      primaryAction: 'read',
      creation: 'contributor',
      presentation: 'default',
      cover: 'document',
      priority: 100,
      labels: labels(
        ['Work', 'Works'],
        '作品',
        '作品',
        '作品',
        '작품',
        ['Werk', 'Werke'],
        ['Œuvre', 'Œuvres'],
        ['Obra', 'Obras'],
      ),
    },
    'rv:Realm': {
      base: 'resource',
      interest: null,
      primaryAction: 'visit',
      creation: 'contributor',
      presentation: 'default',
      cover: 'square',
      priority: 100,
      labels: labels(
        ['Community', 'Communities'],
        '社群',
        '社区',
        'コミュニティ',
        '커뮤니티',
        ['Gemeinschaft', 'Gemeinschaften'],
        ['Communauté', 'Communautés'],
        ['Comunidad', 'Comunidades'],
      ),
      browse: browse(
        'communities',
        1,
        'Communities',
        '社群',
        '社区',
        'コミュニティ',
        '커뮤니티',
        'Communitys',
        'Communautés',
        'Comunidades',
      ),
    },
    'rv:Zone': {
      base: 'resource',
      interest: null,
      primaryAction: 'visit',
      creation: 'contributor',
      presentation: 'default',
      cover: 'square',
      priority: 100,
      labels: labels(
        ['Site', 'Sites'],
        '網站',
        '网站',
        'サイト',
        '사이트',
        ['Website', 'Websites'],
        ['Site', 'Sites'],
        ['Sitio', 'Sitios'],
      ),
      browse: browse(
        'sites',
        2,
        'Sites',
        '網站',
        '网站',
        'サイト',
        '사이트',
        'Websites',
        'Sites',
        'Sitios',
      ),
    },
    'rv:Agent': {
      base: 'resource',
      interest: null,
      primaryAction: 'visit',
      creation: 'contributor',
      presentation: 'default',
      cover: 'square',
      priority: 100,
      labels: labels(
        ['Agent', 'Agents'],
        '行動主體',
        '行动主体',
        'エージェント',
        '에이전트',
        ['Akteur', 'Akteure'],
        ['Acteur', 'Acteurs'],
        ['Agente', 'Agentes'],
      ),
      browse: browse(
        'people',
        3,
        'People',
        '人物',
        '人物',
        '人物',
        '인물',
        'Personen',
        'Personnes',
        'Personas',
      ),
    },
    'rv:Collection': {
      base: 'resource',
      interest: null,
      primaryAction: 'visit',
      creation: 'contributor',
      presentation: 'default',
      cover: 'document',
      priority: 100,
      labels: labels(
        ['List', 'Lists'],
        '清單',
        '列表',
        'リスト',
        '목록',
        ['Liste', 'Listen'],
        ['Liste', 'Listes'],
        ['Lista', 'Listas'],
      ),
      browse: browse(
        'lists',
        4,
        'Lists',
        '清單',
        '列表',
        'リスト',
        '목록',
        'Listen',
        'Listes',
        'Listas',
      ),
    },
    'skos:Concept': {
      base: 'resource',
      interest: null,
      primaryAction: 'visit',
      creation: 'contributor',
      presentation: 'default',
      cover: 'document',
      priority: 100,
      labels: labels(
        ['Topic', 'Topics'],
        '主題',
        '主题',
        'トピック',
        '주제',
        ['Thema', 'Themen'],
        ['Sujet', 'Sujets'],
        ['Tema', 'Temas'],
      ),
      browse: browse(
        'topics',
        5,
        'Topics',
        '主題',
        '主题',
        'トピック',
        '주제',
        'Themen',
        'Sujets',
        'Temas',
      ),
    },
    'rdfs:Resource': {
      base: 'resource',
      interest: null,
      primaryAction: 'visit',
      creation: 'contributor',
      presentation: 'default',
      cover: 'document',
      priority: 100,
      labels: labels(
        ['Resource', 'Resources'],
        '資源',
        '资源',
        'リソース',
        '리소스',
        ['Ressource', 'Ressourcen'],
        ['Ressource', 'Ressources'],
        ['Recurso', 'Recursos'],
      ),
    },
    'rv:Record': {
      base: 'record',
      interest: null,
      primaryAction: 'read',
      creation: 'contributor',
      presentation: 'default',
      cover: 'document',
      priority: 100,
      labels: labels(
        ['Record', 'Records'],
        '記錄',
        '记录',
        '記録',
        '기록',
        ['Datensatz', 'Datensätze'],
        ['Enregistrement', 'Enregistrements'],
        ['Registro', 'Registros'],
      ),
    },
    'rv:Character': {
      wikiSegment: 'characters',
      base: 'resource',
      interest: null,
      primaryAction: 'visit',
      creation: 'contributor',
      presentation: 'default',
      cover: 'document',
      priority: 100,
      labels: labels(
        ['Character', 'Characters'],
        '角色',
        '角色',
        'キャラクター',
        '캐릭터',
        ['Figur', 'Figuren'],
        ['Personnage', 'Personnages'],
        ['Personaje', 'Personajes'],
      ),
    },
    'rv:Role': {
      wikiSegment: 'characters',
      base: 'resource',
      interest: null,
      primaryAction: 'visit',
      creation: 'contributor',
      presentation: 'default',
      cover: 'document',
      priority: 100,
      labels: labels(
        ['Role', 'Roles'],
        '角色職能',
        '角色职能',
        '役割',
        '역할',
        ['Rolle', 'Rollen'],
        ['Rôle', 'Rôles'],
        ['Rol', 'Roles'],
      ),
    },
    'schema:Place': {
      wikiSegment: 'places',
      base: 'resource',
      interest: null,
      primaryAction: 'visit',
      creation: 'contributor',
      presentation: 'default',
      cover: 'document',
      priority: 100,
      labels: labels(
        ['Place', 'Places'],
        '地點',
        '地点',
        '場所',
        '장소',
        ['Ort', 'Orte'],
        ['Lieu', 'Lieux'],
        ['Lugar', 'Lugares'],
      ),
    },
    'schema:Event': {
      wikiSegment: 'events',
      base: 'resource',
      interest: null,
      primaryAction: 'visit',
      creation: 'contributor',
      presentation: 'default',
      cover: 'document',
      priority: 100,
      labels: labels(
        ['Event', 'Events'],
        '事件',
        '事件',
        '出来事',
        '사건',
        ['Ereignis', 'Ereignisse'],
        ['Événement', 'Événements'],
        ['Suceso', 'Sucesos'],
      ),
    },
    'rv:Release': {
      base: 'record',
      interest: null,
      primaryAction: 'read',
      creation: 'contributor',
      presentation: 'default',
      cover: 'document',
      priority: 100,
      labels: labels(
        ['Release', 'Releases'],
        '發行版',
        '发行版',
        'リリース',
        '릴리스',
        ['Veröffentlichung', 'Veröffentlichungen'],
        ['Publication', 'Publications'],
        ['Publicación', 'Publicaciones'],
      ),
    },
    'rv:FixedRelease': {
      base: 'record',
      interest: null,
      primaryAction: 'read',
      creation: 'contributor',
      presentation: 'default',
      cover: 'document',
      priority: 100,
      labels: labels(
        ['Fixed release', 'Fixed releases'],
        '固定發行版',
        '固定发行版',
        '固定リリース',
        '고정 릴리스',
        ['Fixierte Veröffentlichung', 'Fixierte Veröffentlichungen'],
        ['Publication figée', 'Publications figées'],
        ['Publicación fija', 'Publicaciones fijas'],
      ),
    },
    'schema:ListItem': {
      base: 'record',
      interest: null,
      primaryAction: 'read',
      creation: 'contributor',
      presentation: 'default',
      cover: 'document',
      priority: 100,
      labels: labels(
        ['List item', 'List items'],
        '清單項目',
        '列表项',
        'リスト項目',
        '목록 항목',
        ['Listeneintrag', 'Listeneinträge'],
        ['Élément de liste', 'Éléments de liste'],
        ['Elemento de lista', 'Elementos de lista'],
      ),
    },
    'rv:TextContribution': {
      base: 'record',
      interest: null,
      primaryAction: 'read',
      creation: 'contributor',
      presentation: 'default',
      cover: 'document',
      priority: 100,
      labels: labels(
        ['Text contribution', 'Text contributions'],
        '文字投稿',
        '文本投稿',
        'テキスト投稿',
        '텍스트 기여',
        ['Textbeitrag', 'Textbeiträge'],
        ['Contribution textuelle', 'Contributions textuelles'],
        ['Contribución de texto', 'Contribuciones de texto'],
      ),
    },
  },
} as const satisfies TypeRegistryDefinition;
