/** Launch exclusions are exact owner columns, never wildcard table policies.
 * Graph facts retain their original subject and appear on the survivor page.
 * Independent sessions, copies and exact evidence do not become Work slots. */
export const PERSON_STATE_MERGE_EXCLUSIONS: Readonly<Record<string,string>> = {
  'table:access.download_read_lease.target': 'An admitted byte-read lease pins the original asset/target and authority; merge cannot rewrite its permit.',
  'table:access.mod_work_binding.work': 'Native Mod identity and holder authority remain on the original Work.',
  'table:access.mod_work_release.work': 'Exact Mod release evidence and publisher identity remain on the original Work.',
  'table:access.suitability_assessment.target': 'An assessment retains its original target and Context; merge does not synthesize a new judgment.',
  'table:access.work_maintainer.work': 'Creator and maintainer authority never transfers.',
  'table:access.work_maintainer_receipt.target': 'Immutable maintainer command receipt retains its authority target.',
  'table:access.work_maintainer_receipt.work': 'Immutable maintainer command receipt retains its original Work.',
  'table:connected_app.consent_ceiling.resource': 'Private connected-app consent never expands to the survivor.',
  'table:reader.edition_preference.work': 'A preference selects an exact original Main Version/edition; editions remain independent facts.',
  'table:reader.library_import_placement.structure': 'An imported Collection occurrence retains its exact structure and placement receipt.',
  'table:reader.library_import_placement.work': 'Imported Collection membership remains on its original Work, like other graph facts.',
  'table:source.author_credit_intent.work': 'Pinned credit command and contributor evidence remain on the original Work.',
  'table:source.field_support.target': 'Source support retains the exact native fact it evidences.',
  'table:source.native_child_intent.work': 'Pinned child-adoption command retains its original parent and provenance.',
  'table:source.native_work_binding.work': 'Provider binding retains its evidenced original native Work.',
  'table:source.native_work_support_attachment.work': 'Source support remains attached to its exact original Work.',
  'table:source.native_work_title_application.work': 'Retained title-application receipt names its original component.',
  'table:source.native_work_title_intent.work': 'Pinned title command retains its original Work and authority.',
  'table:source.native_work_title_return_intent.work': 'Pinned title-return command retains its original Work and authority.',
  'table:structure.stage_job.structure': 'An exact selected-generation staging job is not a reader progress slot.',
  'table:reader.library_status_command.work': 'Immutable command receipt retains its original intent.',
  'table:reader.private_import_review.work': 'Private imported annotation remains attached to its original import; it is not a public review slot.',
  'table:structure.progress_command.structure': 'Exact occurrence command receipt retains its original structure and selection.',
  'table:structure.progress.structure': 'Reading progress pins an exact structure, occurrence and selection; independent attempts remain on the original Work, like sessions.',
  'table:reader.consumption_session.work': 'Independent reading sessions remain distinct; no session reconciliation at launch.',
  'table:reader.consumption_session_target.resource': 'An exact target within an independent session retains its original identity.',
  'table:access.reader_review_revision.work': 'Retained review revision is immutable history, not a live review slot.',
  'table:access.target_rating_head.target': 'Ratings of non-Work capability targets retain their exact grain.',
  'table:access.feed_vote.target': 'A vote names an exact activity, not a standing Work rating.',
  'table:access.home_exclusion.target': 'Private recommendation exclusions retain the named identity; preference reconciliation is deferred.',
  'table:access.interaction_mute_preference.target': 'Interaction mute targets are Agents and Realms, never Works.',
};
