// Environment configuration for Main processes. Each spec is the single
// declaration of the variables one entry point reads; `task env:example`
// renders them into services/main/.env.example.
import { cleanEnv, num, port, str, url } from 'envalid';

const postgres = (desc: string) => url({ desc, example: 'postgres://role:password@127.0.0.1:5432/role' });
const optionalPostgres = (desc: string) => url({ desc, default: undefined,
  example: 'postgres://role:password@127.0.0.1:5432/role' });
const secret = (desc: string) => str({ desc, example: '<generated by task dev:prepare>' });
const optionalSecret = (desc: string) => str({ desc, default: undefined, example: '<secret>' });

/** Variables shared by Main's API process and its relay. */
const graph = {
  FUSEKI_URL: url({ desc: 'Fuseki dataset URL, ending in /rezics/.', example: 'http://127.0.0.1:3030/rezics/' }),
  FUSEKI_MAINTENANCE_TOKEN: secret('Capability token for Fuseki maintenance requests.'),
  FUSEKI_COMMAND_TOKEN: secret('Capability token for Fuseki command requests.'),
  MAIN_DATA_EPOCH: str({ desc: 'Graph data epoch this stack was initialized with.', example: '1' }),
};

/** The Main API process (`services/main/src/index.ts`). */
export const mainSpec = {
  ...graph,
  MAIN_PORT: port({ default: 3001, desc: 'Port Main listens on at 127.0.0.1.' }),
  MAIN_ROUTING_EPOCH: str({ desc: 'Graph routing epoch this stack was initialized with.', example: '1' }),
  FUSEKI_TITLE_ADMISSION_KEY: secret('HMAC key for Fuseki title admission proofs.'),
  ACCESS_DATABASE_URL: postgres('Access owner PostgreSQL URL.'),
  MAIN_RATE_LIMIT_SECRET: str({ default: undefined, desc: 'Stable HMAC key (32+ characters) for principal/IP budgets; defaults to the title admission key.' }),
  MAIN_RATE_LIMIT_BUDGETS: str({ default: '{}', desc: 'Partial JSON overrides of main-rate-limit-v1 class/family maximum and seconds.' }),
  MAIN_READER_IMPORT_SEARCHES_PER_DAY: num({ default: 200, desc: 'Daily Library source search budget; local stacks may override.' }),
  MAIN_READER_IMPORT_ACQUISITIONS_PER_DAY: num({ default: 50, desc: 'Daily Library acquisition budget; local stacks may override.' }),
  MAIN_RATE_LIMIT_SERVICE_CLIENT_IDS: str({ default: '', desc: 'Comma-separated operator-installed Account client IDs with service budgets.' }),
  MAIN_RATE_LIMIT_TRUSTED_PROXY_PEERS: str({ default: '', desc: 'Comma-separated exact peer IP addresses allowed to supply the client IP header.' }),
  MAIN_RATE_LIMIT_CLIENT_IP_HEADER: str({ default: 'x-rezics-client-ip', desc: 'Single client IP header replaced by a configured trusted proxy.' }),
  CONTENT_DATABASE_URL: postgres('Content owner PostgreSQL URL.'),
  MAIN_RELAY_DATABASE_URL: optionalPostgres('Relay PostgreSQL URL; enables relay hand-off positions.'),
  MAIN_RELAY_CONSUMER: str({ desc: 'Relay consumer name; set together with MAIN_RELAY_DATABASE_URL.', default: undefined }),
  ACCOUNT_RELAY_DATABASE_URL: optionalPostgres('Account relay URL for erasure and recommendation events.'),
  OWNER_RELAY_DATABASE_URL: optionalPostgres('Relay URL for owner operations; defaults to MAIN_RELAY_DATABASE_URL.'),
  CONTENT_PROJECTION_CONSUMER: str({ default: 'main-content-public-search-v1',
    desc: 'Consumer name for the Content public search projection.' }),
  CONTENT_PROJECTION_INTERVAL_MS: num({ default: 1000, desc: 'Content projection polling interval.' }),
  MAIN_OBJECT_DIRECTORY: str({ desc: 'Directory for immutable Main objects without S3.', example: '.temp/stack/rezics-dev/objects' }),
  MAIN_OPEN_LIBRARY_FIXTURE_ROOT: str({ default: undefined,
    desc: 'Local dev only: checkout whose locked Open Library fixtures replace provider requests.' }),
  MAIN_S3_ENDPOINT: url({ desc: 'S3 endpoint for immutable objects (RustFS locally).', example: 'http://127.0.0.1:9000' }),
  MAIN_S3_BUCKET: str({ desc: 'S3 bucket.', example: 'rezics-semantic' }),
  MAIN_S3_REGION: str({ desc: 'S3 region.', example: 'us-east-1' }),
  MAIN_S3_ACCESS_KEY: secret('S3 access key.'),
  MAIN_S3_SECRET_KEY: secret('S3 secret key.'),
  ACCOUNT_ISSUER: url({ desc: 'Account OAuth issuer.', example: 'http://127.0.0.1:3002/api/auth' }),
  ACCOUNT_MAIN_RESOURCE: str({ desc: 'OAuth resource identifier for Main.', example: 'https://main.rezics.test' }),
  ACCOUNT_JWKS_URL: url({ desc: 'Account JWKS URL.', example: 'http://127.0.0.1:3002/api/auth/jwks' }),
  ACCOUNT_INTROSPECT_URL: url({ desc: 'Account token introspection URL.',
    example: 'http://127.0.0.1:3002/api/auth/oauth2/introspect' }),
  ACCOUNT_MAIN_CLIENT_ID: str({ desc: 'Main\'s confidential client ID at Account.', example: '<generated>' }),
  ACCOUNT_MAIN_CLIENT_SECRET: secret('Main\'s confidential client secret at Account.'),
  MAIN_NOTIFICATION_PROVIDER_URL: url({ default: undefined, desc: 'Notification provider URL; enables delivery.' }),
  MAIN_NOTIFICATION_PROVIDER_TOKEN: optionalSecret('Notification provider bearer token.'),
  MAIN_NOTIFICATION_CALLBACK_SECRET: optionalSecret('Secret for notification delivery callbacks.'),
  MAIN_NOTIFICATION_INTERVAL_MS: num({ default: 1000, desc: 'Notification delivery polling interval.' }),
  ACCOUNT_RECOVERY_DATABASE_URL: optionalPostgres('Account recovery URL used by owner operations.'),
  RECOVERY_MANIFEST_HMAC_KEY: optionalSecret('HMAC key for owner recovery manifests.'),
  OWNER_RELOCATION_TARGET_URL: optionalPostgres('Target URL for an owner relocation.'),
  OWNER_RELOCATION_TARGET_OBJECT_DIRECTORY: str({ default: undefined, desc: 'Target object directory for an owner relocation.' }),
  REZICS_LOAD_RUN_ID: str({ default: undefined, desc: 'Load run ID tagged onto search metrics during `task load`.' }),
};

/** The Main relay process (`services/main/src/relay.ts`). */
export const relaySpec = {
  FUSEKI_URL: graph.FUSEKI_URL,
  FUSEKI_MAINTENANCE_TOKEN: graph.FUSEKI_MAINTENANCE_TOKEN,
  FUSEKI_COMMAND_TOKEN: graph.FUSEKI_COMMAND_TOKEN,
  MAIN_RELAY_DATABASE_URL: postgres('Relay PostgreSQL URL.'),
  MAIN_RELAY_CONSUMER: str({ desc: 'Relay consumer name.', example: 'main-graph-v1' }),
  MAIN_RELAY_INTERVAL_MS: num({ default: 1000, desc: 'Relay polling interval.' }),
};

/** Relay checkpoint initialization (`services/main/src/relay-init.ts`). */
export const relayInitSpec = {
  MAIN_RELAY_DATABASE_URL: relaySpec.MAIN_RELAY_DATABASE_URL,
  MAIN_RELAY_CONSUMER: relaySpec.MAIN_RELAY_CONSUMER,
  MAIN_DATA_EPOCH: graph.MAIN_DATA_EPOCH,
};

export function mainConfig(env: Record<string, string | undefined> = process.env) {
  const config = cleanEnv(env, mainSpec);
  if (Boolean(config.MAIN_RELAY_DATABASE_URL) !== Boolean(config.MAIN_RELAY_CONSUMER)) {
    throw new Error('MAIN_RELAY_DATABASE_URL and MAIN_RELAY_CONSUMER are configured together');
  }
  return config;
}

export type MainConfig = ReturnType<typeof mainConfig>;
