// Environment configuration for Account processes. `task env:example` renders
// these specs into services/account/.env.example.
import { bool, cleanEnv, port, str, url } from 'envalid';

/** Variables every Account entry point needs to build its auth instance. */
export const accountCoreSpec = {
  ACCOUNT_BASE_URL: url({ desc: 'Public base URL of Account; the OAuth issuer is <base>/api/auth.',
    example: 'http://127.0.0.1:3002' }),
  ACCOUNT_SECRET: str({ desc: 'Better Auth secret.', example: '<generated by task dev:prepare>' }),
  ACCOUNT_MAIN_RESOURCE: str({ desc: 'OAuth resource identifier for Main.', example: 'https://main.rezics.test' }),
  ACCOUNT_DATABASE_URL: url({ desc: 'Account owner PostgreSQL URL.',
    example: 'postgres://account:password@127.0.0.1:5432/account' }),
};

/** The Account HTTP process (`services/account/src/index.ts`). */
export const accountSpec = {
  ...accountCoreSpec,
  ACCOUNT_POLICY_ACCEPTANCE_ENFORCED: bool({ default: true,
    desc: 'Require existing sessions to accept the current policies before OAuth authorization; the Accounts site sends them to its acceptance page. Set false only to stage a rollout.' }),
  ACCOUNT_TURNSTILE_MODE: str({ choices: ['local', 'cloudflare'], default: 'cloudflare', devDefault: 'local',
    desc: 'Enrollment verifier: cloudflare in production; local always-pass mode permits offline dev/test API clients.' }),
  ACCOUNT_TURNSTILE_SECRET_KEY: str({ default: '',
    desc: 'Cloudflare Turnstile secret, required only in cloudflare mode.' }),
  ACCOUNT_PORT: port({ default: 3002, desc: 'Port Account listens on at 127.0.0.1.' }),
  ACCOUNT_TRUSTED_PROXY_PEERS: str({ default: '',
    desc: 'Comma-separated socket peer IPs whose ingress replaces X-Forwarded-For with one client address.' }),
  ACCOUNT_ACCESS_DATABASE_URL: url({ default: undefined,
    desc: 'Access owner URL; enables the account deletion fence. Requires ACCOUNT_RELAY_DATABASE_URL.',
    example: 'postgres://access:password@127.0.0.1:5432/access' }),
  ACCOUNT_RELAY_DATABASE_URL: url({ default: undefined, desc: 'Relay URL for account deletion events.',
    example: 'postgres://relay:password@127.0.0.1:5432/relay' }),
  ACCOUNT_OPERATOR_USER_IDS: str({ default: '', desc: 'One-time first-owner bootstrap candidates; subsequent authority uses stored roles.' }),
  WEB_OAUTH_CLIENT_ID: str({ default: '', desc: 'First-party web OAuth client allowed to read and write display preferences.' }),
  ACCOUNT_MAIN_CLIENT_SECRET: str({ desc: 'Main confidential client secret for its Account-owned email digest intake.',
    example: '<generated by task dev:prepare>' }),
  ACCOUNT_MAIL_EVENTS_SECRET: str({ default: '',
    desc: 'Provider-neutral bounce/complaint HMAC secret (at least 32 characters); empty disables intake.' }),
  ACCOUNT_SMTP_HOST: str({ default: '127.0.0.1', desc: 'SMTP host; local development uses Mailpit.' }),
  ACCOUNT_SMTP_PORT: port({ default: 1025, desc: 'SMTP port; Mailpit uses 1025 (web UI 8025).' }),
  ACCOUNT_SMTP_SECURE: bool({ default: false, desc: 'Use TLS immediately (usually port 465).' }),
  ACCOUNT_SMTP_REQUIRE_TLS: bool({ default: false, desc: 'Require STARTTLS; enable for remote SMTP.' }),
  ACCOUNT_SMTP_USER: str({ default: '', desc: 'SMTP authentication username, if required.' }),
  ACCOUNT_SMTP_PASSWORD: str({ default: '', desc: 'SMTP authentication password.' }),
  ACCOUNT_EMAIL_FROM: str({ default: 'REZICS <accounts@localhost>', desc: 'Verified transactional sender address.' }),
  FUSEKI_TITLE_ADMISSION_KEY: str({ default: undefined, desc: 'HMAC key for Access title admission proofs.',
    example: '<generated by task dev:prepare>' }),
};

export function accountConfig(env: Record<string, string | undefined> = process.env) {
  const config = cleanEnv(env, accountSpec);
  if (config.ACCOUNT_MAIL_EVENTS_SECRET && config.ACCOUNT_MAIL_EVENTS_SECRET.length < 32) {
    throw new Error('ACCOUNT_MAIL_EVENTS_SECRET must contain at least 32 characters');
  }
  if ((config.ACCOUNT_TURNSTILE_MODE === 'cloudflare' && !config.ACCOUNT_TURNSTILE_SECRET_KEY.trim())
    || (env.NODE_ENV === 'production' && (config.ACCOUNT_TURNSTILE_MODE === 'local'
      || /^[123]x0+AA$/.test(config.ACCOUNT_TURNSTILE_SECRET_KEY)))) {
    throw new Error('ACCOUNT_TURNSTILE_SECRET_KEY must be configured; test keys are development-only');
  }
  if (config.ACCOUNT_ACCESS_DATABASE_URL && !config.ACCOUNT_RELAY_DATABASE_URL) {
    throw new Error('ACCOUNT_RELAY_DATABASE_URL is required when ACCOUNT_ACCESS_DATABASE_URL enables deletion');
  }
  if (!['127.0.0.1', 'localhost', '::1'].includes(config.ACCOUNT_SMTP_HOST)
    && !config.ACCOUNT_SMTP_SECURE && !config.ACCOUNT_SMTP_REQUIRE_TLS) {
    throw new Error('Remote Account SMTP requires TLS');
  }
  return config;
}
