import { validExposure, type Exposure } from '../../services/main/src/modules/access/exposure.ts';
import { exposureOperationId } from '../../services/main/src/modules/access/exposure-routes.ts';

export interface ExposedRoute {
  method: string;
  path: string;
  hooks: {
    detail?: {
      operationId?: string;
      'x-rezics-exposure'?: unknown;
    };
  };
}

/** Includes health, discovery, ALL transports and WS upgrades, even when hidden
 * from OpenAPI. A new served route cannot silently inherit public exposure. */
export function assertRouteExposures(routes: readonly ExposedRoute[]): void {
  for (const route of routes) {
    if (!validExposure(route.hooks.detail?.['x-rezics-exposure'])) {
      throw new Error(`Main operation has no exposure declaration: ${route.method} ${route.path}`);
    }
  }
}

/** Exposure is an additional refusal. Preserve the resource owner's existing
 * 403 schema and normalize its media type before the later document pass. */
export function platformClosedResponse(existing?: {
  description?: string;
  content?: Record<string, unknown>;
}) {
  const content = { ...existing?.content };
  const media = content['application/problem+json'] ?? content['application/json'];
  const prior = media && typeof media === 'object' ? (media as Record<string, unknown>) : undefined;
  delete content['application/json'];
  const closed = {
    type: 'object',
    required: ['type', 'status', 'code', 'title'],
    properties: {
      type: { type: 'string' },
      status: { const: 403 },
      code: { const: 'platform_closed' },
      title: { type: 'string' },
    },
  };
  return {
    ...existing,
    description: [existing?.description, 'Capability closed (platform_closed)']
      .filter(Boolean)
      .join('; '),
    content: {
      ...content,
      'application/problem+json': {
        ...prior,
        schema: prior?.schema ? { anyOf: [prior.schema, closed] } : closed,
      },
    },
  };
}

/** Anonymous callers of a closed operation authenticate before any grant check.
 * Preserve an existing 401 schema beside the two platform authentication codes. */
export function platformUnauthenticatedResponse(existing?: {
  description?: string;
  content?: Record<string, unknown>;
}) {
  const content = { ...existing?.content };
  const media = content['application/problem+json'] ?? content['application/json'];
  const prior = media && typeof media === 'object' ? (media as Record<string, unknown>) : undefined;
  delete content['application/json'];
  const problem = (code: string) => ({
    type: 'object',
    required: ['type', 'status', 'code', 'title'],
    properties: {
      type: { type: 'string' },
      status: { const: 401 },
      code: { const: code },
      title: { type: 'string' },
    },
  });
  const unauthenticated = {
    anyOf: [problem('unauthorized'), problem('invalid_account_assertion')],
  };
  return {
    ...existing,
    description: [existing?.description, 'Authentication required before a closed capability is checked']
      .filter(Boolean)
      .join('; '),
    content: {
      ...content,
      'application/problem+json': {
        ...prior,
        schema: prior?.schema ? { anyOf: [prior.schema, unauthenticated] } : unauthenticated,
      },
    },
  };
}

/** SDK metadata is derived from route-owned declarations, never another policy
 * source. External clients can compare it with the private viewer summary. */
export function exposureSdkSource(routes: readonly ExposedRoute[]): string {
  assertRouteExposures(routes);
  const entries = routes
    .map(
      (route) =>
        [
          route.hooks.detail?.operationId ?? exposureOperationId(route.method, route.path),
          route.hooks.detail!['x-rezics-exposure'] as Exposure,
        ] as const,
    )
    .sort(([a], [b]) => a.localeCompare(b));
  return (
    '// Generated by task gen from Main route declarations.\n' +
    'export const operationExposures = ' +
    JSON.stringify(Object.fromEntries(entries), null, 2) +
    ' as const;\n' +
    'export type PlatformOperationId = keyof typeof operationExposures;\n' +
    'export interface PlatformAccessSummary { groups: readonly string[]; operations: readonly string[]; generation: string }\n' +
    'export function platformOperationOpen(operation: PlatformOperationId, viewer: PlatformAccessSummary): boolean {\n' +
    '  const exposure: string = operationExposures[operation];\n' +
    "  return exposure === 'public' || viewer.groups.includes(exposure.slice('platform:'.length)) || viewer.operations.includes(operation);\n}\n" +
    '/** A closed operation answers this status before a grant check when the caller is anonymous. */\n' +
    'export const platformClosedAnonymousStatus = 401;\n'
  );
}
