/** Bootstrap graph data only. Clients obtain these draft labels from Main, never this file. */
export type LexiconSeedLabel = readonly [
  language: string,
  noun: string,
  plural: string,
  inverseNoun: string,
  inversePlural: string,
];
export interface LexiconSeedDefinition {
  key: string;
  /** The two labelled roles; each direction of labels runs between them. */
  roles: readonly [string, string];
  /** Required singleton roles beyond the labelled pair. */
  extraRoles?: readonly string[];
  /** Role keys of the star constraint, repeated into the definition state. */
  star?: { leaf: string; hub: string };
  /** `false` leaves the relation open to any relation editor instead of a Work's editor. */
  workAuthority?: false;
  editorRecordable?: boolean;
  writePath?: 'derivation' | 'relation';
  labels: readonly LexiconSeedLabel[];
}
export const relationLexiconSeed = [
  {
    key: 'adaptation',
    editorRecordable: true,
    writePath: 'derivation',
    roles: ['source', 'adaptation'],
    labels: [
      ['en', 'Adaptation', 'Adaptations', 'Adapted from', 'Adapted from'],
      ['zh-Hant', '改編作品', '改編作品', '改編自', '改編自'],
      ['zh-Hans', '改编作品', '改编作品', '改编自', '改编自'],
      ['ja', '翻案作品', '翻案作品', '翻案元', '翻案元'],
      ['ko', '각색 작품', '각색 작품', '원작', '원작'],
      ['de', 'Adaption', 'Adaptionen', 'Adaptiert von', 'Adaptiert von'],
      ['fr', 'Adaptation', 'Adaptations', 'Adapté de', 'Adapté de'],
      ['es', 'Adaptación', 'Adaptaciones', 'Adaptación de', 'Adaptaciones de'],
    ],
  },
  {
    key: 'new-recording',
    roles: ['source', 'recording'],
    labels: [
      ['en', 'New recording', 'New recordings', 'New recording of', 'New recordings of'],
      ['zh-Hant', '重新錄製', '重新錄製', '重新錄製自', '重新錄製自'],
      ['zh-Hans', '重新录制', '重新录制', '重新录制自', '重新录制自'],
      ['ja', '再録音', '再録音', '再録音元', '再録音元'],
      ['ko', '새 녹음', '새 녹음', '새로 녹음한 원본', '새로 녹음한 원본'],
      ['de', 'Neuaufnahme', 'Neuaufnahmen', 'Neuaufnahme von', 'Neuaufnahmen von'],
      [
        'fr',
        'Nouvel enregistrement',
        'Nouveaux enregistrements',
        'Nouvel enregistrement de',
        'Nouveaux enregistrements de',
      ],
      [
        'es',
        'Nueva grabación',
        'Nuevas grabaciones',
        'Nueva grabación de',
        'Nuevas grabaciones de',
      ],
    ],
  },
  {
    key: 'software-fork',
    roles: ['source', 'fork'],
    labels: [
      ['en', 'Software fork', 'Software forks', 'Forked from', 'Forked from'],
      ['zh-Hant', '軟體分支', '軟體分支', '分支源自', '分支源自'],
      ['zh-Hans', '软件分支', '软件分支', '分支源自', '分支源自'],
      ['ja', 'ソフトウェアのフォーク', 'ソフトウェアのフォーク', 'フォーク元', 'フォーク元'],
      ['ko', '소프트웨어 포크', '소프트웨어 포크', '포크 원본', '포크 원본'],
      ['de', 'Software-Fork', 'Software-Forks', 'Abgespalten von', 'Abgespalten von'],
      ['fr', 'Fork logiciel', 'Forks logiciels', 'Dérivé de', 'Dérivés de'],
      [
        'es',
        'Bifurcación de software',
        'Bifurcaciones de software',
        'Bifurcación de',
        'Bifurcaciones de',
      ],
    ],
  },
  {
    key: 'rewrite',
    editorRecordable: true,
    writePath: 'derivation',
    roles: ['source', 'rewrite'],
    labels: [
      ['en', 'Rewrite', 'Rewrites', 'Rewrite of', 'Rewrites of'],
      ['zh-Hant', '重寫作品', '重寫作品', '重寫自', '重寫自'],
      ['zh-Hans', '重写作品', '重写作品', '重写自', '重写自'],
      ['ja', '書き直し作品', '書き直し作品', '書き直し元', '書き直し元'],
      ['ko', '다시 쓴 작품', '다시 쓴 작품', '다시 쓴 원작', '다시 쓴 원작'],
      ['de', 'Neufassung', 'Neufassungen', 'Neufassung von', 'Neufassungen von'],
      ['fr', 'Réécriture', 'Réécritures', 'Réécriture de', 'Réécritures de'],
      ['es', 'Reescritura', 'Reescrituras', 'Reescritura de', 'Reescrituras de'],
    ],
  },
  {
    key: 'reboot',
    editorRecordable: true,
    writePath: 'derivation',
    roles: ['source', 'reboot'],
    labels: [
      ['en', 'Reboot', 'Reboots', 'Reboot of', 'Reboots of'],
      ['zh-Hant', '重啟作品', '重啟作品', '重啟自', '重啟自'],
      ['zh-Hans', '重启作品', '重启作品', '重启自', '重启自'],
      ['ja', 'リブート作品', 'リブート作品', 'リブート元', 'リブート元'],
      ['ko', '리부트 작품', '리부트 작품', '리부트 원작', '리부트 원작'],
      ['de', 'Neustart', 'Neustarts', 'Neustart von', 'Neustarts von'],
      ['fr', 'Reboot', 'Reboots', 'Reboot de', 'Reboots de'],
      ['es', 'Reinicio', 'Reinicios', 'Reinicio de', 'Reinicios de'],
    ],
  },
  {
    key: 'sequel',
    editorRecordable: true,
    writePath: 'relation',
    roles: ['predecessor', 'sequel'],
    labels: [
      ['en', 'Sequel', 'Sequels', 'Sequel to', 'Sequels to'],
      ['zh-Hant', '續作', '續作', '前作', '前作'],
      ['zh-Hans', '续作', '续作', '前作', '前作'],
      ['ja', '続編', '続編', '前作', '前作'],
      ['ko', '후속작', '후속작', '전작', '전작'],
      ['de', 'Fortsetzung', 'Fortsetzungen', 'Fortsetzung von', 'Fortsetzungen von'],
      ['fr', 'Suite', 'Suites', 'Suite de', 'Suites de'],
      ['es', 'Secuela', 'Secuelas', 'Secuela de', 'Secuelas de'],
    ],
  },
  {
    key: 'spin-off',
    editorRecordable: true,
    writePath: 'relation',
    roles: ['source', 'spin-off'],
    labels: [
      ['en', 'Spin-off', 'Spin-offs', 'Spin-off of', 'Spin-offs of'],
      ['zh-Hant', '衍生作品', '衍生作品', '衍生自', '衍生自'],
      ['zh-Hans', '衍生作品', '衍生作品', '衍生自', '衍生自'],
      ['ja', 'スピンオフ作品', 'スピンオフ作品', 'スピンオフ元', 'スピンオフ元'],
      ['ko', '스핀오프 작품', '스핀오프 작품', '스핀오프 원작', '스핀오프 원작'],
      ['de', 'Ableger', 'Ableger', 'Ableger von', 'Ableger von'],
      ['fr', 'Œuvre dérivée', 'Œuvres dérivées', 'Œuvre dérivée de', 'Œuvres dérivées de'],
      ['es', 'Obra derivada', 'Obras derivadas', 'Obra derivada de', 'Obras derivadas de'],
    ],
  },
  {
    key: 'correspondence-equivalent',
    editorRecordable: true,
    writePath: 'relation',
    roles: ['source', 'target'],
    labels: [
      [
        'en',
        'Equivalent counterpart',
        'Equivalent counterparts',
        'Equivalent counterpart',
        'Equivalent counterparts',
      ],
      ['zh-Hant', '等同對應', '等同對應', '等同對應', '等同對應'],
      ['zh-Hans', '等同对应', '等同对应', '等同对应', '等同对应'],
      ['ja', '等価な対応物', '等価な対応物', '等価な対応物', '等価な対応物'],
      ['ko', '동등한 대응', '동등한 대응', '동등한 대응', '동등한 대응'],
      [
        'de',
        'Gleichwertige Entsprechung',
        'Gleichwertige Entsprechungen',
        'Gleichwertige Entsprechung',
        'Gleichwertige Entsprechungen',
      ],
      [
        'fr',
        'Correspondance équivalente',
        'Correspondances équivalentes',
        'Correspondance équivalente',
        'Correspondances équivalentes',
      ],
      [
        'es',
        'Correspondencia equivalente',
        'Correspondencias equivalentes',
        'Correspondencia equivalente',
        'Correspondencias equivalentes',
      ],
    ],
  },
  {
    key: 'correspondence-partial',
    editorRecordable: true,
    writePath: 'relation',
    roles: ['source', 'target'],
    labels: [
      [
        'en',
        'Partial counterpart',
        'Partial counterparts',
        'Partial counterpart',
        'Partial counterparts',
      ],
      ['zh-Hant', '部分對應', '部分對應', '部分對應', '部分對應'],
      ['zh-Hans', '部分对应', '部分对应', '部分对应', '部分对应'],
      ['ja', '部分的な対応物', '部分的な対応物', '部分的な対応物', '部分的な対応物'],
      ['ko', '부분 대응', '부분 대응', '부분 대응', '부분 대응'],
      [
        'de',
        'Teilweise Entsprechung',
        'Teilweise Entsprechungen',
        'Teilweise Entsprechung',
        'Teilweise Entsprechungen',
      ],
      [
        'fr',
        'Correspondance partielle',
        'Correspondances partielles',
        'Correspondance partielle',
        'Correspondances partielles',
      ],
      [
        'es',
        'Correspondencia parcial',
        'Correspondencias parciales',
        'Correspondencia parcial',
        'Correspondencias parciales',
      ],
    ],
  },
  {
    key: 'correspondence-revised',
    editorRecordable: true,
    writePath: 'relation',
    roles: ['source', 'revision'],
    labels: [
      ['en', 'Revised counterpart', 'Revised counterparts', 'Revised from', 'Revised from'],
      ['zh-Hant', '修訂對應', '修訂對應', '修訂自', '修訂自'],
      ['zh-Hans', '修订对应', '修订对应', '修订自', '修订自'],
      ['ja', '改訂された対応物', '改訂された対応物', '改訂元', '改訂元'],
      ['ko', '개정 대응', '개정 대응', '개정 원본', '개정 원본'],
      [
        'de',
        'Überarbeitete Entsprechung',
        'Überarbeitete Entsprechungen',
        'Überarbeitet von',
        'Überarbeitet von',
      ],
      ['fr', 'Correspondance révisée', 'Correspondances révisées', 'Révisé de', 'Révisés de'],
      [
        'es',
        'Correspondencia revisada',
        'Correspondencias revisadas',
        'Revisión de',
        'Revisiones de',
      ],
    ],
  },
  {
    key: 'composition-part',
    roles: ['whole', 'part'],
    labels: [
      ['en', 'Part', 'Parts', 'Part of', 'Parts of'],
      ['zh-Hant', '組成部分', '組成部分', '所屬整體', '所屬整體'],
      ['zh-Hans', '组成部分', '组成部分', '所属整体', '所属整体'],
      ['ja', '構成部分', '構成部分', '所属する全体', '所属する全体'],
      ['ko', '구성 부분', '구성 부분', '소속 전체', '소속 전체'],
      ['de', 'Teil', 'Teile', 'Teil von', 'Teile von'],
      ['fr', 'Partie', 'Parties', 'Partie de', 'Parties de'],
      ['es', 'Parte', 'Partes', 'Parte de', 'Partes de'],
    ],
  },
  {
    key: 'credit-author',
    roles: ['work', 'contributor'],
    labels: [
      ['en', 'Author', 'Authors', 'Author of', 'Works authored'],
      ['zh-Hant', '作者', '作者', '創作作品', '創作作品'],
      ['zh-Hans', '作者', '作者', '创作作品', '创作作品'],
      ['ja', '著者', '著者', '著作', '著作'],
      ['ko', '저자', '저자', '집필 작품', '집필 작품'],
      ['de', 'Autor', 'Autoren', 'Autor von', 'Verfasste Werke'],
      ['fr', 'Auteur', 'Auteurs', 'Auteur de', 'Œuvres écrites'],
      ['es', 'Autor', 'Autores', 'Autor de', 'Obras escritas'],
    ],
  },
  {
    key: 'credit-illustrator',
    roles: ['work', 'contributor'],
    labels: [
      ['en', 'Illustrator', 'Illustrators', 'Illustrator of', 'Works illustrated'],
      ['zh-Hant', '插畫家', '插畫家', '插畫作品', '插畫作品'],
      ['zh-Hans', '插画家', '插画家', '插画作品', '插画作品'],
      ['ja', 'イラストレーター', 'イラストレーター', '挿絵を担当した作品', '挿絵を担当した作品'],
      ['ko', '삽화가', '삽화가', '삽화 작품', '삽화 작품'],
      ['de', 'Illustrator', 'Illustratoren', 'Illustrator von', 'Illustrierte Werke'],
      ['fr', 'Illustrateur', 'Illustrateurs', 'Illustrateur de', 'Œuvres illustrées'],
      ['es', 'Ilustrador', 'Ilustradores', 'Ilustrador de', 'Obras ilustradas'],
    ],
  },
  {
    key: 'credit-translator',
    roles: ['work', 'contributor'],
    labels: [
      ['en', 'Translator', 'Translators', 'Translator of', 'Works translated'],
      ['zh-Hant', '譯者', '譯者', '翻譯作品', '翻譯作品'],
      ['zh-Hans', '译者', '译者', '翻译作品', '翻译作品'],
      ['ja', '翻訳者', '翻訳者', '翻訳作品', '翻訳作品'],
      ['ko', '번역가', '번역가', '번역 작품', '번역 작품'],
      ['de', 'Übersetzer', 'Übersetzer', 'Übersetzer von', 'Übersetzte Werke'],
      ['fr', 'Traducteur', 'Traducteurs', 'Traducteur de', 'Œuvres traduites'],
      ['es', 'Traductor', 'Traductores', 'Traductor de', 'Obras traducidas'],
    ],
  },
  {
    key: 'credit-concept-supervision',
    roles: ['work', 'contributor'],
    labels: [
      [
        'en',
        'Concept supervisor',
        'Concept supervisors',
        'Concept supervision for',
        'Works supervised',
      ],
      ['zh-Hant', '概念監修', '概念監修', '概念監修作品', '概念監修作品'],
      ['zh-Hans', '概念监修', '概念监修', '概念监修作品', '概念监修作品'],
      ['ja', 'コンセプト監修', 'コンセプト監修', 'コンセプト監修作品', 'コンセプト監修作品'],
      ['ko', '콘셉트 감수', '콘셉트 감수', '콘셉트 감수 작품', '콘셉트 감수 작품'],
      ['de', 'Konzeptaufsicht', 'Konzeptaufsicht', 'Konzeptaufsicht für', 'Betreute Werke'],
      [
        'fr',
        'Supervision du concept',
        'Supervision des concepts',
        'Supervision du concept de',
        'Œuvres supervisées',
      ],
      [
        'es',
        'Supervisión del concepto',
        'Supervisión de conceptos',
        'Supervisión del concepto de',
        'Obras supervisadas',
      ],
    ],
  },
  {
    key: 'variant-of',
    workAuthority: false,
    roles: ['hub', 'variant'],
    extraRoles: ['kind'],
    star: { leaf: 'variant', hub: 'hub' },
    labels: [
      ['en', 'Variant', 'Variants', 'Variant of', 'Variants of'],
      ['zh-Hant', '變體', '變體', '變體本體', '變體本體'],
      ['zh-Hans', '变体', '变体', '变体本体', '变体本体'],
      ['ja', 'バリアント', 'バリアント', 'バリアント元', 'バリアント元'],
      ['ko', '변형', '변형', '변형 원본', '변형 원본'],
      ['de', 'Variante', 'Varianten', 'Variante von', 'Varianten von'],
      ['fr', 'Variante', 'Variantes', 'Variante de', 'Variantes de'],
      ['es', 'Variante', 'Variantes', 'Variante de', 'Variantes de'],
    ],
  },
  {
    key: 'holds-title',
    workAuthority: false,
    roles: ['title', 'holder'],
    labels: [
      ['en', 'Holder', 'Holders', 'Title held', 'Titles held'],
      ['zh-Hant', '持有者', '持有者', '所持稱號', '所持稱號'],
      ['zh-Hans', '持有者', '持有者', '所持称号', '所持称号'],
      ['ja', '保持者', '保持者', '保持する称号', '保持する称号'],
      ['ko', '보유자', '보유자', '보유 칭호', '보유 칭호'],
      ['de', 'Titelträger', 'Titelträger', 'Getragener Titel', 'Getragene Titel'],
      ['fr', 'Titulaire', 'Titulaires', 'Titre porté', 'Titres portés'],
      ['es', 'Titular', 'Titulares', 'Título que ostenta', 'Títulos que ostenta'],
    ],
  },
  {
    key: 'represents',
    workAuthority: false,
    roles: ['character', 'unit'],
    labels: [
      ['en', 'Unit', 'Units', 'Represents', 'Represents'],
      ['zh-Hant', '單位', '單位', '代表角色', '代表角色'],
      ['zh-Hans', '单位', '单位', '代表角色', '代表角色'],
      ['ja', 'ユニット', 'ユニット', '代表キャラクター', '代表キャラクター'],
      ['ko', '유닛', '유닛', '대표 캐릭터', '대표 캐릭터'],
      ['de', 'Einheit', 'Einheiten', 'Stellt dar', 'Stellt dar'],
      ['fr', 'Unité', 'Unités', 'Représente', 'Représente'],
      ['es', 'Unidad', 'Unidades', 'Representa', 'Representa'],
    ],
  },
  {
    key: 'in-continuity',
    roles: ['continuity', 'work'],
    labels: [
      ['en', 'Work', 'Works', 'In continuity', 'In continuities'],
      ['zh-Hant', '作品', '作品', '所屬連續性', '所屬連續性'],
      ['zh-Hans', '作品', '作品', '所属连续性', '所属连续性'],
      ['ja', '作品', '作品', '所属する連続性', '所属する連続性'],
      ['ko', '작품', '작품', '소속 연속성', '소속 연속성'],
      ['de', 'Werk', 'Werke', 'In Kontinuität', 'In Kontinuitäten'],
      ['fr', 'Œuvre', 'Œuvres', 'Dans la continuité', 'Dans les continuités'],
      ['es', 'Obra', 'Obras', 'En la continuidad', 'En las continuidades'],
    ],
  },
] as const satisfies readonly LexiconSeedDefinition[];

/** Concepts named by the `kind` role of `variant-of`; they are Concepts, so a kind is data, not a new type. */
export const variantKindConcepts = [
  { key: 'persona', labels: [
    { language: 'en', value: 'Persona' }, { language: 'zh-Hant', value: '化身' },
    { language: 'zh-Hans', value: '化身' }, { language: 'ja', value: 'ペルソナ' },
    { language: 'ko', value: '페르소나' }, { language: 'de', value: 'Persona' },
    { language: 'fr', value: 'Persona' }, { language: 'es', value: 'Persona' },
  ] },
  { key: 'counterpart', labels: [
    { language: 'en', value: 'Counterpart' }, { language: 'zh-Hant', value: '對應者' },
    { language: 'zh-Hans', value: '对应者' }, { language: 'ja', value: '対応者' },
    { language: 'ko', value: '대응 인물' }, { language: 'de', value: 'Gegenstück' },
    { language: 'fr', value: 'Homologue' }, { language: 'es', value: 'Contraparte' },
  ] },
] as const;
