// Rebuild Main's composition root after union merges: every domain plugin used anywhere in app.ts is
// mounted once, in first-seen order, in nested groups short enough for TypeScript to infer MainApp.
import { readFileSync, writeFileSync } from 'node:fs';

const file = 'services/main/src/app.ts';
const text = readFileSync(file, 'utf8');
const groupNames = ['identitySourceRoutes', 'accessSearchRoutes', 'contentCommunityRoutes', 'domainRoutes',
  'extraRoutes1', 'extraRoutes2', 'extraRoutes3', 'extraRoutes4', 'extraRoutes5'];
const calls = new Map<string, string>();
for (const match of text.matchAll(/\.use\((\w+Routes)\(([^)]*)\)\)/g)) {
  const [, name, args] = match;
  if (name === 'healthRoutes' || groupNames.includes(name!) || calls.has(name!)) continue;
  calls.set(name!, `${name}(${args})`);
}
const header = text.slice(0, text.search(/\n(function identitySourceRoutes|\/\*\* Composition root)/));
const footer = text.slice(text.indexOf('/** Inferred product route contract'));
const entries = [...calls.values()];
const groups: string[][] = [];
for (let i = 0; i < entries.length; i += 9) groups.push(entries.slice(i, i + 9));
if (groups.length > groupNames.length) throw new Error('Too many route plugins for the declared groups');
const functions = groups.map((group, index) => `function ${groupNames[index]}(fuseki: FusekiClient, work: SearchRouteDependencies) {
  return new Elysia()
${group.map(call => `    .use(${call})`).join('\n')};
}
`).join('\n');
const body = `/** Composition root: each domain plugin under \`routes/\` owns its registrations. */
export function createMainApp(fuseki: FusekiClient, work?: SearchRouteDependencies) {
  // Registered first so it also handles every plugin route mounted below.
  const app = new Elysia()
    .error(({ error }) => {
      if (error instanceof ValidationError || error instanceof ParseError) {
        return problem(400, 'invalid_request', 'Request does not match the Work contract');
      }
      // Unknown paths and unsupported methods on known paths.
      if (error instanceof NotFound) return problem(404, 'not_found', 'No such operation');
      return problem(500, 'internal_error', 'Request could not be processed');
    })
    .use(healthRoutes(fuseki, work));
  if (work) {
    // Generated by scripts/goal/normalize-app.ts: nested groups keep each .use() chain short
    // enough for TypeScript to infer MainApp. Add a domain plugin as one .use() line anywhere here.
    return app
${groups.map((_, index) => `      .use(${groupNames[index]}(fuseki, work))`).join('\n')};
  }
  return app;
}

`;
writeFileSync(file, `${header.trimEnd()}\n\n${functions}\n${body}${footer}`);
console.log(`${file}: ${entries.length} route plugins in ${groups.length} groups`);
