import { expect, test } from 'bun:test';
import * as fc from 'fast-check';
import { checkNodeLocalCandidate, profileRegistry, shapeArbitraries } from '../../../packages/model/src/index.ts';
import { governanceBodyScopeId, proposalGraphProfile } from '../src/modules/proposal/schema.ts';
import { pollScopeId, voteGraphProfiles } from '../src/modules/vote/schema.ts';

// Node-local checks of the vote owner profiles. Jena's transactional SHACL and
// the command guards remain authoritative for links, heads and unit conservation.
const rv = (name: string) => `https://rezics.com/vocab/${name}`;
const shape = (profile: string, role: string) => `https://rezics.com/definition/${profile}/${role}-shape`;
type Candidate = Record<string, unknown>;

function sample(shapeIri: string, overrides: Candidate, removed: readonly string[] = []): Candidate {
  const arbitrary = shapeArbitraries[shapeIri as keyof typeof shapeArbitraries] as fc.Arbitrary<Candidate>;
  const [base] = fc.sample(arbitrary, { seed: 53, numRuns: 1 });
  const candidate: Candidate = { ...base, ...overrides };
  for (const key of removed) delete candidate[key];
  return candidate;
}
const valid = (shapeIri: string, candidate: Candidate) => checkNodeLocalCandidate(shapeIri, candidate);

test('vote schema: graph profiles publish their focus roles', () => {
  // Generated by the integration wave's `task gen`; absent profiles fail here, not in tsc.
  const registry: Readonly<Record<string, { focusRoles: readonly string[] } | undefined>> = profileRegistry;
  expect([...voteGraphProfiles, proposalGraphProfile].map(id => [id, registry[id]?.focusRoles])).toEqual([
    ['charter-revision-v1', ['charter', 'electorate-revision', 'holder-revision']],
    ['poll-snapshot-v1', ['poll', 'question', 'option', 'snapshot', 'entitlement', 'opening']],
    ['poll-allocation-v1', ['plan', 'leaf', 'activation']],
    ['ballot-proxy-v1', ['route', 'revision']],
    ['ballot-mandate-approval-v1', ['approval']],
    ['ballot-v1', ['ballot', 'revision', 'share']],
    ['poll-resolution-v1', ['resolution', 'tally', 'invalidation']],
    ['proposal-v1', ['proposal', 'revision', 'execution']],
  ]);
});

test('vote schema (GOV16/GOV17): holder charter binds k-of-n threshold and aggregation mode', () => {
  const holder = shape('charter-revision-v1', 'holder-revision');
  const rule = (name: string) => ({ 'rv:mandateRule': [rv(name)] });
  expect(valid(holder, sample(holder, { ...rule('KOfNApproval'), 'rv:approvalThreshold': [2] }))).toBe(true);
  expect(valid(holder, sample(holder, rule('KOfNApproval'), ['rv:approvalThreshold']))).toBe(false);
  expect(valid(holder, sample(holder, { ...rule('KOfNApproval'), 'rv:approvalThreshold': [0] }))).toBe(false);
  expect(valid(holder, sample(holder, rule('DesignatedRepresentative'), ['rv:approvalThreshold']))).toBe(true);
  expect(valid(holder, sample(holder, { ...rule('DesignatedRepresentative'), 'rv:approvalThreshold': [1] })))
    .toBe(false);
  expect(valid(holder, sample(holder, { ...rule('InternalDecision'), 'rv:aggregationMode': [rv('Multiplied')] },
    ['rv:approvalThreshold']))).toBe(false);
});

test('vote schema (GOV15/GOV20/GOV21): electorate charter fixes counting basis, frozen routing and uncast', () => {
  const electorate = shape('charter-revision-v1', 'electorate-revision');
  expect(valid(electorate, sample(electorate, {}))).toBe(true);
  for (const [key, value] of [['rv:proxyRoutingPolicy', 'LiveRerouting'], ['rv:uncastPolicy', 'UncastAsAbstain'],
    ['rv:personCountingBasis', 'NaturalPersonProof'], ['rv:admittedSeatClass', 'ProxySeat']] as const) {
    expect(valid(electorate, sample(electorate, { [key]: [rv(value)] }))).toBe(false);
  }
  expect(valid(electorate, sample(electorate, { 'rv:passDenominator': [0] }))).toBe(false);
});

test('vote schema (GOV13): poll state requires an opening before counting and a resolution when final', () => {
  const poll = shape('poll-snapshot-v1', 'poll');
  const opening = 'https://rezics.com/id/00000000-0000-4000-8000-000000000001';
  const resolution = 'https://rezics.com/id/00000000-0000-4000-8000-000000000002';
  const state = (name: string) => ({ 'rv:pollState': [rv(name)] });
  expect(valid(poll, sample(poll, state('PollDraft'), ['rv:pollOpening', 'rv:pollResolution']))).toBe(true);
  expect(valid(poll, sample(poll, { ...state('PollDraft'), 'rv:pollOpening': [opening] }, ['rv:pollResolution'])))
    .toBe(false);
  expect(valid(poll, sample(poll, state('PollOpen'), ['rv:pollOpening', 'rv:pollResolution']))).toBe(false);
  expect(valid(poll, sample(poll, { ...state('PollOpen'), 'rv:pollOpening': [opening] }, ['rv:pollResolution'])))
    .toBe(true);
  expect(valid(poll, sample(poll, { ...state('PollFinalized'), 'rv:pollOpening': [opening] },
    ['rv:pollResolution']))).toBe(false);
  expect(valid(poll, sample(poll, { ...state('PollFinalized'), 'rv:pollOpening': [opening],
    'rv:pollResolution': [resolution] }))).toBe(true);
});

test('vote schema (GOV12/GOV14/GOV18): ballot revisions conserve bounded units by availability', () => {
  const revision = shape('ballot-v1', 'revision');
  const share = 'https://rezics.com/id/00000000-0000-4000-8000-000000000003';
  const decision = 'https://rezics.com/id/00000000-0000-4000-8000-000000000004';
  const cast = { 'rv:ballotAvailability': [rv('BallotCast')], 'rv:ballotShare': [share], 'rv:countedUnits': [100] };
  expect(valid(revision, sample(revision, cast, ['rv:invalidationDecision']))).toBe(true);
  expect(valid(revision, sample(revision, { ...cast, 'rv:countedUnits': [0] }, ['rv:invalidationDecision'])))
    .toBe(false);
  expect(valid(revision, sample(revision, { ...cast, 'rv:countedUnits': [1000001] },
    ['rv:invalidationDecision']))).toBe(false);
  expect(valid(revision, sample(revision, { 'rv:ballotAvailability': [rv('BallotCast')], 'rv:countedUnits': [40] },
    ['rv:ballotShare', 'rv:invalidationDecision']))).toBe(false);
  const withdrawn = { 'rv:ballotAvailability': [rv('BallotWithdrawn')], 'rv:countedUnits': [0] };
  expect(valid(revision, sample(revision, withdrawn, ['rv:ballotShare', 'rv:invalidationDecision']))).toBe(true);
  expect(valid(revision, sample(revision, { ...withdrawn, 'rv:countedUnits': [60] },
    ['rv:ballotShare', 'rv:invalidationDecision']))).toBe(false);
  const invalidated = { 'rv:ballotAvailability': [rv('BallotInvalidated')], 'rv:countedUnits': [0] };
  expect(valid(revision, sample(revision, invalidated, ['rv:ballotShare', 'rv:invalidationDecision']))).toBe(false);
  expect(valid(revision, sample(revision, { ...invalidated, 'rv:invalidationDecision': [decision] },
    ['rv:ballotShare']))).toBe(true);
});

test('vote schema (GOV19/GOV20): proxy routes are one hop and never redelegable', () => {
  const route = shape('ballot-proxy-v1', 'revision');
  expect(valid(route, sample(route, {}))).toBe(true);
  expect(valid(route, sample(route, { 'rv:proxyHopLimit': [2] }))).toBe(false);
  expect(valid(route, sample(route, { 'rv:redelegation': [rv('RedelegationAllowed')] }))).toBe(false);
  expect(valid(route, sample(route, { 'rv:routeState': [rv('RouteLive')] }))).toBe(false);
});

test('vote schema (GOV21): resolutions separate quorum, outcome and winning option', () => {
  const resolution = shape('poll-resolution-v1', 'resolution');
  const option = 'https://rezics.com/id/00000000-0000-4000-8000-000000000005';
  const outcome = (result: string, quorum: string) =>
    ({ 'rv:resolutionOutcome': [rv(result)], 'rv:quorumOutcome': [rv(quorum)] });
  expect(valid(resolution, sample(resolution, { ...outcome('ResolutionAdopted', 'QuorumMet'),
    'rv:winningOption': [option] }))).toBe(true);
  expect(valid(resolution, sample(resolution, outcome('ResolutionAdopted', 'QuorumMet'), ['rv:winningOption'])))
    .toBe(false);
  expect(valid(resolution, sample(resolution, outcome('ResolutionNoQuorum', 'QuorumMet'), ['rv:winningOption'])))
    .toBe(false);
  expect(valid(resolution, sample(resolution, { ...outcome('ResolutionNoQuorum', 'QuorumNotMet'),
    'rv:winningOption': [option] }))).toBe(false);
});

test('vote schema (GOV23): only an executed proposal names its execution', () => {
  const proposal = shape('proposal-v1', 'proposal');
  const execution = 'https://rezics.com/id/00000000-0000-4000-8000-000000000006';
  const state = (name: string) => ({ 'rv:proposalState': [rv(name)] });
  expect(valid(proposal, sample(proposal, { ...state('ProposalExecuted'), 'rv:proposalExecution': [execution] })))
    .toBe(true);
  expect(valid(proposal, sample(proposal, state('ProposalExecuted'), ['rv:proposalExecution']))).toBe(false);
  expect(valid(proposal, sample(proposal, { ...state('ProposalAdopted'), 'rv:proposalExecution': [execution] })))
    .toBe(false);
  const revision = shape('proposal-v1', 'revision');
  expect(valid(revision, sample(revision, { 'rv:effectDigest': ['not-a-digest'] }))).toBe(false);
});

test('vote schema: Access scope gates derive only from canonical poll and body IRIs', () => {
  const id = '0a1b2c3d-0000-4000-8000-00000000000f';
  expect(pollScopeId(`https://rezics.com/id/${id}`)).toBe(`vote:poll:${id}`);
  expect(governanceBodyScopeId(`https://rezics.com/id/${id}`)).toBe(`governance:body:${id}`);
  for (const bad of [`https://rezics.com/id/${id.toUpperCase()}`, `https://example.org/id/${id}`,
    `https://rezics.com/id/${id}/x`]) {
    expect(() => pollScopeId(bad)).toThrow('canonical');
    expect(() => governanceBodyScopeId(bad)).toThrow('canonical');
  }
});
