import type { PendingSubcase } from './types.ts';

// Prospective combinations of existing IDs. A passing top-level case does not
// qualify these owner-boundary, recovery or workload obligations.
export const pendingProtectionSubcases = [
  { caseIds: ['MODEL18', 'SYS03', 'SYS10'], scenario: 'Edit and protection race at the same content/protection basis',
    requiredResult: 'One wins; the loser cannot confirm the new head. Inspect both receipts and projections.', status: 'pending' },
  { caseIds: ['MODEL23'], scenario: 'Edit expects absent protection while another command creates it',
    requiredResult: 'Guard absence; Content serializes on the existing target row, not an optional row.', status: 'pending' },
  { caseIds: ['MODEL17', 'IAM10', 'LIVE03'], scenario: 'Omit protection/control expectations or forge actor origin',
    requiredResult: 'Reject missing proof; trusted admission determines origin.', status: 'pending' },
  { caseIds: ['LIVE03'], scenario: 'Same-value human confirmation races source application',
    requiredResult: 'Human control advances despite equal bytes; source cannot restore ownership or overwrite, but its observation remains.', status: 'pending' },
  { caseIds: ['LIVE05', 'FACT01'], scenario: 'Two supports share one origin, then one is withdrawn',
    requiredResult: 'No false independence; preserve remaining support and independent native confirmation.', status: 'pending' },
  { caseIds: ['FACT03', 'WORK09'], scenario: 'Evidence or a draft arrives against review-required adoption',
    requiredResult: 'Retain candidate and pending review without changing adoption, protection or official verdict.', status: 'pending' },
  { caseIds: ['MODEL15', 'MODEL16', 'MODEL24'], scenario: 'Change value or remove protection/type/ownership link without advancing its head',
    requiredResult: 'Trusted mutation footprint blocks bypass in projection and raw ingress paths.', status: 'pending' },
  { caseIds: ['MODEL25', 'MODEL26'], scenario: 'Mutate an old revision or retarget its manifest',
    requiredResult: 'Reject even if candidate passes SHACL; same-key receipt replay remains possible.', status: 'pending' },
  { caseIds: ['GOV02', 'GOV23'], scenario: 'Label unrelated write as correction or reuse approval for other candidate/context',
    requiredResult: 'Effect digest, scope, proposal and expected heads reject substitution and extra mutations.', status: 'pending' },
  { caseIds: ['GOV16', 'GOV23', 'IAM10'], scenario: 'Proposer reviews through another Agent or shared controller',
    requiredResult: 'Private control identity blocks self-approval without disclosure in history or errors.', status: 'pending' },
  { caseIds: ['GOV02', 'MODEL22', 'FACT04'], scenario: 'Proposal, evidence, rule, protection or content changes during review',
    requiredResult: 'Decision cannot retarget; retain proposal and require revalidation or report conflict.', status: 'pending' },
  { caseIds: ['GOV03', 'SYS02', 'SYS11', 'SYS14'], scenario: 'Concurrent decisions, lost response and new-key application repeat',
    requiredResult: 'One terminal decision and adopted effect per proposal revision; replay respects current disclosure.', status: 'pending' },
  { caseIds: ['IAM10', 'GOV23', 'WORK05'], scenario: 'Ordinary editor attempts relax, source-control return or generic unseal',
    requiredResult: 'Require separate admission and existing rule; fixed meaning or release has no generic unseal.', status: 'pending' },
  { caseIds: ['LIVE03', 'GOV23'], scenario: 'Reviewer accepts source correction before later source job',
    requiredResult: 'Reviewed application advances human control; separate source return retains protection and adopted value.', status: 'pending' },
  { caseIds: ['IAM07', 'SYS06', 'SYS11'], scenario: 'Reviewer loses authority in flight',
    requiredResult: 'Apply declared revocation fence; unknown result remains pending until original or cancellation receipt.', status: 'pending' },
  { caseIds: ['GOV03', 'MODEL20'], scenario: 'Protect following selection or separate Global and Realm selections',
    requiredResult: 'Pin exact revision or reject dependency profile; preserve other contexts and drafts.', status: 'pending' },
  { caseIds: ['MODEL16', 'MODEL23', 'SYS01'], scenario: 'Resource-wide protection gains child or spans owners',
    requiredResult: 'Guard membership/roots if supported, otherwise reject; cross-owner workflow reports per-owner pending outcomes.', status: 'pending' },
  { caseIds: ['GOV07', 'SYS07', 'OPS10', 'OPS11'], scenario: 'Erase protected payload, then replay source or backup',
    requiredResult: 'Erasure frontier covers copies; exact identity never substitutes bytes or resurrects payload.', status: 'pending' },
  { caseIds: ['OPS03', 'OPS12', 'SYS13'], scenario: 'Restore before protection/correction or lose application receipt',
    requiredResult: 'Hold routing until exact decisions, one-use applications, authority and erasure reconcile; epoch alone is insufficient.', status: 'pending' },
  { caseIds: ['MODEL21', 'OPS04', 'LIVE03'], scenario: 'Activate profile over ambiguous source/control history',
    requiredResult: 'No invented confirmation or source takeover; unsupported old writers fail closed.', status: 'pending' },
  { caseIds: ['FACT03', 'FACT04', 'OPS05', 'OPS06'], scenario: 'Quality recomputation and bounded protection workload',
    requiredResult: 'Summary cannot unlock adoption; test 32/33 dependencies, 50/51 history, hot target, fan-out, engine work and receipts without claiming full-corpus capacity.', status: 'pending' },
] as const satisfies readonly PendingSubcase[];
