import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { classificationContextProfile } from '../definitions/classification-context-v1.ts';
import { classificationDirectDecisionProfile } from '../definitions/classification-direct-decision-v1.ts';
import { classificationPropositionProfile } from '../definitions/classification-proposition-v1.ts';
import { mainDefaultSelectionProfile } from '../definitions/main-default-selection-v1.ts';
import { realmLocalRejectionProfile } from '../definitions/realm-local-rejection-v1.ts';
import { realmLocalSelectionProfile } from '../definitions/realm-local-selection-v1.ts';
import { realmStandingRatingContextProfile } from '../definitions/realm-standing-rating-context-v1.ts';
import { realmStandingRatingObservationProfile } from '../definitions/realm-standing-rating-observation-v1.ts';
import { spaceRealmProfile } from '../definitions/space-realm-v1.ts';
import { textContributionProfile } from '../definitions/text-contribution-v1.ts';
import { textPublicationProfile } from '../definitions/text-publication-v1.ts';
import { workMetadataProfile } from '../definitions/work-metadata-v1.ts';
import { renderProfile, type ProfileDefinition } from './ir.ts';
import { artifactDigests, buildModelOutputs } from './outputs.ts';

export interface ProfileArtifact {
  id: string;
  sha256: string;
  file: string;
  shapes: string[];
  focusRoles: string[];
}

/** Source of truth for the fixed first profiles; generated Turtle bytes retain their reviewed digests. */
export const authoredProfiles: readonly ProfileDefinition[] = [
  classificationContextProfile,
  classificationDirectDecisionProfile,
  classificationPropositionProfile,
  mainDefaultSelectionProfile,
  realmLocalRejectionProfile,
  realmLocalSelectionProfile,
  realmStandingRatingContextProfile,
  realmStandingRatingObservationProfile,
  spaceRealmProfile,
  textContributionProfile,
  textPublicationProfile,
  workMetadataProfile,
];

function profileShapes(source: string, id: string): string[] {
  const shapes = [...source.matchAll(/^<([^>]+)>\s+a\s+sh:NodeShape\s*;/gm)].map(match => match[1]!);
  if (!shapes.length || new Set(shapes).size !== shapes.length) {
    throw new Error(`${id} must declare distinct named NodeShapes`);
  }
  return shapes;
}

export function buildArtifacts(_root: string): Map<string, string> {
  const authored = new Map(authoredProfiles.map(profile => [profile.id, profile]));
  if (!authored.size || authored.size !== authoredProfiles.length) throw new Error('No unique authored profiles');
  const artifacts = new Map<string, string>();
  const profiles: ProfileArtifact[] = [...authored].sort(([a], [b]) => a.localeCompare(b)).map(([id, profile]) => {
    const source = renderProfile(profile);
    const shapeFile = `shapes/${id}.ttl`;
    artifacts.set(`generated/model/${shapeFile}`, source);
    return {
      id,
      sha256: createHash('sha256').update(source).digest('hex'),
      file: shapeFile,
      shapes: profileShapes(source, id),
      focusRoles: profile.shapes.map(shape => {
        const role = shape.iri.split('/').at(-1)?.replace(/-shape$/, '');
        if (!role || !shape.iri.endsWith('-shape')) throw new Error(`${id} has an unnamed focus role`);
        return role;
      }),
    };
  });
  const registry = Object.fromEntries(profiles.map(({ id, sha256, file, shapes, focusRoles }) =>
    [id, { sha256, file, shapes, focusRoles }]));
  artifacts.set('packages/model/src/generated/profiles.ts',
    `// Generated by yarn gen from authored TypeScript profiles.\n` +
    `export const profileRegistry = ${JSON.stringify(registry, null, 2)} as const;\n` +
    `export type ProfileId = keyof typeof profileRegistry;\n`);
  for (const [path, content] of buildModelOutputs(authoredProfiles)) artifacts.set(path, content);
  artifacts.set('generated/model/manifest.json', `${JSON.stringify({
    profiles: profiles.map(({ id, sha256, file }) => ({ id, sha256, file })),
    artifacts: artifactDigests(artifacts),
  }, null, 2)}\n`);
  return artifacts;
}

export function generate(root: string, check: boolean): void {
  const artifacts = buildArtifacts(root);
  for (const [relative, expected] of artifacts) {
    const path = join(root, relative);
    if (check) {
      let actual: string;
      try { actual = readFileSync(path, 'utf8'); }
      catch { throw new Error(`Missing generated artifact: ${relative}`); }
      if (actual !== expected) throw new Error(`Generated artifact differs: ${relative}; run yarn gen`);
    } else {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, expected);
    }
  }
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  if (args.length > 1 || (args.length === 1 && args[0] !== '--check')) {
    throw new Error('usage: yarn gen [--check]');
  }
  generate(resolve(import.meta.dir, '../..'), args[0] === '--check');
}
