import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

export interface ProfileArtifact {
  id: string;
  sha256: string;
  file: string;
  shapes: string[];
}

function profileShapes(source: string, id: string): string[] {
  const shapes = [...source.matchAll(/^<([^>]+)>\s+a\s+sh:NodeShape\s*;/gm)].map(match => match[1]!);
  if (!shapes.length || new Set(shapes).size !== shapes.length) {
    throw new Error(`${id} must declare distinct named NodeShapes`);
  }
  return shapes;
}

export function buildArtifacts(root: string): Map<string, string> {
  const definitions = join(root, 'model/definitions');
  const files = readdirSync(definitions).filter(file => file.endsWith('.ttl')).sort();
  if (!files.length) throw new Error('No model profiles found');
  const artifacts = new Map<string, string>();
  const profiles: ProfileArtifact[] = files.map(file => {
    const id = file.slice(0, -4);
    const source = readFileSync(join(definitions, file), 'utf8');
    const shapeFile = `shapes/${file}`;
    artifacts.set(`generated/model/${shapeFile}`, source);
    return {
      id,
      sha256: createHash('sha256').update(source).digest('hex'),
      file: shapeFile,
      shapes: profileShapes(source, id),
    };
  });
  artifacts.set('generated/model/manifest.json', `${JSON.stringify({
    profiles: profiles.map(({ id, sha256, file }) => ({ id, sha256, file })),
  }, null, 2)}\n`);
  const registry = Object.fromEntries(profiles.map(({ id, sha256, file, shapes }) =>
    [id, { sha256, file, shapes }]));
  artifacts.set('packages/model/src/generated/profiles.ts',
    `// Generated by yarn gen from the reviewed Phase 0 Turtle profiles.\n` +
    `export const profileRegistry = ${JSON.stringify(registry, null, 2)} as const;\n` +
    `export type ProfileId = keyof typeof profileRegistry;\n`);
  return artifacts;
}

export function generate(root: string, check: boolean): void {
  const artifacts = buildArtifacts(root);
  for (const [relative, expected] of artifacts) {
    const path = join(root, relative);
    if (check) {
      let actual: string;
      try { actual = readFileSync(path, 'utf8'); }
      catch { throw new Error(`Missing generated artifact: ${relative}`); }
      if (actual !== expected) throw new Error(`Generated artifact differs: ${relative}; run yarn gen`);
    } else {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, expected);
    }
  }
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  if (args.length > 1 || (args.length === 1 && args[0] !== '--check')) {
    throw new Error('usage: yarn gen [--check]');
  }
  generate(resolve(import.meta.dir, '../..'), args[0] === '--check');
}
