import { createHash } from 'node:crypto';
import { profileSnapshot, reservedNamespaces, type ProfileDefinition, type PropertyDefinition, type Term } from './ir.ts';

const header = '// Generated by task gen from authored profiles. Do not edit.\n';
const quote = (value: unknown): string => JSON.stringify(value);
const digest = (value: string): string => createHash('sha256').update(value).digest('hex');

export function expand(term: Term | string, prefixes: ReadonlyMap<string, string>): string {
  if (term.startsWith('<') && term.endsWith('>')) return term.slice(1, -1);
  if (/^".*"$/.test(term)) return JSON.parse(term) as string;
  if (/^-?\d+$/.test(term)) return term;
  const colon = term.indexOf(':');
  const namespace = prefixes.get(term.slice(0, colon));
  if (colon < 1 || !namespace) throw new Error(`Cannot expand model term ${term}`);
  return `${namespace}${term.slice(colon + 1)}`;
}

function valueKind(property: PropertyDefinition, prefixes: ReadonlyMap<string, string>): 'boolean' | 'integer' | 'dateTime' | 'langString' | 'string' | 'iri' | 'mixed' | 'absent' {
  if (property.maxCount === 0) return 'absent';
  if (property.hasValue && /^-?\d+$/.test(property.hasValue)) return 'integer';
  const datatype = property.datatype && expand(property.datatype, new Map([...Object.entries(reservedNamespaces), ...prefixes]));
  if (datatype === `${reservedNamespaces.xsd}boolean`) return 'boolean';
  if (datatype === `${reservedNamespaces.xsd}integer`) return 'integer';
  if (datatype === `${reservedNamespaces.xsd}dateTime`) return 'dateTime';
  if (datatype === `${reservedNamespaces.rdf}langString`) return 'langString';
  if (datatype === `${reservedNamespaces.xsd}string`) return 'string';
  // RDF term kind, not the presence of an enum, determines JSON-LD coercion.
  const fixed = property.in ?? (property.hasValue ? [property.hasValue] : []);
  if (fixed.length && fixed.every(term => term.startsWith('"'))) return 'string';
  if (fixed.some(term => term.startsWith('"'))) return 'mixed';
  const nodeKind = property.nodeKind && expand(property.nodeKind, new Map([...Object.entries(reservedNamespaces), ...prefixes]));
  if (nodeKind === `${reservedNamespaces.sh}IRIOrLiteral`) return 'mixed';
  if (nodeKind === `${reservedNamespaces.sh}IRI` || property.class || property.in || property.hasValue) return 'iri';
  throw new Error(`No supported JSON value mapping for ${property.path}`);
}

function valueExpression(property: PropertyDefinition, prefixes: ReadonlyMap<string, string>): string {
  const kind = valueKind(property, prefixes);
  if (property.hasValue && property.maxCount === 1) {
    const fixed = kind === 'integer' ? Number(expand(property.hasValue, prefixes)) : expand(property.hasValue, prefixes);
    return `Type.Literal(${quote(fixed)})`;
  }
  const options: Record<string, unknown> = {};
  if (property.minLength !== undefined) options.minLength = property.minLength;
  if (property.maxLength !== undefined) options.maxLength = property.maxLength;
  if (property.pattern !== undefined) options.pattern = property.pattern;
  if (kind === 'integer') {
    if (property.minInclusive !== undefined) options.minimum = property.minInclusive;
    if (property.maxInclusive !== undefined) options.maximum = property.maxInclusive;
    return `Type.Integer(${quote(options)})`;
  }
  if (kind === 'boolean') return 'Type.Boolean()';
  if (kind === 'dateTime') return `Type.String({ pattern: ${quote('^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?(?:Z|[+-]\\d{2}:\\d{2})$')} })`;
  if (kind === 'mixed') return 'Type.Unknown()';
  if (kind === 'langString') {
    const language = property.languageIn?.length
      ? unionLiterals(property.languageIn)
      : `Type.String({ pattern: ${quote('^[a-z]{2,3}(?:-[A-Za-z0-9]{1,8})*$')} })`;
    return `Type.Object({ "@value": Type.String(${quote(options)}), "@language": ${language} }, { additionalProperties: false })`;
  }
  if (property.in) return unionLiterals(property.in.map(term => expand(term, prefixes)));
  return `Type.String(${quote(options)})`;
}

function unionLiterals(values: readonly string[]): string {
  const literals = [...new Set(values)].map(value => `Type.Literal(${quote(value)})`);
  return literals.length === 1 ? literals[0]! : `Type.Union([${literals.join(', ')}])`;
}

function propertyExpression(property: PropertyDefinition, prefixes: ReadonlyMap<string, string>): string {
  if (property.maxCount === 0) return 'Type.Optional(Type.Array(Type.Unknown(), { maxItems: 0 }))';
  const kind = valueKind(property, prefixes);
  const options: string[] = ['uniqueItems: true'];
  if (property.minCount !== undefined) options.push(`minItems: ${property.minCount}`);
  if (property.maxCount !== undefined) options.push(`maxItems: ${property.maxCount}`);
  if (property.hasValue) {
    const fixed = kind === 'integer' ? Number(expand(property.hasValue, prefixes)) : expand(property.hasValue, prefixes);
    if (!Number.isFinite(fixed as number) && kind === 'integer') throw new Error(`Invalid integer value for ${property.path}`);
    options.push(`minItems: ${Math.max(1, property.minCount ?? 0)}`);
    if (property.maxCount !== 1) options.push(`contains: Type.Literal(${quote(fixed)})`);
  }
  if (property.uniqueLang && property.languageIn && property.languageIn.length === 1) options.push('maxItems: 1');
  const deduped = new Map(options.map(option => [option.split(':')[0], option]));
  const base = `Type.Array(${valueExpression(property, prefixes)}, { ${[...deduped.values()].join(', ')} })`;
  // JSON Schema uniqueItems compares complete values; SHACL uniqueLang compares
  // language tags case-insensitively even when the lexical values differ.
  const array = property.uniqueLang && kind === 'langString'
    ? `Type.Refine(${base}, values => new Set(values.map(value => value["@language"].toLowerCase())).size === values.length, () => "Language tags must be unique")`
    : base;
  return property.minCount || property.hasValue ? array : `Type.Optional(${array})`;
}

function objectExpression(properties: readonly PropertyDefinition[], prefixes: ReadonlyMap<string, string>, closed = false): string {
  const grouped = new Map<string, string[]>();
  for (const property of properties) {
    grouped.set(property.path, [...grouped.get(property.path) ?? [], propertyExpression(property, prefixes)]);
  }
  const entries = [...grouped].map(([path, constraints]) =>
    `${quote(path)}: ${constraints.length === 1 ? constraints[0] : `Type.Intersect([${constraints.join(', ')}])`}`);
  return `Type.Object({ "@id": Type.String({ minLength: 1 }), ${entries.join(', ')} }, { additionalProperties: ${!closed} })`;
}

function shapeExpression(shape: ProfileDefinition['shapes'][number], prefixes: ReadonlyMap<string, string>): string {
  const base = objectExpression(shape.properties, prefixes, shape.closed);
  if (!shape.or) return base;
  const branches = shape.or.map(branch => objectExpression(branch, prefixes));
  return `Type.Intersect([${base}, Type.Union([${branches.join(', ')}])])`;
}

function nameFor(iri: string): string {
  return iri.split('/').slice(-2).join('-').split('-').map(part => part.slice(0, 1).toUpperCase() + part.slice(1)).join('');
}

export function buildModelOutputs(profiles: readonly ProfileDefinition[]): Map<string, string> {
  const artifacts = new Map<string, string>();
  const namespaceEntries = new Map<string, string>();
  const iriEntries = new Map<string, string>();
  const schemaLines: string[] = [];
  const registrySchemas: string[] = [];
  for (const authored of profiles) {
    const profile = profileSnapshot(authored);
    const prefixes = new Map(profile.prefixes);
    for (const [name, iri] of prefixes) {
      const old = namespaceEntries.get(name);
      if (old && old !== iri) throw new Error(`Inconsistent namespace ${name}`);
      namespaceEntries.set(name, iri);
    }
    const paths = [...new Set(profile.shapes.flatMap(shape => [
      ...shape.properties.map(property => property.path),
      ...(shape.or ?? []).flatMap(branch => branch.map(property => property.path)),
    ]))].sort();
    const context: Record<string, unknown> = {};
    for (const [prefix, iri] of prefixes) context[prefix] = { '@id': iri, '@prefix': true };
    for (const path of paths) {
      const properties = profile.shapes.flatMap(shape => [
        ...shape.properties, ...(shape.or ?? []).flat(),
      ]).filter(property => property.path === path);
      const kinds = new Set(properties.map(property => valueKind(property, prefixes)));
      const mapping: Record<string, string> = { '@id': expand(path, prefixes) };
      if ([...kinds].every(kind => kind === 'iri')) mapping['@type'] = '@id';
      if ([...kinds].every(kind => kind === 'integer')) mapping['@type'] = 'xsd:integer';
      if ([...kinds].every(kind => kind === 'boolean')) mapping['@type'] = `${reservedNamespaces.xsd}boolean`;
      if ([...kinds].every(kind => kind === 'dateTime')) mapping['@type'] = 'xsd:dateTime';
      context[path] = mapping;
      iriEntries.set(path, expand(path, prefixes));
      for (const property of properties) {
        for (const term of [property.class, property.hasValue, ...(property.in ?? [])]) {
          if (term && !/^-?\d+$/.test(term) && !term.startsWith('"')) iriEntries.set(term, expand(term, prefixes));
        }
      }
    }
    const contextFile = `generated/model/contexts/${profile.id}.jsonld`;
    artifacts.set(contextFile, `${JSON.stringify({ '@context': context }, null, 2)}\n`);
    for (const shape of profile.shapes) {
      const name = nameFor(shape.iri);
      schemaLines.push(`export const ${name}Schema = ${shapeExpression(shape, prefixes)};`);
      schemaLines.push(`export type ${name} = Static<typeof ${name}Schema>;`);
      registrySchemas.push(`${quote(shape.iri)}: ${name}Schema`);
    }
  }
  const namespaces = Object.fromEntries([...namespaceEntries].sort(([a], [b]) => a.localeCompare(b)));
  const iris = Object.fromEntries([...iriEntries].sort(([a], [b]) => a.localeCompare(b)));
  artifacts.set('packages/model/src/generated/vocabulary.ts', `${header}export const namespaces = ${JSON.stringify(namespaces, null, 2)} as const;\nexport const iri = ${JSON.stringify(iris, null, 2)} as const;\n`);
  artifacts.set('packages/model/src/generated/schemas.ts', `${header}import { Type, type Static } from 'typebox';\n\n/** Node-local JSON-LD value envelopes. Jena performs graph-wide SHACL validation. */\n${schemaLines.join('\n\n')}\n\nexport const shapeSchemas = {\n  ${registrySchemas.join(',\n  ')}\n} as const;\n`);
  return artifacts;
}

export function artifactDigests(artifacts: ReadonlyMap<string, string>): Record<string, string> {
  return Object.fromEntries([...artifacts].sort(([a], [b]) => a.localeCompare(b))
    .map(([path, content]) => [path.replace(/^generated\/model\//, ''), digest(content)]));
}
