import { createHash } from 'node:crypto';
import type { ProfileDefinition, PropertyDefinition, Term } from './ir.ts';

const header = '// Generated by yarn gen from authored TypeScript profiles. Do not edit.\n';
const quote = (value: unknown): string => JSON.stringify(value);
const digest = (value: string): string => createHash('sha256').update(value).digest('hex');

function expand(term: Term | string, prefixes: ReadonlyMap<string, string>): string {
  if (term.startsWith('<') && term.endsWith('>')) return term.slice(1, -1);
  if (/^".*"$/.test(term)) return JSON.parse(term) as string;
  if (/^-?\d+$/.test(term)) return term;
  const colon = term.indexOf(':');
  const namespace = prefixes.get(term.slice(0, colon));
  if (colon < 1 || !namespace) throw new Error(`Cannot expand model term ${term}`);
  return `${namespace}${term.slice(colon + 1)}`;
}

function valueKind(property: PropertyDefinition): 'integer' | 'dateTime' | 'langString' | 'string' | 'iri' | 'absent' {
  if (property.maxCount === 0) return 'absent';
  if (property.hasValue && /^-?\d+$/.test(property.hasValue)) return 'integer';
  if (property.datatype === 'xsd:integer') return 'integer';
  if (property.datatype === 'xsd:dateTime') return 'dateTime';
  if (property.datatype === 'rdf:langString') return 'langString';
  if (property.datatype === 'xsd:string') return 'string';
  if (property.nodeKind === 'sh:IRI' || property.class || property.in || property.hasValue) return 'iri';
  throw new Error(`No supported JSON value mapping for ${property.path}`);
}

function valueExpression(property: PropertyDefinition, prefixes: ReadonlyMap<string, string>): string {
  const kind = valueKind(property);
  if (property.hasValue && property.maxCount === 1) {
    const fixed = kind === 'integer' ? Number(expand(property.hasValue, prefixes)) : expand(property.hasValue, prefixes);
    return `Type.Literal(${quote(fixed)})`;
  }
  const options: Record<string, unknown> = {};
  if (property.minLength !== undefined) options.minLength = property.minLength;
  if (property.maxLength !== undefined) options.maxLength = property.maxLength;
  if (property.pattern !== undefined) options.pattern = property.pattern;
  if (kind === 'integer') {
    if (property.minInclusive !== undefined) options.minimum = property.minInclusive;
    if (property.maxInclusive !== undefined) options.maximum = property.maxInclusive;
    return `Type.Integer(${quote(options)})`;
  }
  if (kind === 'dateTime') return `Type.String({ pattern: ${quote('^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?(?:Z|[+-]\\d{2}:\\d{2})$')} })`;
  if (kind === 'langString') {
    const language = property.languageIn?.length
      ? unionLiterals(property.languageIn)
      : `Type.String({ pattern: ${quote('^[a-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$')} })`;
    return `Type.Object({ "@value": Type.String(${quote(options)}), "@language": ${language} }, { additionalProperties: false })`;
  }
  if (property.in) return unionLiterals(property.in.map(term => expand(term, prefixes)));
  return `Type.String(${quote(options)})`;
}

function unionLiterals(values: readonly string[]): string {
  const literals = [...new Set(values)].map(value => `Type.Literal(${quote(value)})`);
  return literals.length === 1 ? literals[0]! : `Type.Union([${literals.join(', ')}])`;
}

function propertyExpression(property: PropertyDefinition, prefixes: ReadonlyMap<string, string>): string {
  if (property.maxCount === 0) return 'Type.Optional(Type.Array(Type.Unknown(), { maxItems: 0 }))';
  if (property.uniqueLang && property.languageIn && property.languageIn.length > 1) {
    throw new Error(`Cannot emit exact uniqueLang schema for ${property.path}`);
  }
  const kind = valueKind(property);
  const options: string[] = [];
  if (property.minCount !== undefined) options.push(`minItems: ${property.minCount}`);
  if (property.maxCount !== undefined) options.push(`maxItems: ${property.maxCount}`);
  if (property.hasValue) {
    const fixed = kind === 'integer' ? Number(expand(property.hasValue, prefixes)) : expand(property.hasValue, prefixes);
    if (!Number.isFinite(fixed as number) && kind === 'integer') throw new Error(`Invalid integer value for ${property.path}`);
    options.push('minItems: 1');
    if (property.maxCount !== 1) options.push(`contains: Type.Literal(${quote(fixed)})`);
  }
  if (property.uniqueLang && property.languageIn && property.languageIn.length === 1) options.push('maxItems: 1');
  const deduped = new Map(options.map(option => [option.split(':')[0], option]));
  const array = `Type.Array(${valueExpression(property, prefixes)}, { ${[...deduped.values()].join(', ')} })`;
  return property.minCount || property.hasValue ? array : `Type.Optional(${array})`;
}

function objectExpression(properties: readonly PropertyDefinition[], prefixes: ReadonlyMap<string, string>): string {
  const entries = properties.map(property => `${quote(property.path)}: ${propertyExpression(property, prefixes)}`);
  return `Type.Object({ "@id": Type.String({ minLength: 1 }), ${entries.join(', ')} }, { additionalProperties: true })`;
}

function shapeExpression(shape: ProfileDefinition['shapes'][number], prefixes: ReadonlyMap<string, string>): string {
  const base = objectExpression(shape.properties, prefixes);
  if (!shape.or) return base;
  const branches = shape.or.map(branch => objectExpression(branch, prefixes));
  return `Type.Intersect([${base}, Type.Union([${branches.join(', ')}])])`;
}

function nameFor(iri: string): string {
  return iri.split('/').slice(-2).join('-').split('-').map(part => part.slice(0, 1).toUpperCase() + part.slice(1)).join('');
}

function arbitraryValue(property: PropertyDefinition, prefixes: ReadonlyMap<string, string>): string {
  const kind = valueKind(property);
  if (property.hasValue) return `fc.constant(${quote(kind === 'integer' ? Number(expand(property.hasValue, prefixes)) : expand(property.hasValue, prefixes))})`;
  if (property.in) return `fc.constantFrom(${property.in.map(term => quote(expand(term, prefixes))).join(', ')})`;
  if (kind === 'integer') return `fc.integer({ min: ${property.minInclusive ?? 0}, max: ${property.maxInclusive ?? 100} })`;
  if (kind === 'dateTime') return `fc.integer({ min: 0, max: 4102444800000 }).map(value => new Date(value).toISOString())`;
  if (kind === 'langString') {
    if (!property.languageIn?.length) {
      return `fc.constant({ "@value": "sample", "@language": "en" })`;
    }
    return `fc.record({ "@value": fc.string({ minLength: ${property.minLength ?? 1}, maxLength: ${property.maxLength ?? 20} }), "@language": fc.constantFrom(${property.languageIn.map(quote).join(', ')}) })`;
  }
  if (property.pattern) {
    const examples: Record<string, string> = {
      '^[a-z]{2,3}(-[A-Za-z0-9]{2,8})*$': 'en',
      '^[A-Za-z]{2,8}(-[A-Za-z0-9]{1,8})*$': 'en-US',
      '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$':
        '00000000-0000-4000-8000-000000000001',
      '^(0|[1-9][0-9]*)$': '1',
      '^https://[^\\s<>"{}|\\^`]{1,2040}$': 'https://publisher.example/translation',
      '^[0-9a-f]{64}$': 'a'.repeat(64),
      '^OL[1-9][0-9]{0,11}W$': 'OL1W',
      '^/works/OL[1-9][0-9]{0,11}W$': '/works/OL1W',
      '^[a-z0-9]+(-[a-z0-9]+)*$': 'sample-work',
      '^urn:rezics:operation:[0-9a-f]{64}$': `urn:rezics:operation:${'a'.repeat(64)}`,
      '^urn:rezics:content:revision:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$':
        'urn:rezics:content:revision:00000000-0000-4000-8000-000000000001',
    };
    const example = examples[property.pattern];
    if (!example) throw new Error(`No arbitrary for pattern ${property.pattern}`);
    return `fc.constant(${quote(example)})`;
  }
  if (kind === 'iri') return `fc.integer({ min: 0, max: 1000000 }).map(value => ${quote(`urn:rezics:sample:${property.path}:`)} + value)`;
  return `fc.string({ minLength: ${property.minLength ?? 1}, maxLength: ${property.maxLength ?? 20} })`;
}

function arbitraryProperties(properties: readonly PropertyDefinition[], prefixes: ReadonlyMap<string, string>): string[] {
  return properties.filter(property => property.maxCount !== 0 && (property.minCount || property.hasValue))
    .map(property => {
      if (property.minCount && property.minCount > 1 && property.in
        && property.in.length === property.minCount && property.maxCount === property.minCount) {
        return `${quote(property.path)}: fc.constant(${quote(property.in.map(term => expand(term, prefixes)))})`;
      }
      return `${quote(property.path)}: ${arbitraryValue(property, prefixes)}.map(value => [value])`;
    });
}

function arbitraryExpression(shape: ProfileDefinition['shapes'][number], prefixes: ReadonlyMap<string, string>): string {
  const base = arbitraryProperties(shape.properties, prefixes);
  const id = `"@id": fc.integer({ min: 0, max: 1000000 }).map(value => ${quote(`urn:rezics:sample:${nameFor(shape.iri)}:`)} + value)`;
  if (!shape.or) return `fc.record({ ${[id, ...base].join(', ')} })`;
  const branches = shape.or.map(branch => {
    const overrides = new Map(base.map(entry => [entry.split(': ')[0], entry]));
    for (const property of branch) {
      if (property.maxCount === 0) {
        overrides.delete(quote(property.path));
        continue;
      }
      const baseProperty = shape.properties.find(candidate => candidate.path === property.path);
      const merged = baseProperty ? { ...baseProperty, ...property } : property;
      const entry = arbitraryProperties([merged], prefixes)[0];
      if (entry) overrides.set(quote(property.path), entry);
    }
    return `fc.record({ ${[id, ...overrides.values()].join(', ')} })`;
  });
  return `fc.oneof(${branches.join(', ')})`;
}

export function buildModelOutputs(profiles: readonly ProfileDefinition[]): Map<string, string> {
  const artifacts = new Map<string, string>();
  const namespaceEntries = new Map<string, string>();
  const iriEntries = new Map<string, string>();
  const schemaLines: string[] = [];
  const arbitraryLines: string[] = [];
  const registrySchemas: string[] = [];
  const registryArbitraries: string[] = [];
  for (const profile of profiles) {
    const prefixes = new Map(profile.prefixes);
    for (const [name, iri] of prefixes) {
      const old = namespaceEntries.get(name);
      if (old && old !== iri) throw new Error(`Inconsistent namespace ${name}`);
      namespaceEntries.set(name, iri);
    }
    const paths = [...new Set(profile.shapes.flatMap(shape => [
      ...shape.properties.map(property => property.path),
      ...(shape.or ?? []).flatMap(branch => branch.map(property => property.path)),
    ]))].sort();
    const context: Record<string, unknown> = {};
    for (const [prefix, iri] of prefixes) context[prefix] = { '@id': iri, '@prefix': true };
    for (const path of paths) {
      const properties = profile.shapes.flatMap(shape => [
        ...shape.properties, ...(shape.or ?? []).flat(),
      ]).filter(property => property.path === path);
      const kinds = new Set(properties.map(valueKind));
      const mapping: Record<string, string> = { '@id': expand(path, prefixes) };
      if ([...kinds].every(kind => kind === 'iri')) mapping['@type'] = '@id';
      if ([...kinds].every(kind => kind === 'integer')) mapping['@type'] = 'xsd:integer';
      if ([...kinds].every(kind => kind === 'dateTime')) mapping['@type'] = 'xsd:dateTime';
      context[path] = mapping;
      iriEntries.set(path, expand(path, prefixes));
      for (const property of properties) {
        for (const term of [property.class, property.hasValue, ...(property.in ?? [])]) {
          if (term && !/^-?\d+$/.test(term)) iriEntries.set(term, expand(term, prefixes));
        }
      }
    }
    const contextFile = `generated/model/contexts/${profile.id}.jsonld`;
    artifacts.set(contextFile, `${JSON.stringify({ '@context': context }, null, 2)}\n`);
    for (const shape of profile.shapes) {
      const name = nameFor(shape.iri);
      schemaLines.push(`export const ${name}Schema = ${shapeExpression(shape, prefixes)};`);
      schemaLines.push(`export type ${name} = Static<typeof ${name}Schema>;`);
      arbitraryLines.push(`export const ${name}Arbitrary = ${arbitraryExpression(shape, prefixes)};`);
      registrySchemas.push(`${quote(shape.iri)}: ${name}Schema`);
      registryArbitraries.push(`${quote(shape.iri)}: ${name}Arbitrary`);
    }
  }
  const namespaces = Object.fromEntries([...namespaceEntries].sort(([a], [b]) => a.localeCompare(b)));
  const iris = Object.fromEntries([...iriEntries].sort(([a], [b]) => a.localeCompare(b)));
  artifacts.set('packages/model/src/generated/vocabulary.ts', `${header}export const namespaces = ${JSON.stringify(namespaces, null, 2)} as const;\nexport const iri = ${JSON.stringify(iris, null, 2)} as const;\n`);
  artifacts.set('packages/model/src/generated/schemas.ts', `${header}import { Type, type Static } from 'typebox';\n\n/** Node-local JSON-LD value envelopes. Jena performs graph-wide SHACL validation. */\n${schemaLines.join('\n\n')}\n\nexport const shapeSchemas = {\n  ${registrySchemas.join(',\n  ')}\n} as const;\n`);
  artifacts.set('packages/model/src/generated/arbitraries.ts', `${header}import * as fc from 'fast-check';\n\n/** Valid node-local candidates; linked-node/class validity must be established in Jena. */\n${arbitraryLines.join('\n\n')}\n\nexport const shapeArbitraries = {\n  ${registryArbitraries.join(',\n  ')}\n} as const;\n`);
  return artifacts;
}

export function artifactDigests(artifacts: ReadonlyMap<string, string>): Record<string, string> {
  return Object.fromEntries([...artifacts].sort(([a], [b]) => a.localeCompare(b))
    .map(([path, content]) => [path.replace(/^generated\/model\//, ''), digest(content)]));
}
