// Renders each workspace's committed .env.example from its envalid specs, so
// the documented variables cannot drift from the code. `--check` fails on drift.
import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { mainSpec, relayInitSpec, relaySpec } from '../../services/main/src/config.ts';
import { accountSpec } from '../../services/account/src/config.ts';
import { webSpec } from '../../apps/web/features/config/env.ts';

interface Spec { desc?: string; example?: string; default?: unknown }
interface Section { title: string; spec: Record<string, Spec> }

const root = resolve(import.meta.dir, '../..');
const header = (source: string) => [
  `# Generated by task env:example from ${source}. Do not edit.`,
  '# task dev:prepare writes the local values, including generated secrets, to',
  '# .temp/stack/<project>/dev.env (see `task env`). Put personal overrides in the',
  '# repository-root .env.dev; see .env.dev.example.',
];

function render(source: string, sections: Section[]): string {
  const lines = header(source);
  const seen = new Set<string>();
  for (const { title, spec } of sections) {
    const entries = Object.entries(spec).filter(([name]) => !seen.has(name));
    if (!entries.length) continue;
    lines.push('', `## ${title}`);
    for (const [name, item] of entries) {
      seen.add(name);
      const optional = 'default' in item;
      const note = optional
        ? item.default === undefined ? ' (optional)' : ` (default: ${String(item.default)})`
        : '';
      lines.push(`# ${item.desc ?? name}${note}`);
      const value = item.example ?? (optional && item.default !== undefined ? String(item.default) : '');
      lines.push(`${optional ? '# ' : ''}${name}=${value}`);
    }
  }
  return `${lines.join('\n')}\n`;
}

const files: Record<string, string> = {
  'services/main/.env.example': render('services/main/src/config.ts', [
    { title: 'Main API (src/index.ts)', spec: mainSpec },
    { title: 'Main relay (src/relay.ts, src/relay-init.ts)', spec: { ...relaySpec, ...relayInitSpec } },
  ]),
  'services/account/.env.example': render('services/account/src/config.ts', [
    { title: 'Account (src/index.ts, src/migrate.ts)', spec: accountSpec },
  ]),
  'apps/web/.env.example': render('apps/web/features/config/env.ts', [
    { title: 'Web Worker', spec: webSpec },
  ]),
};

const check = process.argv.includes('--check');
const stale: string[] = [];
for (const [path, content] of Object.entries(files)) {
  const file = join(root, path);
  let current = '';
  try { current = readFileSync(file, 'utf8'); } catch { /* not generated yet */ }
  if (current === content) continue;
  if (check) stale.push(path);
  else writeFileSync(file, content);
}
if (stale.length) {
  console.error(`Stale .env.example: ${stale.join(', ')}; run task env:example`);
  process.exit(1);
}
