import type { OwnerColumns } from './owner-columns.ts';

/** Access database `commerce` schema from migration 090. Entitlements here are
 * benefit grants, never Access permission grants. */
export const commerceSchema = 'commerce';

export const commerceColumns = {
  payment_provider: { id: 'text', kind: 'text', callback_key_reference: 'text', enabled: 'bool' },
  offering: { id: 'uuid', seller: 'text', beneficiary_kind: 'text', head_revision: 'int8',
    created_at: 'timestamptz' },
  offering_revision: { offering_id: 'uuid', revision: 'int8', lifecycle: 'text',
    definition_digest: 'text', created_at: 'timestamptz' },
  plan_group: { offering_id: 'uuid', group_key: 'text', semantics: 'text' },
  plan: { offering_id: 'uuid', offering_revision: 'int8', plan_key: 'text', group_key: 'text',
    rank: 'int4' },
  price: { offering_id: 'uuid', offering_revision: 'int8', plan_key: 'text', price_key: 'text',
    currency: 'text', amount_minor: 'int8', billing_period: 'text' },
  plan_benefit: { offering_id: 'uuid', offering_revision: 'int8', plan_key: 'text',
    benefit_key: 'text', level: 'int4', quota_unit: 'text?', quota_amount: 'int8?' },
  subscription: { id: 'uuid', principal_id: 'uuid', beneficiary: 'text', offering_id: 'uuid',
    group_key: 'text', group_semantics: 'text', offering_revision: 'int8', plan_key: 'text',
    price_key: 'text', state: 'text', generation: 'int8', provider: 'text',
    provider_reference: 'text?', current_period_end: 'timestamptz?', created_at: 'timestamptz' },
  quote: { id: 'uuid', principal_id: 'uuid', beneficiary: 'text', operation: 'text',
    subscription_id: 'uuid?', expected_subscription_generation: 'int8?', offering_id: 'uuid',
    offering_revision: 'int8', plan_key: 'text?', price_key: 'text?', amount_minor: 'int8',
    currency: 'text', eligibility: 'jsonb', quote_digest: 'text', expires_at: 'timestamptz',
    created_at: 'timestamptz' },
  subscription_change: { id: 'uuid', subscription_id: 'uuid', quote_id: 'uuid', operation: 'text',
    base_generation: 'int8', result_generation: 'int8', principal_id: 'uuid',
    idempotency_key: 'text', created_at: 'timestamptz' },
  receipt: { principal_id: 'uuid', idempotency_key: 'text', request_digest: 'text',
    operation: 'text', result: 'jsonb', created_at: 'timestamptz' },
  settlement: { id: 'uuid', change_id: 'uuid', provider: 'text', provider_reference: 'text',
    amount_minor: 'int8', currency: 'text', state: 'text', generation: 'int8',
    created_at: 'timestamptz' },
  provider_callback: { provider: 'text', provider_event_id: 'text', provider_reference: 'text',
    event_kind: 'text', payload_digest: 'text', disposition: 'text', settlement_id: 'uuid?',
    settlement_generation: 'int8?', received_at: 'timestamptz' },
  reconciliation: { id: 'uuid', operation_id: 'text', settlement_id: 'uuid',
    base_generation: 'int8', observed: 'text', observation_digest: 'text', outcome: 'text',
    settlement_generation: 'int8?', created_at: 'timestamptz' },
  settlement_event: { settlement_id: 'uuid', generation: 'int8', state: 'text', source: 'text',
    callback_provider: 'text?', callback_event_id: 'text?', reconciliation_id: 'uuid?',
    created_at: 'timestamptz' },
  entitlement: { id: 'uuid', beneficiary: 'text', source: 'text', offering_id: 'uuid',
    offering_revision: 'int8', plan_key: 'text', subscription_id: 'uuid?', award_issuer: 'text?',
    award_reason: 'text?', replaces: 'uuid?', valid_from: 'timestamptz',
    valid_until: 'timestamptz', state: 'text', generation: 'int8', created_at: 'timestamptz' },
  entitlement_event: { entitlement_id: 'uuid', generation: 'int8', action: 'text', state: 'text',
    valid_until: 'timestamptz', change_id: 'uuid?', settlement_id: 'uuid?',
    reason_reference: 'text?', created_at: 'timestamptz' },
  benefit_epoch: { beneficiary: 'text', epoch: 'int8' },
} as const satisfies OwnerColumns;
