// The franchise wiki Zone's own words. Packages bring their strings; the platform passes the interface locale in
// `zone.locale`, and any other locale reads English. What things are called (a character, a chapter) comes from the
// type registry and from the story's own labels, never from here.

const en = {
  creditedAs: "as",
  nameNotShown: 'Name not shown',
  atPosition: (label: string) => `Showing what is revealed up to ${label}.`,
  atAnyPosition: 'Showing what is revealed at your position.',
  atEverything: 'Includes records from chapters you may not have read.',
  showEverything: 'Show everything',
  worksHeading: 'Works',
  characters: 'Main characters',
  places: 'Places',
  chapters: 'Chapter guide',
  events: 'Timeline',
  seeAll: 'See all',
  more: 'More pages continue on the full list.',
  nothingHere: 'Nothing is revealed here yet at your position.',
  emptyTitle: 'This wiki has no pages yet',
  emptyWithWorks: 'It covers the Works above, but no characters, places, events or chapters have been published yet.',
  emptyNoWorks: 'No Work is part of this wiki yet.',
  buildIt: 'Holders build a wiki with the REZICS wiki toolkit: it turns their own copy of the book into a bundle of names, relationships and short quotations with exact locations, and a steward reviews it before anything is published.',
  howRun: 'How this wiki is run',
  youngTitle: 'This wiki is just beginning',
  youngBody: 'What exists so far is listed here. More appears as holders submit chapters and stewards publish them.',
  alsoKnownAs: 'Also known as',
  atAGlance: 'At a glance',
  relationships: 'Relationships',
  relationship: 'Relationship',
  firstAppears: 'First appears in',
  passages: 'Passages and sources',
  source: 'Source',
  sourceEdition: (type: string) => `${type} edition`,
  sourceAgent: (agent: string) => `extracted by ${agent}`,
  modality: { narrated: 'Narrated', said: 'Said by a character', rumoured: 'Rumoured', hypothetical: 'Hypothetical' } as Record<string, string>,
  rights: { public_domain: 'public domain', original_contribution: 'original contribution', unprotected_fact: 'unprotected fact',
    license: 'licensed', permission: 'by permission', statutory_exception: 'statutory exception',
    service_terms: 'under service terms', unknown: 'rights not established' } as Record<string, string>,
  withheld: 'The quotation is withheld by a rights restriction. Its source is still recorded.',
  moreOnFull: 'This record holds more than is listed here.',
  openFull: 'Open the full record',
  revealedHere: 'Revealed in this chapter',
  nothingNew: 'No new pages are listed for this chapter.',
  notReached: 'This chapter is beyond your reading position, so what it reveals stays hidden.',
  incomplete: 'This list may be incomplete.',
  previous: 'Previous chapter',
  next: 'Next chapter',
  chapterNav: 'Chapters',
  back: (name: string) => `All of ${name}`,
  kind: 'Kind',
};

type Strings = typeof en;
type ZoneLocale = 'en' | 'zh-Hans' | 'zh-Hant' | 'ja' | 'ko' | 'de' | 'fr' | 'es';
const zoneLocales = ['en', 'zh-Hans', 'zh-Hant', 'ja', 'ko', 'de', 'fr', 'es'] as const satisfies readonly ZoneLocale[];

const translations: Record<ZoneLocale, Strings> = {
  en,
  'zh-Hans': {
    creditedAs: '署名为',
    nameNotShown: '未显示名字',
    atPosition: (label: string) => `正在显示截至「${label}」已揭示的内容。`,
    atAnyPosition: '正在显示你当前位置已揭示的内容。',
    atEverything: '包含你可能还没读到的章节中的记录。',
    showEverything: '显示全部',
    worksHeading: '作品', characters: '主要角色', places: '地点', chapters: '章节导览', events: '时间线',
    seeAll: '查看全部',
    more: '更多页面见完整列表。',
    nothingHere: '在你当前的位置，这里还没有揭示任何内容。',
    emptyTitle: '这个维基还没有页面',
    emptyWithWorks: '它涵盖上面列出的作品，但角色、地点、事件和章节都还没有发布。',
    emptyNoWorks: '还没有作品属于这个维基。',
    buildIt: '持有者用 REZICS 维基工具包建设维基：它把自己手上的书整理成人名、关系和带精确位置的简短引文，由管理员审核后才会发布。',
    howRun: '这个维基如何运作',
    youngTitle: '这个维基刚刚起步',
    youngBody: '目前已有的内容列在这里。随着持有者提交章节、管理员发布，内容会不断增加。',
    alsoKnownAs: '又名', atAGlance: '概览', relationships: '关系', relationship: '关系', firstAppears: '首次出现于',
    passages: '段落与出处', source: '出处',
    sourceEdition: (type: string) => `${type} 版本`,
    sourceAgent: (agent: string) => `由 ${agent} 提取`,
    modality: { narrated: '叙述', said: '角色所说', rumoured: '传闻', hypothetical: '假设' },
    rights: { public_domain: '公有领域', original_contribution: '原创贡献', unprotected_fact: '不受保护的事实', license: '已获许可',
      permission: '经许可', statutory_exception: '法定例外', service_terms: '依服务条款', unknown: '权利状态未确定' },
    withheld: '该引文因权利限制而不显示，其出处仍有记录。',
    moreOnFull: '这条记录的内容多于此处所列。', openFull: '打开完整记录',
    revealedHere: '本章揭示的内容', nothingNew: '这一章没有列出新的页面。',
    notReached: '这一章超出了你的阅读位置，所以它揭示的内容保持隐藏。',
    incomplete: '此列表可能不完整。', previous: '上一章', next: '下一章', chapterNav: '章节',
    back: (name: string) => `全部${name}`, kind: '类型',
  },
  'zh-Hant': {
    creditedAs: '署名為',
    nameNotShown: '未顯示名字',
    atPosition: (label: string) => `正在顯示截至「${label}」已揭示的內容。`,
    atAnyPosition: '正在顯示你目前位置已揭示的內容。',
    atEverything: '包含你可能還沒讀到的章節中的記錄。',
    showEverything: '顯示全部',
    worksHeading: '作品', characters: '主要角色', places: '地點', chapters: '章節導覽', events: '時間線',
    seeAll: '查看全部',
    more: '更多頁面見完整清單。',
    nothingHere: '在你目前的位置，這裡還沒有揭示任何內容。',
    emptyTitle: '這個維基還沒有頁面',
    emptyWithWorks: '它涵蓋上面列出的作品，但角色、地點、事件和章節都還沒有發布。',
    emptyNoWorks: '還沒有作品屬於這個維基。',
    buildIt: '持有者用 REZICS 維基工具包建設維基：它把自己手上的書整理成人名、關係和帶精確位置的簡短引文，由管理員審核後才會發布。',
    howRun: '這個維基如何運作',
    youngTitle: '這個維基才剛起步',
    youngBody: '目前已有的內容列在這裡。隨著持有者提交章節、管理員發布，內容會不斷增加。',
    alsoKnownAs: '又名', atAGlance: '概覽', relationships: '關係', relationship: '關係', firstAppears: '首次出現於',
    passages: '段落與出處', source: '出處',
    sourceEdition: (type: string) => `${type} 版本`,
    sourceAgent: (agent: string) => `由 ${agent} 擷取`,
    modality: { narrated: '敘述', said: '角色所說', rumoured: '傳聞', hypothetical: '假設' },
    rights: { public_domain: '公有領域', original_contribution: '原創貢獻', unprotected_fact: '不受保護的事實', license: '已獲授權',
      permission: '經許可', statutory_exception: '法定例外', service_terms: '依服務條款', unknown: '權利狀態未確定' },
    withheld: '該引文因權利限制而不顯示，其出處仍有記錄。',
    moreOnFull: '這筆記錄的內容多於此處所列。', openFull: '開啟完整記錄',
    revealedHere: '本章揭示的內容', nothingNew: '這一章沒有列出新的頁面。',
    notReached: '這一章超出了你的閱讀位置，所以它揭示的內容保持隱藏。',
    incomplete: '此清單可能不完整。', previous: '上一章', next: '下一章', chapterNav: '章節',
    back: (name: string) => `全部${name}`, kind: '類型',
  },
  ja: {
    creditedAs: "役名：",
    nameNotShown: '名前は表示されていません',
    atPosition: (label: string) => `「${label}」までに明かされた内容を表示しています。`,
    atAnyPosition: '現在の位置で明かされている内容を表示しています。',
    atEverything: 'まだ読んでいない章の記録も含まれています。',
    showEverything: 'すべて表示',
    worksHeading: '作品', characters: '主要人物', places: '場所', chapters: '章ガイド', events: '年表',
    seeAll: 'すべて見る',
    more: '続きは一覧ページにあります。',
    nothingHere: '現在の位置では、まだここに明かされた内容がありません。',
    emptyTitle: 'このウィキにはまだページがありません',
    emptyWithWorks: '上の作品を対象としていますが、人物・場所・出来事・章はまだ公開されていません。',
    emptyNoWorks: 'このウィキに属する作品はまだありません。',
    buildIt: '保有者は REZICS ウィキツールキットでウィキを作ります。手元の本から、名前・関係・正確な位置つきの短い引用をまとめたバンドルを作り、公開前に管理者が確認します。',
    howRun: 'このウィキの運営について',
    youngTitle: 'このウィキは始まったばかりです',
    youngBody: 'ここまでにあるものを一覧にしています。保有者が章を提出し、管理者が公開するたびに増えていきます。',
    alsoKnownAs: '別名', atAGlance: '概要', relationships: '関係', relationship: '関係', firstAppears: '初登場',
    passages: '引用と出典', source: '出典',
    sourceEdition: (type: string) => `${type} 版`,
    sourceAgent: (agent: string) => `${agent} が抽出`,
    modality: { narrated: '地の文', said: '登場人物の発言', rumoured: '噂', hypothetical: '仮定' },
    rights: { public_domain: 'パブリックドメイン', original_contribution: '独自の寄稿', unprotected_fact: '保護されない事実', license: 'ライセンスあり',
      permission: '許諾あり', statutory_exception: '法定の例外', service_terms: 'サービス規約による', unknown: '権利関係は未確認' },
    withheld: '権利上の制限により引用は表示されません。出典は記録されています。',
    moreOnFull: 'この記録には、ここに載せきれない内容があります。', openFull: '記録の全体を開く',
    revealedHere: 'この章で明かされること', nothingNew: 'この章で新しく載るページはありません。',
    notReached: 'この章は現在の読み進めた位置より先にあるため、明かされる内容は表示されません。',
    incomplete: 'この一覧は不完全かもしれません。', previous: '前の章', next: '次の章', chapterNav: '章',
    back: (name: string) => `${name}の一覧`, kind: '種類',
  },
  ko: {
    creditedAs: "배역명:",
    nameNotShown: '이름이 표시되지 않음',
    atPosition: (label: string) => `「${label}」까지 밝혀진 내용을 보여 주고 있습니다.`,
    atAnyPosition: '현재 위치에서 밝혀진 내용을 보여 주고 있습니다.',
    atEverything: '아직 읽지 않은 장의 기록도 포함되어 있습니다.',
    showEverything: '모두 보기',
    worksHeading: '작품', characters: '주요 인물', places: '장소', chapters: '장 안내', events: '연표',
    seeAll: '모두 보기',
    more: '나머지는 전체 목록에서 이어집니다.',
    nothingHere: '현재 위치에서는 여기에 아직 밝혀진 내용이 없습니다.',
    emptyTitle: '이 위키에는 아직 페이지가 없습니다',
    emptyWithWorks: '위의 작품을 다루지만 인물, 장소, 사건, 장은 아직 공개되지 않았습니다.',
    emptyNoWorks: '이 위키에 속한 작품이 아직 없습니다.',
    buildIt: '소장자는 REZICS 위키 툴킷으로 위키를 만듭니다. 자신이 가진 책에서 이름, 관계, 정확한 위치가 붙은 짧은 인용을 묶음으로 만들고, 공개 전에 관리자가 검토합니다.',
    howRun: '이 위키의 운영 방식',
    youngTitle: '이 위키는 막 시작했습니다',
    youngBody: '지금까지 있는 내용을 여기에 나열했습니다. 소장자가 장을 제출하고 관리자가 공개할수록 늘어납니다.',
    alsoKnownAs: '다른 이름', atAGlance: '한눈에 보기', relationships: '관계', relationship: '관계', firstAppears: '처음 등장',
    passages: '인용과 출처', source: '출처',
    sourceEdition: (type: string) => `${type} 판`,
    sourceAgent: (agent: string) => `${agent}이(가) 추출`,
    modality: { narrated: '서술', said: '인물의 말', rumoured: '소문', hypothetical: '가정' },
    rights: { public_domain: '퍼블릭 도메인', original_contribution: '직접 기여', unprotected_fact: '보호받지 않는 사실', license: '라이선스',
      permission: '허락', statutory_exception: '법정 예외', service_terms: '서비스 약관', unknown: '권리 미확인' },
    withheld: '권리 제한 때문에 인용문은 표시되지 않습니다. 출처는 기록되어 있습니다.',
    moreOnFull: '이 기록에는 여기에 나열된 것보다 많은 내용이 있습니다.', openFull: '전체 기록 열기',
    revealedHere: '이 장에서 밝혀지는 것', nothingNew: '이 장에서 새로 나열할 페이지가 없습니다.',
    notReached: '이 장은 현재 읽기 위치보다 뒤에 있어서 여기서 밝혀지는 내용은 숨겨집니다.',
    incomplete: '이 목록은 완전하지 않을 수 있습니다.', previous: '이전 장', next: '다음 장', chapterNav: '장',
    back: (name: string) => `${name} 전체`, kind: '종류',
  },
  de: {
    creditedAs: "als",
    nameNotShown: 'Name nicht angezeigt',
    atPosition: (label: string) => `Gezeigt wird, was bis „${label}“ verraten ist.`,
    atAnyPosition: 'Gezeigt wird, was an deiner Position verraten ist.',
    atEverything: 'Enthalten sind auch Einträge aus Kapiteln, die du vielleicht noch nicht gelesen hast.',
    showEverything: 'Alles anzeigen',
    worksHeading: 'Werke', characters: 'Hauptfiguren', places: 'Orte', chapters: 'Kapitelführer', events: 'Zeitleiste',
    seeAll: 'Alle ansehen',
    more: 'Weitere Seiten stehen in der vollständigen Liste.',
    nothingHere: 'An deiner Position ist hier noch nichts verraten.',
    emptyTitle: 'Dieses Wiki hat noch keine Seiten',
    emptyWithWorks: 'Es behandelt die oben genannten Werke, aber Figuren, Orte, Ereignisse und Kapitel sind noch nicht veröffentlicht.',
    emptyNoWorks: 'Zu diesem Wiki gehört noch kein Werk.',
    buildIt: 'Besitzer bauen ein Wiki mit dem REZICS-Wiki-Toolkit: Es macht aus ihrer eigenen Ausgabe des Buchs ein Bündel aus Namen, Beziehungen und kurzen Zitaten mit genauen Fundstellen, das ein Steward prüft, bevor etwas veröffentlicht wird.',
    howRun: 'Wie dieses Wiki betrieben wird',
    youngTitle: 'Dieses Wiki fängt gerade an',
    youngBody: 'Hier steht, was es bisher gibt. Es wächst, wenn Besitzer Kapitel einreichen und Stewards sie veröffentlichen.',
    alsoKnownAs: 'Auch bekannt als', atAGlance: 'Auf einen Blick', relationships: 'Beziehungen', relationship: 'Beziehung', firstAppears: 'Erstes Auftreten in',
    passages: 'Textstellen und Quellen', source: 'Quelle',
    sourceEdition: (type: string) => `Ausgabe (${type})`,
    sourceAgent: (agent: string) => `extrahiert von ${agent}`,
    modality: { narrated: 'Erzählt', said: 'Von einer Figur gesagt', rumoured: 'Gerücht', hypothetical: 'Hypothetisch' },
    rights: { public_domain: 'gemeinfrei', original_contribution: 'eigener Beitrag', unprotected_fact: 'ungeschützte Tatsache', license: 'lizenziert',
      permission: 'mit Erlaubnis', statutory_exception: 'gesetzliche Ausnahme', service_terms: 'nach den Nutzungsbedingungen', unknown: 'Rechte ungeklärt' },
    withheld: 'Das Zitat wird wegen einer Rechtebeschränkung zurückgehalten. Seine Quelle ist weiterhin erfasst.',
    moreOnFull: 'Dieser Eintrag enthält mehr, als hier aufgeführt ist.', openFull: 'Vollständigen Eintrag öffnen',
    revealedHere: 'In diesem Kapitel verraten', nothingNew: 'Für dieses Kapitel sind keine neuen Seiten aufgeführt.',
    notReached: 'Dieses Kapitel liegt hinter deiner Leseposition, daher bleibt verborgen, was es verrät.',
    incomplete: 'Diese Liste ist möglicherweise unvollständig.', previous: 'Vorheriges Kapitel', next: 'Nächstes Kapitel', chapterNav: 'Kapitel',
    back: (name: string) => `Alle: ${name}`, kind: 'Art',
  },
  fr: {
    creditedAs: 'sous le nom de',
    nameNotShown: 'Nom non affiché',
    atPosition: (label: string) => `Ce qui est révélé jusqu’à « ${label} » est affiché.`,
    atAnyPosition: 'Ce qui est révélé à votre position est affiché.',
    atEverything: 'Cela comprend des fiches de chapitres que vous n’avez peut-être pas lus.',
    showEverything: 'Tout afficher',
    worksHeading: 'Œuvres', characters: 'Personnages principaux', places: 'Lieux', chapters: 'Guide des chapitres', events: 'Chronologie',
    seeAll: 'Tout voir',
    more: 'D’autres pages figurent dans la liste complète.',
    nothingHere: 'Rien n’est encore révélé ici à votre position.',
    emptyTitle: 'Ce wiki n’a pas encore de pages',
    emptyWithWorks: 'Il couvre les œuvres ci-dessus, mais aucun personnage, lieu, événement ni chapitre n’est encore publié.',
    emptyNoWorks: 'Aucune œuvre ne fait encore partie de ce wiki.',
    buildIt: 'Les détenteurs construisent un wiki avec la boîte à outils wiki de REZICS : elle transforme leur propre exemplaire du livre en un lot de noms, de relations et de courtes citations aux emplacements exacts, qu’un intendant relit avant toute publication.',
    howRun: 'Comment ce wiki est tenu',
    youngTitle: 'Ce wiki ne fait que commencer',
    youngBody: 'Ce qui existe déjà est listé ici. Il s’enrichit à mesure que les détenteurs soumettent des chapitres et que les intendants les publient.',
    alsoKnownAs: 'Aussi connu comme', atAGlance: 'En bref', relationships: 'Relations', relationship: 'Relation', firstAppears: 'Première apparition dans',
    passages: 'Passages et sources', source: 'Source',
    sourceEdition: (type: string) => `édition ${type}`,
    sourceAgent: (agent: string) => `extrait par ${agent}`,
    modality: { narrated: 'Raconté', said: 'Dit par un personnage', rumoured: 'Rumeur', hypothetical: 'Hypothétique' },
    rights: { public_domain: 'domaine public', original_contribution: 'contribution originale', unprotected_fact: 'fait non protégé', license: 'sous licence',
      permission: 'avec autorisation', statutory_exception: 'exception légale', service_terms: 'selon les conditions du service', unknown: 'droits non établis' },
    withheld: 'La citation est retenue en raison d’une restriction de droits. Sa source reste enregistrée.',
    moreOnFull: 'Cette fiche contient plus que ce qui est listé ici.', openFull: 'Ouvrir la fiche complète',
    revealedHere: 'Révélé dans ce chapitre', nothingNew: 'Aucune nouvelle page n’est listée pour ce chapitre.',
    notReached: 'Ce chapitre est au-delà de votre position de lecture : ce qu’il révèle reste masqué.',
    incomplete: 'Cette liste peut être incomplète.', previous: 'Chapitre précédent', next: 'Chapitre suivant', chapterNav: 'Chapitres',
    back: (name: string) => `Tout : ${name}`, kind: 'Type',
  },
  es: {
    creditedAs: "como",
    nameNotShown: 'Nombre no mostrado',
    atPosition: (label: string) => `Se muestra lo revelado hasta «${label}».`,
    atAnyPosition: 'Se muestra lo revelado en tu posición.',
    atEverything: 'Incluye registros de capítulos que quizá no hayas leído.',
    showEverything: 'Mostrar todo',
    worksHeading: 'Obras', characters: 'Personajes principales', places: 'Lugares', chapters: 'Guía de capítulos', events: 'Cronología',
    seeAll: 'Ver todo',
    more: 'Hay más páginas en la lista completa.',
    nothingHere: 'Aquí aún no se ha revelado nada en tu posición.',
    emptyTitle: 'Este wiki aún no tiene páginas',
    emptyWithWorks: 'Abarca las obras de arriba, pero aún no se han publicado personajes, lugares, sucesos ni capítulos.',
    emptyNoWorks: 'Ninguna obra forma parte todavía de este wiki.',
    buildIt: 'Quienes tienen el libro construyen un wiki con el kit de herramientas wiki de REZICS: convierte su propio ejemplar en un lote de nombres, relaciones y citas breves con ubicaciones exactas, y un administrador lo revisa antes de publicar nada.',
    howRun: 'Cómo se gestiona este wiki',
    youngTitle: 'Este wiki acaba de empezar',
    youngBody: 'Aquí se enumera lo que ya existe. Crecerá a medida que se envíen capítulos y los administradores los publiquen.',
    alsoKnownAs: 'También conocido como', atAGlance: 'De un vistazo', relationships: 'Relaciones', relationship: 'Relación', firstAppears: 'Primera aparición en',
    passages: 'Pasajes y fuentes', source: 'Fuente',
    sourceEdition: (type: string) => `edición ${type}`,
    sourceAgent: (agent: string) => `extraído por ${agent}`,
    modality: { narrated: 'Narrado', said: 'Dicho por un personaje', rumoured: 'Rumor', hypothetical: 'Hipotético' },
    rights: { public_domain: 'dominio público', original_contribution: 'aportación original', unprotected_fact: 'hecho no protegido', license: 'con licencia',
      permission: 'con permiso', statutory_exception: 'excepción legal', service_terms: 'según las condiciones del servicio', unknown: 'derechos sin establecer' },
    withheld: 'La cita se retiene por una restricción de derechos. Su fuente sigue registrada.',
    moreOnFull: 'Este registro contiene más de lo que se enumera aquí.', openFull: 'Abrir el registro completo',
    revealedHere: 'Revelado en este capítulo', nothingNew: 'No se enumeran páginas nuevas para este capítulo.',
    notReached: 'Este capítulo está más allá de tu posición de lectura, así que lo que revela sigue oculto.',
    incomplete: 'Esta lista puede estar incompleta.', previous: 'Capítulo anterior', next: 'Capítulo siguiente', chapterNav: 'Capítulos',
    back: (name: string) => `Todo: ${name}`, kind: 'Tipo',
  },
};

export const localeStrings = translations;

export function strings(locale: string): Strings {
  return (zoneLocales as readonly string[]).includes(locale) ? translations[locale as ZoneLocale] : en;
}
